-- === 공통코드·채번 기반테이블(정합 보강: portal 정의 이식) ===
CREATE TABLE IDS  (
  TABLE_NAME varchar2(20) NOT NULL,  -- 대상 테이블명
  NEXT_ID number(30,0)DEFAULT 0 NOT NULL,  -- 다음 ID 값
  CONSTRAINT IDS_PK PRIMARY KEY (TABLE_NAME)
);
CREATE TABLE COMTECOPSEQ (
  TABLE_NAME varchar2(20) DEFAULT '' NOT NULL,  -- 대상 테이블명
  NEXT_ID number(30,0) DEFAULT 0 NOT NULL,  -- 다음 ID 값
  CONSTRAINT COMTECOPSEQ_PK PRIMARY KEY (TABLE_NAME)
) ;
CREATE TABLE TB_CMMN_CL_CODE (
  CL_CODE char(3) NOT NULL,  -- 분류코드
  CL_CODE_NM varchar2(60),  -- 분류코드명
  CL_CODE_DC varchar2(200),  -- 분류코드 설명
  USE_AT char(1),  -- 사용여부(Y/N)
  FRST_REGIST_PNTTM DATE,  -- 최초등록시각
  FRST_REGISTER_ID varchar2(20),  -- 최초등록자ID
  LAST_UPDT_PNTTM DATE,  -- 최종수정시각
  LAST_UPDUSR_ID varchar2(20),  -- 최종수정자ID
  CONSTRAINT TB_CMMN_CL_CODE_PK PRIMARY KEY (CL_CODE)
) ;
CREATE TABLE TB_CMMN_CODE (
  CODE_ID varchar2(6) NOT NULL,  -- 코드ID
  CODE_ID_NM varchar2(60),  -- 코드ID명
  CODE_ID_DC varchar2(200),  -- 코드ID 설명
  USE_AT char(1),  -- 사용여부(Y/N)
  CL_CODE char(3),  -- 분류코드
  FRST_REGIST_PNTTM DATE,  -- 최초등록시각
  FRST_REGISTER_ID varchar2(20),  -- 최초등록자ID
  LAST_UPDT_PNTTM DATE,  -- 최종수정시각
  LAST_UPDUSR_ID varchar2(20),  -- 최종수정자ID
  CONSTRAINT TB_CMMN_CODE_PK PRIMARY KEY (CODE_ID),
  CONSTRAINT TB_CMMN_CODE_ibfk_1 FOREIGN KEY (CL_CODE) REFERENCES TB_CMMN_CL_CODE (CL_CODE)
) ;
CREATE TABLE TB_CMMN_DETAIL_CODE (
  CODE_ID varchar2(6) NOT NULL,  -- 코드ID
  CODE varchar2(15) NOT NULL,  -- 상세코드
  CODE_NM varchar2(60),  -- 상세코드명
  CODE_DC varchar2(200),  -- 상세코드 설명
  USE_AT char(1),  -- 사용여부(Y/N)
  FRST_REGIST_PNTTM DATE,  -- 최초등록시각
  FRST_REGISTER_ID varchar2(20),  -- 최초등록자ID
  LAST_UPDT_PNTTM DATE,  -- 최종수정시각
  LAST_UPDUSR_ID varchar2(20),  -- 최종수정자ID
  CONSTRAINT TB_CMMN_DETAIL_CODE_PK PRIMARY KEY (CODE_ID,CODE),
  CONSTRAINT TB_CMMN_DETAIL_CODE_ibfk_1 FOREIGN KEY (CODE_ID) REFERENCES TB_CMMN_CODE (CODE_ID)
) ;

-- === foundation 테이블 보강(정합: portal/biz 이식) ===
CREATE TABLE TB_ORGNZT_INFO (
  ORGNZT_ID char(20) DEFAULT '' NOT NULL,  -- 조직ID
  ORGNZT_NM varchar2(20) NOT NULL,  -- 조직명
  ORGNZT_DC varchar2(100),  -- 조직 설명
  CONSTRAINT TB_ORGNZT_INFO_PK PRIMARY KEY (ORGNZT_ID)
) ;
CREATE TABLE TB_AUTHOR_INFO (
  AUTHOR_CODE varchar2(30) DEFAULT '' NOT NULL,  -- 권한코드
  AUTHOR_NM varchar2(60) NOT NULL,  -- 권한명
  AUTHOR_DC varchar2(200),  -- 권한 설명
  AUTHOR_CREAT_DE char(20) NOT NULL,  -- 생성일자
  CONSTRAINT TB_AUTHOR_INFO_PK PRIMARY KEY (AUTHOR_CODE)
) ;
CREATE TABLE TB_AUTHOR_GROUP_INFO (
  GROUP_ID char(20) DEFAULT '' NOT NULL,  -- 그룹ID
  GROUP_NM varchar2(60) NOT NULL,  -- 그룹명
  GROUP_CREAT_DE char(20) NOT NULL,  -- 생성일자
  GROUP_DC varchar2(100),  -- 그룹 설명
  CONSTRAINT TB_AUTHOR_GROUP_INFO_PK PRIMARY KEY (GROUP_ID)
) ;
CREATE TABLE TB_EMPLYR_INFO (
  EMPLYR_ID varchar2(20) NOT NULL,  -- 사용자ID
  ORGNZT_ID char(20),  -- 조직ID
  USER_NM varchar2(60) NOT NULL,  -- 사용자명
  PASSWORD varchar2(200) NOT NULL,  -- 비밀번호(해시)
  EMPL_NO varchar2(20),  -- 사번
  IHIDNUM varchar2(200),  -- 주민등록번호
  SEXDSTN_CODE char(1),  -- 성별코드
  BRTHDY char(20),  -- 생년월일
  FXNUM varchar2(20),  -- 팩스
  HOUSE_ADRES varchar2(100),  -- 자택주소
  PASSWORD_HINT varchar2(100) NOT NULL,  -- 비밀번호 힌트
  PASSWORD_CNSR varchar2(100) NOT NULL,  -- 비밀번호 정답
  HOUSE_END_TELNO varchar2(4),  -- 자택전화 끝번호
  AREA_NO varchar2(4),  -- 지역번호
  DETAIL_ADRES varchar2(100),  -- 상세주소
  ZIP varchar2(6),  -- 우편번호
  OFFM_TELNO varchar2(20),  -- 사무실전화
  MBTLNUM varchar2(20),  -- 휴대전화
  EMAIL_ADRES varchar2(50),  -- 이메일
  OFCPS_NM varchar2(60),  -- 직책명
  HOUSE_MIDDLE_TELNO varchar2(4),  -- 자택전화 중간번호
  GROUP_ID char(20),  -- 그룹ID
  PSTINST_CODE char(8),  -- 소속기관코드
  EMPLYR_STTUS_CODE varchar2(15) NOT NULL,  -- 사용자상태코드
  ESNTL_ID char(20) NOT NULL,  -- 고유ID
  CRTFC_DN_VALUE varchar2(20),  -- 인증DN
  SBSCRB_DE DATE,  -- 가입일시
  CONSTRAINT TB_EMPLYR_INFO_PK PRIMARY KEY (EMPLYR_ID),
  CONSTRAINT TB_EMPLYR_INFO_ibfk_2 FOREIGN KEY (GROUP_ID) REFERENCES TB_AUTHOR_GROUP_INFO (GROUP_ID) ON DELETE CASCADE,
  CONSTRAINT TB_EMPLYR_INFO_ibfk_1 FOREIGN KEY (ORGNZT_ID) REFERENCES TB_ORGNZT_INFO (ORGNZT_ID) ON DELETE CASCADE
) ;
CREATE TABLE TB_GNRL_MBER (
  MBER_ID varchar2(20) DEFAULT '' NOT NULL,  -- 회원ID
  PASSWORD varchar2(200) NOT NULL,  -- 비밀번호(해시)
  PASSWORD_HINT varchar2(100) NOT NULL,  -- 비밀번호 힌트
  PASSWORD_CNSR varchar2(100) NOT NULL,  -- 비밀번호 정답
  IHIDNUM varchar2(200),  -- 주민등록번호
  MBER_NM varchar2(50) NOT NULL,  -- 회원명
  ZIP varchar2(6),  -- 우편번호
  ADRES varchar2(100),  -- 주소
  AREA_NO varchar2(4),  -- 지역번호
  MBER_STTUS varchar2(15),  -- 회원상태코드
  DETAIL_ADRES varchar2(100),  -- 상세주소
  END_TELNO varchar2(4),  -- 전화 끝번호
  MBTLNUM varchar2(20),  -- 휴대전화
  GROUP_ID char(20),  -- 그룹ID
  MBER_FXNUM varchar2(20),  -- 팩스번호
  MBER_EMAIL_ADRES varchar2(50),  -- 이메일주소
  MIDDLE_TELNO varchar2(4),  -- 전화 중간번호
  SBSCRB_DE DATE,  -- 가입일시
  SEXDSTN_CODE char(1),  -- 성별코드
  ESNTL_ID char(20) NOT NULL,  -- 고유ID
  CONSTRAINT TB_GNRL_MBER_PK PRIMARY KEY (MBER_ID),
  CONSTRAINT TB_GNRL_MBER_ibfk_1 FOREIGN KEY (GROUP_ID) REFERENCES TB_AUTHOR_GROUP_INFO (GROUP_ID) ON DELETE CASCADE
) ;
CREATE TABLE TB_ENTRPRS_MBER (
  ENTRPRS_MBER_ID varchar2(20) DEFAULT '' NOT NULL,  -- 기업회원ID
  ENTRPRS_SE_CODE char(15),  -- 기업구분코드
  BIZRNO varchar2(10),  -- 사업자등록번호
  JURIRNO varchar2(13),  -- 법인등록번호
  CMPNY_NM varchar2(60) NOT NULL,  -- 회사명
  CXFC varchar2(50),  -- 대표자명
  ZIP varchar2(6),  -- 우편번호
  ADRES varchar2(100),  -- 주소
  ENTRPRS_MIDDLE_TELNO varchar2(4),  -- 전화 중간번호
  FXNUM varchar2(20),  -- 팩스
  INDUTY_CODE char(15),  -- 업종코드
  APPLCNT_NM varchar2(50),  -- 신청자명
  APPLCNT_IHIDNUM varchar2(200),  -- 신청자 주민등록번호
  SBSCRB_DE DATE,  -- 가입일시
  ENTRPRS_MBER_STTUS varchar2(15),  -- 회원상태코드
  ENTRPRS_MBER_PASSWORD varchar2(200) NOT NULL,  -- 비밀번호(해시)
  ENTRPRS_MBER_PASSWORD_HINT varchar2(100) NOT NULL,  -- 비밀번호 힌트
  ENTRPRS_MBER_PASSWORD_CNSR varchar2(100) NOT NULL,  -- 비밀번호 정답
  GROUP_ID char(20),  -- 그룹ID
  DETAIL_ADRES varchar2(100),  -- 상세주소
  ENTRPRS_END_TELNO varchar2(4),  -- 전화 끝번호
  AREA_NO varchar2(4),  -- 지역번호
  APPLCNT_EMAIL_ADRES varchar2(50),  -- 신청자 이메일
  ESNTL_ID char(20) NOT NULL,  -- 고유ID
  CONSTRAINT TB_ENTRPRS_MBER_PK PRIMARY KEY (ENTRPRS_MBER_ID),
  CONSTRAINT TB_ENTRPRS_MBER_ibfk_1 FOREIGN KEY (GROUP_ID) REFERENCES TB_AUTHOR_GROUP_INFO (GROUP_ID) ON DELETE CASCADE
) ;
CREATE TABLE TB_BBS_MASTER (
  BBS_ID char(20) NOT NULL,  -- 게시판ID
  BBS_NM varchar2(255) NOT NULL,  -- 게시판명
  BBS_INTRCN varchar2(2400),  -- 게시판 소개
  BBS_TY_CODE char(6) NOT NULL,  -- 게시판 유형코드
  BBS_ATTRB_CODE char(6) NOT NULL,  -- 게시판 속성코드
  REPLY_POSBL_AT char(1),  -- 답글 가능(Y/N)
  FILE_ATCH_POSBL_AT char(1) NOT NULL,  -- 파일첨부 가능(Y/N)
  ATCH_POSBL_FILE_NUMBER number(2,0) NOT NULL,  -- 첨부가능 파일 수
  ATCH_POSBL_FILE_SIZE number(8,0),  -- 첨부가능 총 용량(단위: 시스템 정의)
  USE_AT char(1) NOT NULL,  -- 사용여부(Y/N)
  TMPLAT_ID char(20),  -- 템플릿ID
  FRST_REGISTER_ID varchar2(20) NOT NULL,  -- 최초등록자ID
  FRST_REGIST_PNTTM DATE NOT NULL,  -- 최초등록시각
  LAST_UPDUSR_ID varchar2(20),  -- 최종수정자ID
  LAST_UPDT_PNTTM DATE,  -- 최종수정시각
  CONSTRAINT TB_BBS_MASTER_PK PRIMARY KEY (BBS_ID)
) ;
CREATE TABLE TB_BBS_USE (
  BBS_ID char(20) NOT NULL,  -- 게시판ID
  TRGET_ID char(20) DEFAULT '' NOT NULL,  -- 사용대상ID
  USE_AT char(1) NOT NULL,  -- 사용여부(Y/N)
  REGIST_SE_CODE char(6),  -- 등록구분코드
  FRST_REGIST_PNTTM DATE,  -- 최초등록시각
  FRST_REGISTER_ID varchar2(20) NOT NULL,  -- 최초등록자ID
  LAST_UPDT_PNTTM DATE,  -- 최종수정시각
  LAST_UPDUSR_ID varchar2(20),  -- 최종수정자ID
  CONSTRAINT TB_BBS_USE_PK PRIMARY KEY (BBS_ID,TRGET_ID),
  CONSTRAINT TB_BBS_USE_ibfk_1 FOREIGN KEY (BBS_ID) REFERENCES TB_BBS_MASTER (BBS_ID)
) ;
CREATE TABLE TB_BBS (
  NTT_ID number(20,0) NOT NULL,  -- 게시물ID
  BBS_ID char(20) NOT NULL,  -- 게시판ID
  NTT_NO number(20,0),  -- 게시물 번호(정렬/표시용)
  NTT_SJ varchar2(2000),  -- 제목
  NTT_CN CLOB,  -- 내용
  ANSWER_AT char(1),  -- 답변글 여부(Y/N)
  PARNTSCTT_NO number(10,0),  -- 부모글 번호
  ANSWER_LC number(8),  -- 답변 계층(레벨)
  SORT_ORDR number(8,0),  -- 정렬순서
  RDCNT number(10,0),  -- 조회수
  USE_AT char(1) NOT NULL,  -- 사용여부(Y/N)
  NTCE_BGNDE char(20),  -- 공지 시작일시
  NTCE_ENDDE char(20),  -- 공지 종료일시
  NTCR_ID varchar2(20),  -- 게시자ID
  NTCR_NM varchar2(20),  -- 게시자명
  PASSWORD varchar2(200),  -- 비밀번호(해시)
  ATCH_FILE_ID char(20),  -- 첨부파일 묶음ID
  FRST_REGIST_PNTTM DATE NOT NULL,  -- 최초등록시각
  FRST_REGISTER_ID varchar2(20) NOT NULL,  -- 최초등록자ID
  LAST_UPDT_PNTTM DATE,  -- 최종수정시각
  LAST_UPDUSR_ID varchar2(20),  -- 최종수정자ID
  CONSTRAINT TB_BBS_PK PRIMARY KEY (NTT_ID,BBS_ID),
  CONSTRAINT TB_BBS_ibfk_1 FOREIGN KEY (BBS_ID) REFERENCES TB_BBS_MASTER (BBS_ID)
) ;
CREATE TABLE TB_TMPLAT_INFO (
  TMPLAT_ID char(20) DEFAULT '' NOT NULL,  -- 템플릿ID
  TMPLAT_NM varchar2(255),  -- 템플릿명
  TMPLAT_COURS varchar2(2000),  -- 템플릿COURS
  USE_AT char(1),  -- 사용여부(Y/N)
  TMPLAT_SE_CODE char(6),  -- 템플릿구분상세코드
  FRST_REGISTER_ID varchar2(20),  -- 최초등록자ID
  FRST_REGIST_PNTTM DATE,  -- 최초등록시각
  LAST_UPDUSR_ID varchar2(20),  -- 최종수정자ID
  LAST_UPDT_PNTTM DATE,  -- 최종수정시각
  CONSTRAINT TB_TMPLAT_INFO_PK PRIMARY KEY (TMPLAT_ID)
) ;
CREATE TABLE TB_FAQ_INFO (
  FAQ_ID char(20) NOT NULL,  -- FAQID
  QESTN_SJ varchar2(255),  -- 질문제목
  QESTN_CN varchar2(2500),  -- 질문내용
  ANSWER_CN varchar2(2500),  -- 답변내용
  RDCNT number(10,0),  -- 조회수
  FRST_REGIST_PNTTM DATE NOT NULL,  -- 최초등록시각
  FRST_REGISTER_ID varchar2(20) NOT NULL,  -- 최초등록자ID
  LAST_UPDT_PNTTM DATE NOT NULL,  -- 최종수정시각
  LAST_UPDUSR_ID varchar2(20) NOT NULL,  -- 최종수정자ID
  ATCH_FILE_ID char(20),  -- 첨부파일 묶음ID
  QNA_PROCESS_STTUS_CODE char(1),  -- 질의응답처리상태상세코드
  CONSTRAINT TB_FAQ_INFO_PK PRIMARY KEY (FAQ_ID),
  CONSTRAINT TB_FAQ_INFO_ibfk_1 FOREIGN KEY (ATCH_FILE_ID) REFERENCES TB_FILE (ATCH_FILE_ID)
) ;
CREATE TABLE TB_QA_INFO (
  QA_ID char(20) NOT NULL,  -- 질의응답ID
  QESTN_SJ varchar2(255),  -- 질문제목
  QESTN_CN varchar2(2500),  -- 질문내용
  WRITNG_DE char(20),  -- 작성일자
  RDCNT number(10,0),  -- 조회수
  EMAIL_ADRES varchar2(50),  -- 이메일
  FRST_REGIST_PNTTM DATE,  -- 최초등록시각
  FRST_REGISTER_ID varchar2(20),  -- 최초등록자ID
  LAST_UPDT_PNTTM DATE,  -- 최종수정시각
  LAST_UPDUSR_ID varchar2(20),  -- 최종수정자ID
  QNA_PROCESS_STTUS_CODE char(1),  -- 질의응답처리상태상세코드
  WRTER_NM varchar2(20),  -- WRTER명
  ANSWER_CN varchar2(2500),  -- 답변내용
  WRITNG_PASSWORD varchar2(20),  -- 작성비밀번호(해시)
  ANSWER_DE char(20),  -- 답변일자
  EMAIL_ANSWER_AT char(1),  -- 이메일답변여부
  AREA_NO varchar2(4),  -- 지역번호
  MIDDLE_TELNO varchar2(4),  -- 전화 중간번호
  END_TELNO varchar2(4),  -- 전화 끝번호
  CONSTRAINT TB_QA_INFO_PK PRIMARY KEY (QA_ID)
) ;
CREATE TABLE TB_RESTDE (
  RESTDE_NO number(20,0) NOT NULL,  -- 휴일번호
  RESTDE_DE char(8) NOT NULL,  -- 휴일일자
  RESTDE_NM varchar2(100) NOT NULL,  -- 휴일명
  RESTDE_DC varchar2(200),  -- 휴일설명
  RESTDE_SE_CODE char(6),  -- 휴일구분상세코드
  FRST_REGIST_PNTTM DATE,  -- 최초등록시각
  FRST_REGISTER_ID varchar2(20),  -- 최초등록자ID
  LAST_UPDT_PNTTM DATE,  -- 최종수정시각
  LAST_UPDUSR_ID varchar2(20),  -- 최종수정자ID
  CONSTRAINT TB_RESTDE_PK PRIMARY KEY (RESTDE_NO)
) ;
CREATE TABLE TB_SCHDUL_INFO (
  SCHDUL_ID char(20) NOT NULL,  -- 일정ID
  SCHDUL_SE char(1),  -- 일정구분코드
  SCHDUL_DEPT_ID varchar2(20),  -- 부서ID
  SCHDUL_KND_CODE varchar2(20),  -- 일정종류코드
  SCHDUL_BEGINDE DATE,  -- 시작일시
  SCHDUL_ENDDE DATE,  -- 종료일시
  SCHDUL_NM varchar2(255),  -- 일정명
  SCHDUL_CN varchar2(2500),  -- 일정 내용
  SCHDUL_PLACE varchar2(255),  -- 장소
  SCHDUL_IPCR_CODE char(1),  -- 중요도코드
  SCHDUL_CHARGER_ID varchar2(20),  -- 담당자ID
  ATCH_FILE_ID char(20),  -- 첨부파일 묶음ID
  REPTIT_SE_CODE char(3),  -- 반복구분코드
  FRST_REGIST_PNTTM DATE,  -- 최초등록시각
  FRST_REGISTER_ID varchar2(20),  -- 최초등록자ID
  LAST_UPDT_PNTTM DATE,  -- 최종수정시각
  LAST_UPDUSR_ID varchar2(20),  -- 최종수정자ID
  CONSTRAINT TB_SCHDUL_INFO_PK PRIMARY KEY (SCHDUL_ID)
) ;
CREATE TABLE TB_LOGIN_LOG  (
  LOG_ID char(20) NOT NULL,  -- 로그ID
  CONECT_MTHD char(1),  -- 접속방식
  CONECT_ID varchar2(20),  -- 접속ID
  CONECT_IP varchar2(23),  -- 접속IP
  ERROR_OCCRRNC_AT char(1),  -- 오류발생여부
  ERROR_CODE varchar2(3),  -- 오류상세코드
  CREAT_DT DATE,  -- 생성시각
  FRST_REGIST_PNTTM DATE,  -- 최초등록시각
  FRST_REGISTER_ID varchar2(20),  -- 최초등록자ID
  LAST_UPDT_PNTTM DATE,  -- 최종수정시각
  LAST_UPDUSR_ID varchar2(20),  -- 최종수정자ID
  CONSTRAINT TB_LOGIN_LOG_PK PRIMARY KEY (LOG_ID)
) ;
CREATE TABLE TB_SYS_LOG  (
  REQUST_ID char(20) NOT NULL,  -- 요청ID
  OCCRRNC_DE char(20),  -- 발생일자
  SVC_NM varchar2(200),  -- 봉사명
  METHOD_NM varchar2(60),  -- METHOD명
  PROCESS_SE_CODE varchar2(15),  -- 처리구분상세코드
  PROCESS_TIME varchar2(14),  -- 처리시간
  RQESTER_ID varchar2(20),  -- RQESTERID
  RQESTER_IP varchar2(23),  -- RQESTERIP
  FRST_REGIST_PNTTM DATE,  -- 최초등록시각
  FRST_REGISTER_ID varchar2(20),  -- 최초등록자ID
  LAST_UPDT_PNTTM DATE,  -- 최종수정시각
  LAST_UPDUSR_ID varchar2(20),  -- 최종수정자ID
  CONSTRAINT TB_SYS_LOG_PK PRIMARY KEY (REQUST_ID)
) ;
CREATE TABLE TB_CONECT_LOG  (
  LOG_ID number(20,0) DEFAULT 0 NOT NULL,  -- 로그ID
  SRVC_NM varchar2(60),  -- 서비스명
  METHOD_NM varchar2(60),  -- METHOD명
  OCCRRNC_DE char(8),  -- 발생일자
  CREAT_CO number(10,0) DEFAULT 0,  -- 생성수
  UPDT_CO number(10,0) DEFAULT 0,  -- 갱신수
  RDCNT number(10,0) DEFAULT 0,  -- 조회수
  DELETE_CO number(10,0) DEFAULT 0,  -- 삭제수
  OUTPT_CO number(10,0) DEFAULT 0,  -- OUTPT수
  ERROR_CO number(10,0) DEFAULT 0,  -- 오류수
  CONECT_ID varchar2(20),  -- 접속ID
  CONECT_IP varchar2(23),  -- 접속IP
  CONECT_MTHD char(1),  -- 접속방식
  ERROR_OCCRRNC_AT char(1),  -- 오류발생여부
  ERROR_CODE varchar2(3),  -- 오류상세코드
  CREAT_DT DATE,  -- 생성시각
  FRST_REGIST_PNTTM DATE,  -- 최초등록시각
  FRST_REGISTER_ID varchar2(20),  -- 최초등록자ID
  LAST_UPDT_PNTTM DATE,  -- 최종수정시각
  LAST_UPDUSR_ID varchar2(20),  -- 최종수정자ID
  CONSTRAINT TB_CONECT_LOG_PK PRIMARY KEY (LOG_ID)
) ;
CREATE TABLE TB_LOGIN_POLICY  (
  EMPLYR_ID varchar2(20) NOT NULL,  -- 사용자ID
  IP_INFO varchar2(23),  -- IP정보
  DPLCT_PERM_AT char(1) DEFAULT 'Y',  -- DPLCTPERM여부
  LMTT_AT char(1) DEFAULT 'N',  -- LMTT여부
  FRST_REGIST_PNTTM DATE,  -- 최초등록시각
  FRST_REGISTER_ID varchar2(20),  -- 최초등록자ID
  LAST_UPDT_PNTTM DATE,  -- 최종수정시각
  LAST_UPDUSR_ID varchar2(20),  -- 최종수정자ID
  CONSTRAINT TB_LOGIN_POLICY_PK PRIMARY KEY (EMPLYR_ID)
) ;
CREATE TABLE TB_PROGRM_CHANGE_DTLS (
  PROGRM_FILE_NM     VARCHAR2(180) NOT NULL,  -- 프로그램파일명
  REQUST_NO          NUMBER(10)    DEFAULT 0 NOT NULL,  -- 요청번호
  PROGRM_KOREAN_NM   VARCHAR2(60),  -- 프로그램KOREAN명
  RQESTER_ID         VARCHAR2(20),  -- RQESTERID
  CHANGE_REQUST_CN   VARCHAR2(2500),  -- 변경요청내용
  REQUST_PROCESS_CN  VARCHAR2(2500),  -- 요청처리내용
  OPETR_ID           VARCHAR2(20),  -- OPETRID
  PROCESS_STTUS_CODE VARCHAR2(15),  -- 처리상태상세코드
  PROCESS_DE         VARCHAR2(20),  -- 처리일자
  REQUST_DE          VARCHAR2(20),  -- 요청일자
  REQUST_SJ          VARCHAR2(100),  -- 요청제목
  CONSTRAINT TB_PROGRM_CHANGE_DTLS_PK PRIMARY KEY (PROGRM_FILE_NM, REQUST_NO)
) ;

-- 개정이력: 2026.06.30  구재호  전 DBMS TB_ 표준 명명 현행화(공통컴포넌트)
-- ============================================================
-- common-components-boot Tibero DDL (shtdb.sql HSQL 정본에서 생성)
-- 명명규칙: TB_ + snake_case / 감사컬럼 4종(FRST_REGIST_PNTTM, FRST_REGISTER_ID, LAST_UPDT_PNTTM, LAST_UPDUSR_ID)
-- 사용: tibero 에 적재 (DB명 예: ccm)
-- ============================================================

DROP VIEW VW_USER_MASTER;
DROP TABLE TB_MEMO_TODO;
DROP TABLE TB_COMMENT;
DROP TABLE TB_ADBK_MANAGE;
DROP TABLE TB_DAM_KNO_IFM;
DROP TABLE TB_NCRD;
DROP TABLE TB_BATCH_RESULT;
DROP TABLE TB_BATCH_SCHDUL;
DROP TABLE TB_BATCH_OPERT;
DROP TABLE TB_CNSLT_LIST;
DROP TABLE TB_CPYRHT_INFO;
DROP TABLE TB_ONLINE_MANUAL;
DROP TABLE TB_ONLINE_POLL_IEM;
DROP TABLE TB_ONLINE_POLL_MANAGE;
DROP TABLE TB_BNDT_CECK_MANAGE;
DROP TABLE TB_BNDT_DIARY;
DROP TABLE TB_BNDT_MANAGE;
DROP TABLE TB_VCATN_MANAGE;
DROP TABLE TB_EVENT_INFO;
DROP TABLE TB_RECENT_SRCHWRD;
DROP TABLE TB_RECENT_SRCHWRD_MANAGE;
DROP TABLE TB_MTG_INFO;
DROP TABLE TB_ANNVRSRY_MANAGE;
DROP TABLE TB_INDVDL_YRYC_MANAGE;
DROP TABLE TB_NOTE_RECPTN;
DROP TABLE TB_NOTE_TRNSMIT;
DROP TABLE TB_NOTE;
DROP TABLE TB_ADMINISTRATION_WORD;
DROP TABLE TB_COMMUTE;
DROP TABLE TB_HPCM_INFO;
DROP TABLE TB_INDVDL_PGE_CNTNTS;
DROP TABLE TB_WORD_DICARY_INFO;
DROP TABLE TB_MTG_PLACE_MANAGE;
DROP TABLE TB_LOGIN_SCRIN_IMAGE;
DROP TABLE TB_MAIN_IMAGE;
DROP TABLE TB_NEWS_INFO;
DROP TABLE TB_RWARD_MANAGE;
DROP TABLE TB_EVENT_MANAGE;
DROP TABLE TB_WIKI_BKMK;
DROP TABLE TB_POPUP_MANAGE;
DROP TABLE TB_SITE_LIST;
DROP TABLE TB_UNITY_LINK;
DROP TABLE TB_ROUGHMAP;
DROP TABLE TB_RECOMEND_SITE_INFO;
DROP TABLE TB_INTNET_SVC;
DROP TABLE TB_NTFC_INFO;
DROP TABLE TB_RSS;
DROP TABLE TB_CTSNN_MANAGE;
DROP TABLE TB_STPLAT_INFO;
DROP TABLE TB_QUSTNR_RSPNS_RESULT;
DROP TABLE TB_QUSTNR_RESPOND_INFO;
DROP TABLE TB_QUSTNR_IEM;
DROP TABLE TB_QUSTNR_QESITM;
DROP TABLE TB_QESTNR_INFO;
DROP TABLE TB_QUSTNR_TMPLAT;
DROP TABLE TB_MENU_CREAT_DTLS;
DROP TABLE TB_MENU_INFO;
DROP TABLE TB_PROGRM_LIST;
DROP TABLE TB_INDVDL_INFO_POLICY;
DROP TABLE TB_BANNER;
DROP TABLE TB_ZIP;
DROP TABLE TB_AUTHOR_ROLE_RELATE;
DROP TABLE TB_ROLE_INFO;
DROP TABLE TB_ROLES_HIERARCHY;

CREATE TABLE TB_ROLES_HIERARCHY (
  PARNTS_ROLE VARCHAR2(30) NOT NULL,  -- 부모롤
  CHLDRN_ROLE VARCHAR2(30) NOT NULL,  -- 자식롤
  PRIMARY KEY (PARNTS_ROLE,CHLDRN_ROLE)
);
CREATE TABLE TB_ROLE_INFO (
  ROLE_CODE VARCHAR2(50) DEFAULT '' NOT NULL,  -- 역할코드
  ROLE_NM VARCHAR2(60) NOT NULL,  -- 역할명
  ROLE_PTTRN VARCHAR2(300) DEFAULT NULL,  -- 롤PTTRN
  ROLE_DC VARCHAR2(200) DEFAULT NULL,  -- 역할설명
  ROLE_TY VARCHAR2(80) DEFAULT NULL,  -- 역할유형
  ROLE_SORT VARCHAR2(10) DEFAULT NULL,  -- 역할정렬
  ROLE_CREAT_DE char(20) NOT NULL,  -- 롤생성일자
  PRIMARY KEY (ROLE_CODE)
);
CREATE TABLE TB_AUTHOR_ROLE_RELATE (
  AUTHOR_CODE VARCHAR2(30) NOT NULL,  -- 권한코드
  ROLE_CODE VARCHAR2(50) NOT NULL,  -- 역할코드
  CREAT_DT date DEFAULT NULL,  -- 생성시각
  PRIMARY KEY (AUTHOR_CODE,ROLE_CODE)
);
CREATE TABLE TB_ZIP (
  ZIP VARCHAR2(6) NOT NULL,  -- 우편번호
  SN number(10,0) DEFAULT '0' NOT NULL,  -- 일련번호
  CTPRVN_NM VARCHAR2(20) DEFAULT NULL,  -- 시도명
  SIGNGU_NM VARCHAR2(20) DEFAULT NULL,  -- 시군구명
  EMD_NM VARCHAR2(60) DEFAULT NULL,  -- 읍면동명
  LI_BULD_NM VARCHAR2(60) DEFAULT NULL,  -- 리건물명
  LNBR_DONG_HO VARCHAR2(20) DEFAULT NULL,  -- 지번동호
  FRST_REGIST_PNTTM date DEFAULT NULL,  -- 최초등록시각
  FRST_REGISTER_ID VARCHAR2(20) DEFAULT NULL,  -- 최초등록자ID
  LAST_UPDT_PNTTM date DEFAULT NULL,  -- 최종수정시각
  LAST_UPDUSR_ID VARCHAR2(20) DEFAULT NULL,  -- 최종수정자ID
  PRIMARY KEY (ZIP,SN)
);
CREATE TABLE TB_BANNER (
  BANNER_ID char(20) DEFAULT '' NOT NULL,  -- 배너ID
  BANNER_NM VARCHAR2(60) NOT NULL,  -- 배너명
  LINK_URL VARCHAR2(255) DEFAULT NULL,  -- 연계URL
  BANNER_IMAGE VARCHAR2(60) DEFAULT NULL,  -- 배너이미지
  BANNER_DC VARCHAR2(200) DEFAULT NULL,  -- 배너설명
  REFLCT_AT char(1) NOT NULL,  -- REFLCT여부
  FRST_REGISTER_ID VARCHAR2(20) DEFAULT NULL,  -- 최초등록자ID
  FRST_REGIST_PNTTM date DEFAULT NULL,  -- 최초등록시각
  LAST_UPDUSR_ID VARCHAR2(20) DEFAULT NULL,  -- 최종수정자ID
  LAST_UPDT_PNTTM date DEFAULT NULL,  -- 최종수정시각
  BANNER_IMAGE_FILE VARCHAR2(60) DEFAULT NULL,  -- 배너이미지파일
  SORT_ORDR number(8,0) DEFAULT NULL,  -- 정렬순서
  BANNER_TY VARCHAR2(10) DEFAULT 'MAIN',  -- 배너유형
  POPUP_LEFT INT DEFAULT NULL,  -- 팝업LEFT
  POPUP_TOP INT DEFAULT NULL,  -- 팝업TOP
  POPUP_WIDTH INT DEFAULT NULL,  -- 팝업너비
  POPUP_HEIGHT INT DEFAULT NULL,  -- 팝업HEIGHT
  POPUP_GROUP_AT char(1) DEFAULT 'N',  -- 팝업그룹여부
  EXPSR_BGNDE DATE DEFAULT NULL,  -- 노출시작일자
  EXPSR_ENDDE DATE DEFAULT NULL,  -- 노출종료일자
  PRIMARY KEY (BANNER_ID)
);
CREATE TABLE TB_INDVDL_INFO_POLICY (
  INDVDL_INFO_POLICY_ID char(20) DEFAULT '' NOT NULL,  -- 개인정보정책ID
  INDVDL_INFO_POLICY_CN VARCHAR2(2500) DEFAULT NULL,  -- 개인정보정책내용
  INDVDL_INFO_POLICY_AGRE_AT char(1) DEFAULT NULL,  -- 개인정보정책동의여부
  VER VARCHAR2(20) DEFAULT NULL,  -- 버전
  APLC_DE VARCHAR2(8) DEFAULT NULL,  -- 응용일자
  REPRSNT_AT char(1) DEFAULT 'N',  -- REPRSNT여부
  USE_AT char(1) DEFAULT 'Y',  -- 사용여부(Y/N)
  FRST_REGISTER_ID VARCHAR2(20) DEFAULT NULL,  -- 최초등록자ID
  FRST_REGIST_PNTTM date DEFAULT NULL,  -- 최초등록시각
  LAST_UPDUSR_ID VARCHAR2(20) DEFAULT NULL,  -- 최종수정자ID
  LAST_UPDT_PNTTM date DEFAULT NULL,  -- 최종수정시각
  INDVDL_INFO_POLICY_NM VARCHAR2(255) DEFAULT NULL,  -- 개인정보정책명
  PRIMARY KEY (INDVDL_INFO_POLICY_ID)
);
CREATE TABLE TB_PROGRM_LIST (
  PROGRM_FILE_NM VARCHAR2(60) DEFAULT '' NOT NULL,  -- 프로그램파일명
  PROGRM_STRE_PATH VARCHAR2(100) NOT NULL,  -- 프로그램STRE경로
  PROGRM_KOREAN_NM VARCHAR2(60) DEFAULT NULL,  -- 프로그램KOREAN명
  PROGRM_DC VARCHAR2(200) DEFAULT NULL,  -- 프로그램설명
  URL VARCHAR2(100) NOT NULL,  -- URL
  PRIMARY KEY (PROGRM_FILE_NM)
);
CREATE TABLE TB_MENU_INFO (
  MENU_NM VARCHAR2(60) NOT NULL,  -- 메뉴명
  PROGRM_FILE_NM VARCHAR2(60) NOT NULL,  -- 프로그램파일명
  MENU_NO number(20,0) NOT NULL,  -- 메뉴번호
  UPPER_MENU_NO number(20,0) DEFAULT NULL,  -- UPPER메뉴번호
  MENU_ORDR number(5,0) NOT NULL,  -- 메뉴순서
  MENU_DC VARCHAR2(250) DEFAULT NULL,  -- 메뉴설명
  RELATE_IMAGE_PATH VARCHAR2(100) DEFAULT NULL,  -- 관련이미지경로
  RELATE_IMAGE_NM VARCHAR2(60) DEFAULT NULL,  -- 관련이미지명
  PRIMARY KEY (MENU_NO)
);
CREATE TABLE TB_MENU_CREAT_DTLS (
  MENU_NO number(20,0) NOT NULL,  -- 메뉴번호
  AUTHOR_CODE VARCHAR2(30) NOT NULL,  -- 권한코드
  MAPNG_CREAT_ID VARCHAR2(30) DEFAULT NULL,  -- MAPNG생성ID
  PRIMARY KEY (MENU_NO,AUTHOR_CODE)
);
CREATE TABLE TB_QUSTNR_TMPLAT (
  QUSTNR_TMPLAT_ID char(20) NOT NULL,  -- 설문템플릿ID
  QUSTNR_TMPLAT_TY VARCHAR2(100) DEFAULT NULL,  -- 설문템플릿유형
  QUSTNR_TMPLAT_DC VARCHAR2(2000) DEFAULT NULL,  -- 설문템플릿설명
  QUSTNR_TMPLAT_PATH_NM VARCHAR2(100) DEFAULT NULL,  -- 설문템플릿경로명
  FRST_REGIST_PNTTM date DEFAULT NULL,  -- 최초등록시각
  FRST_REGISTER_ID VARCHAR2(20) DEFAULT NULL,  -- 최초등록자ID
  LAST_UPDT_PNTTM date DEFAULT NULL,  -- 최종수정시각
  LAST_UPDUSR_ID VARCHAR2(20) DEFAULT NULL,  -- 최종수정자ID
  QUSTNR_TMPLAT_IMAGE_INFO blob,  -- 설문템플릿이미지정보
  PRIMARY KEY (QUSTNR_TMPLAT_ID)
);
CREATE TABLE TB_QESTNR_INFO (
  QUSTNR_TMPLAT_ID char(20) NOT NULL,  -- 설문템플릿ID
  QESTNR_ID char(20) NOT NULL,  -- QESTNRID
  QUSTNR_SJ VARCHAR2(255) DEFAULT NULL,  -- 설문제목
  QUSTNR_PURPS VARCHAR2(1000) DEFAULT NULL,  -- 설문목적
  QUSTNR_WRITNG_GUIDANCE_CN VARCHAR2(2000) DEFAULT NULL,  -- 설문작성안내내용
  QUSTNR_TRGET VARCHAR2(1000) DEFAULT NULL,  -- 설문대상
  QUSTNR_BGNDE char(20)  DEFAULT NULL,  -- 설문시작일자
  QUSTNR_ENDDE char(20) DEFAULT NULL,  -- 설문종료일자
  FRST_REGIST_PNTTM date DEFAULT NULL,  -- 최초등록시각
  FRST_REGISTER_ID VARCHAR2(20) DEFAULT NULL,  -- 최초등록자ID
  LAST_UPDT_PNTTM date DEFAULT NULL,  -- 최종수정시각
  LAST_UPDUSR_ID VARCHAR2(20) DEFAULT NULL,  -- 최종수정자ID
  PRIMARY KEY (QUSTNR_TMPLAT_ID,QESTNR_ID)
);
CREATE TABLE TB_QUSTNR_QESITM (
  QESTNR_ID char(20) NOT NULL,  -- QESTNRID
  QUSTNR_QESITM_ID char(20) NOT NULL,  -- 설문QESITMID
  QUSTNR_TMPLAT_ID char(20) NOT NULL,  -- 설문템플릿ID
  QESTN_SN number(10,0) DEFAULT NULL,  -- 질문일련번호
  QESTN_TY_CODE char(1) DEFAULT NULL,  -- 질문유형상세코드
  QESTN_CN VARCHAR2(2500) DEFAULT NULL,  -- 질문내용
  MXMM_CHOISE_CO number(5,0) DEFAULT NULL,  -- MXMMCHOISE수
  FRST_REGIST_PNTTM date NOT NULL,  -- 최초등록시각
  FRST_REGISTER_ID VARCHAR2(20) NOT NULL,  -- 최초등록자ID
  LAST_UPDT_PNTTM date NOT NULL,  -- 최종수정시각
  LAST_UPDUSR_ID VARCHAR2(20) NOT NULL,  -- 최종수정자ID
  PRIMARY KEY (QESTNR_ID,QUSTNR_QESITM_ID,QUSTNR_TMPLAT_ID)
);
CREATE TABLE TB_QUSTNR_IEM (
  QUSTNR_TMPLAT_ID char(20) NOT NULL,  -- 설문템플릿ID
  QESTNR_ID char(20) NOT NULL,  -- QESTNRID
  QUSTNR_QESITM_ID char(20) NOT NULL,  -- 설문QESITMID
  QUSTNR_IEM_ID VARCHAR2(20) NOT NULL,  -- 설문항목ID
  IEM_SN number(5,0) DEFAULT NULL,  -- 항목일련번호
  IEM_CN VARCHAR2(1000) DEFAULT NULL,  -- 항목내용
  ETC_ANSWER_AT char(1) DEFAULT NULL,  -- 기타답변여부
  FRST_REGIST_PNTTM date DEFAULT NULL,  -- 최초등록시각
  FRST_REGISTER_ID VARCHAR2(20) DEFAULT NULL,  -- 최초등록자ID
  LAST_UPDT_PNTTM date DEFAULT NULL,  -- 최종수정시각
  LAST_UPDUSR_ID VARCHAR2(20) DEFAULT NULL,  -- 최종수정자ID
  PRIMARY KEY (QUSTNR_TMPLAT_ID,QESTNR_ID,QUSTNR_QESITM_ID,QUSTNR_IEM_ID)
);
CREATE TABLE TB_QUSTNR_RESPOND_INFO (
  QUSTNR_TMPLAT_ID char(20) NOT NULL,  -- 설문템플릿ID
  QESTNR_ID char(20) NOT NULL,  -- QESTNRID
  QUSTNR_RESPOND_ID char(20) NOT NULL,  -- 설문응답ID
  SEXDSTN_CODE char(1) DEFAULT NULL,  -- 성별코드
  OCCP_TY_CODE VARCHAR2(10) DEFAULT NULL,  -- 직업유형상세코드
  RESPOND_NM VARCHAR2(50) DEFAULT NULL,  -- 응답명
  BRTHDY char(20) DEFAULT NULL,  -- 생년월일
  AREA_NO VARCHAR2(4) DEFAULT NULL,  -- 지역번호
  MIDDLE_TELNO VARCHAR2(4) DEFAULT NULL,  -- 전화 중간번호
  END_TELNO VARCHAR2(4) DEFAULT NULL,  -- 전화 끝번호
  FRST_REGIST_PNTTM date DEFAULT NULL,  -- 최초등록시각
  FRST_REGISTER_ID VARCHAR2(20) DEFAULT NULL,  -- 최초등록자ID
  LAST_UPDT_PNTTM date DEFAULT NULL,  -- 최종수정시각
  LAST_UPDUSR_ID VARCHAR2(20) DEFAULT NULL,  -- 최종수정자ID
  PRIMARY KEY (QUSTNR_TMPLAT_ID,QESTNR_ID,QUSTNR_RESPOND_ID)
);
CREATE TABLE TB_QUSTNR_RSPNS_RESULT (
  QUSTNR_RSPNS_RESULT_ID char(20) NOT NULL,  -- 설문응답결과ID
  QESTNR_ID char(20) NOT NULL,  -- QESTNRID
  QUSTNR_QESITM_ID char(20) NOT NULL,  -- 설문QESITMID
  QUSTNR_TMPLAT_ID char(20) NOT NULL,  -- 설문템플릿ID
  RESPOND_ANSWER_CN VARCHAR2(1000) DEFAULT NULL,  -- 응답답변내용
  ETC_ANSWER_CN VARCHAR2(1000) DEFAULT NULL,  -- 기타답변내용
  RESPOND_NM VARCHAR2(50) DEFAULT NULL,  -- 응답명
  FRST_REGIST_PNTTM date DEFAULT NULL,  -- 최초등록시각
  FRST_REGISTER_ID VARCHAR2(20) DEFAULT NULL,  -- 최초등록자ID
  LAST_UPDT_PNTTM date DEFAULT NULL,  -- 최종수정시각
  LAST_UPDUSR_ID VARCHAR2(20) DEFAULT NULL,  -- 최종수정자ID
  QUSTNR_IEM_ID VARCHAR2(20) DEFAULT NULL,  -- 설문항목ID
  PRIMARY KEY (QUSTNR_RSPNS_RESULT_ID,QESTNR_ID,QUSTNR_QESITM_ID,QUSTNR_TMPLAT_ID)
);
CREATE TABLE TB_STPLAT_INFO (
  USE_STPLAT_ID char(20) NOT NULL,  -- 이용약관ID
  USE_STPLAT_NM VARCHAR2(100) DEFAULT NULL,  -- 이용약관명
  USE_STPLAT_CN clob,  -- 이용약관 내용
  INFO_PROVD_AGRE_CN clob,  -- 정보제공 동의 내용
  VER VARCHAR2(20) DEFAULT NULL,  -- 버전
  APLC_DE VARCHAR2(8) DEFAULT NULL,  -- 응용일자
  REPRSNT_AT char(1) DEFAULT 'N',  -- REPRSNT여부
  USE_AT char(1) DEFAULT 'Y',  -- 사용여부(Y/N)
  FRST_REGIST_PNTTM date DEFAULT NULL,  -- 최초등록시각
  FRST_REGISTER_ID VARCHAR2(20) DEFAULT NULL,  -- 최초등록자ID
  LAST_UPDT_PNTTM date DEFAULT NULL,  -- 최종수정시각
  LAST_UPDUSR_ID VARCHAR2(20) DEFAULT NULL,  -- 최종수정자ID
  PRIMARY KEY (USE_STPLAT_ID)
);
CREATE TABLE TB_CTSNN_MANAGE (
  CTSNN_ID char(20) NOT NULL,  -- 경조사ID
  USER_ID VARCHAR2(20) DEFAULT NULL,  -- 사용자아이디
  CTSNN_CODE VARCHAR2(6) DEFAULT NULL,  -- 경조사상세코드
  REQST_DE VARCHAR2(20) DEFAULT NULL,  -- REQST일자
  CTSNN_NM VARCHAR2(100) DEFAULT NULL,  -- 경조사명
  TRGTER_NM VARCHAR2(50) DEFAULT NULL,  -- 대상자명
  BRTHDY VARCHAR2(20) DEFAULT NULL,  -- 생년월일
  OCCRRNC_DE VARCHAR2(20) DEFAULT NULL,  -- 발생일자
  RELATE VARCHAR2(6) DEFAULT NULL,  -- 관련
  RM clob,  -- RM
  SANCTNER_ID VARCHAR2(20) DEFAULT NULL,  -- SANCTNERID
  CONFM_AT char(1) DEFAULT 'N',  -- 승인여부
  SANCTN_DT VARCHAR2(20) DEFAULT NULL,  -- 결재일시
  RETURN_RESN VARCHAR2(2000) DEFAULT NULL,  -- RETURN사유
  INFRML_SANCTN_ID VARCHAR2(20) DEFAULT NULL,  -- INFRML결재ID
  FRST_REGISTER_ID VARCHAR2(20) DEFAULT NULL,  -- 최초등록자ID
  FRST_REGIST_PNTTM date DEFAULT NULL,  -- 최초등록시각
  LAST_UPDUSR_ID VARCHAR2(20) DEFAULT NULL,  -- 최종수정자ID
  LAST_UPDT_PNTTM date DEFAULT NULL,  -- 최종수정시각
  PRIMARY KEY (CTSNN_ID)
);
CREATE TABLE TB_RSS (
  RSS_ID VARCHAR2(20) NOT NULL,  -- RSSID
  TRGET_SVC_NM VARCHAR2(100),  -- 대상서비스명
  TRGET_SVC_TABLE VARCHAR2(100),  -- 대상서비스TABLE
  TRGET_SVC_LIST_CO number(6),  -- 대상서비스목록수
  HDER_TITLE VARCHAR2(200),  -- 헤더제목
  HDER_LINK VARCHAR2(200),  -- 헤더링크
  HDER_DC VARCHAR2(500),  -- 헤더설명
  HDER_TAG VARCHAR2(200),  -- 헤더태그
  HDER_ETC VARCHAR2(200),  -- 헤더기타
  BDT_TITLE VARCHAR2(200),  -- 본문제목
  BDT_LINK VARCHAR2(200),  -- 본문링크
  BDT_DC VARCHAR2(500),  -- 본문설명
  BDT_TAG VARCHAR2(200),  -- 본문태그
  BDT_ETC_TAG VARCHAR2(200),  -- 본문기타태그
  FRST_REGIST_PNTTM date,  -- 최초등록시각
  FRST_REGISTER_ID VARCHAR2(20),  -- 최초등록자ID
  LAST_UPDT_PNTTM date,  -- 최종수정시각
  LAST_UPDUSR_ID VARCHAR2(20),  -- 최종수정자ID
  PRIMARY KEY (RSS_ID)
);
CREATE TABLE TB_NTFC_INFO (
  NTCN_NO number(10) NOT NULL,  -- 알림번호
  NTCN_SJ VARCHAR2(200),  -- 알림제목
  NTCN_CN clob,  -- 알림내용
  NTCN_TM VARCHAR2(20),  -- 알림시각
  BH_NTCN_INTRVL VARCHAR2(100),  -- BH알림INTRVL
  FRST_REGISTER_ID VARCHAR2(20),  -- 최초등록자ID
  FRST_REGIST_PNTTM date,  -- 최초등록시각
  LAST_UPDUSR_ID VARCHAR2(20),  -- 최종수정자ID
  LAST_UPDT_PNTTM date,  -- 최종수정시각
  PRIMARY KEY (NTCN_NO)
);
CREATE TABLE TB_INTNET_SVC (
  INTNET_SVC_ID VARCHAR2(20) NOT NULL,  -- 인터넷서비스ID
  INTNET_SVC_NM VARCHAR2(200),  -- 인터넷서비스명
  INTNET_SVC_DC clob,  -- 인터넷서비스설명
  REFLCT_AT VARCHAR2(1) DEFAULT 'N',  -- REFLCT여부
  FRST_REGISTER_ID VARCHAR2(20),  -- 최초등록자ID
  FRST_REGIST_PNTTM date,  -- 최초등록시각
  LAST_UPDUSR_ID VARCHAR2(20),  -- 최종수정자ID
  LAST_UPDT_PNTTM date,  -- 최종수정시각
  PRIMARY KEY (INTNET_SVC_ID)
);
CREATE TABLE TB_RECOMEND_SITE_INFO (
  RECOMEND_SITE_ID VARCHAR2(20) NOT NULL,  -- 추천사이트ID
  RECOMEND_SITE_URL VARCHAR2(300),  -- 추천사이트URL
  RECOMEND_SITE_NM VARCHAR2(200),  -- 추천사이트명
  RECOMEND_SITE_DC clob,  -- 추천사이트설명
  RECOMEND_RESN_CN clob,  -- 추천사유내용
  RECOMEND_CONFM_AT VARCHAR2(1) DEFAULT 'N',  -- 추천승인여부
  CONFM_DE VARCHAR2(20),  -- 승인일자
  FRST_REGIST_PNTTM date,  -- 최초등록시각
  FRST_REGISTER_ID VARCHAR2(20),  -- 최초등록자ID
  LAST_UPDT_PNTTM date,  -- 최종수정시각
  LAST_UPDUSR_ID VARCHAR2(20),  -- 최종수정자ID
  PRIMARY KEY (RECOMEND_SITE_ID)
);
CREATE TABLE TB_ROUGHMAP (
  ROUGHMAP_ID VARCHAR2(20) NOT NULL,  -- 약도ID
  ROUGHMAPSJ VARCHAR2(200),  -- ROUGHMAPSJ
  ROUGHMAPADDRESS VARCHAR2(300),  -- ROUGHMAPADDRESS
  LA VARCHAR2(30),  -- 위도
  LO VARCHAR2(30),  -- 경도
  MARKERLA VARCHAR2(30),  -- MARKERLA
  MARKERLO VARCHAR2(30),  -- MARKERLO
  INFOWINDOW clob,  -- 말풍선
  ZOOMLEVEL VARCHAR2(5),  -- ZOOMLEVEL
  FRST_REGISTER_ID VARCHAR2(20),  -- 최초등록자ID
  FRST_REGIST_PNTTM date,  -- 최초등록시각
  LAST_UPDUSR_ID VARCHAR2(20),  -- 최종수정자ID
  LAST_UPDT_PNTTM date,  -- 최종수정시각
  PRIMARY KEY (ROUGHMAP_ID)
);
CREATE TABLE TB_UNITY_LINK (
  UNITY_LINK_ID VARCHAR2(20) NOT NULL,  -- 통합링크ID
  UNITY_LINK_SE_CODE VARCHAR2(20),  -- 통합링크구분상세코드
  UNITY_LINK_NM VARCHAR2(200),  -- 통합링크명
  UNITY_LINK_URL VARCHAR2(300),  -- 통합링크URL
  UNITY_LINK_DC clob,  -- 통합링크설명
  FRST_REGIST_PNTTM date,  -- 최초등록시각
  FRST_REGISTER_ID VARCHAR2(20),  -- 최초등록자ID
  LAST_UPDT_PNTTM date,  -- 최종수정시각
  LAST_UPDUSR_ID VARCHAR2(20),  -- 최종수정자ID
  PRIMARY KEY (UNITY_LINK_ID)
);
CREATE TABLE TB_SITE_LIST (
  SITE_ID VARCHAR2(20) NOT NULL,  -- 사이트ID
  SITE_URL VARCHAR2(300),  -- 사이트URL
  SITE_NM VARCHAR2(200),  -- 사이트명
  SITE_DC clob,  -- 사이트설명
  SITE_THEMA_CL_CODE VARCHAR2(20),  -- 사이트THEMACL상세코드
  ACTVTY_AT VARCHAR2(1) DEFAULT 'Y',  -- 활성여부
  USE_AT VARCHAR2(1) DEFAULT 'Y',  -- 사용여부(Y/N)
  FRST_REGIST_PNTTM date,  -- 최초등록시각
  FRST_REGISTER_ID VARCHAR2(20),  -- 최초등록자ID
  LAST_UPDT_PNTTM date,  -- 최종수정시각
  LAST_UPDUSR_ID VARCHAR2(20),  -- 최종수정자ID
  PRIMARY KEY (SITE_ID)
);
CREATE TABLE TB_POPUP_MANAGE (
  POPUP_ID VARCHAR2(20) NOT NULL,  -- 팝업ID
  POPUP_SJ_NM VARCHAR2(200),  -- 팝업제목명
  FILE_URL VARCHAR2(300),  -- 파일URL
  POPUP_VRTICL_LC VARCHAR2(10),  -- 팝업세로위치
  POPUP_WIDTH_LC VARCHAR2(10),  -- 팝업너비위치
  POPUP_VRTICL_SIZE VARCHAR2(10),  -- 팝업세로크기
  POPUP_WIDTH_SIZE VARCHAR2(10),  -- 팝업너비크기
  NTCE_BGNDE VARCHAR2(20),  -- 공지 시작일시
  NTCE_ENDDE VARCHAR2(20),  -- 공지 종료일시
  STOPVEW_SETUP_AT VARCHAR2(1) DEFAULT 'N',  -- STOPVEW설정여부
  NTCE_AT VARCHAR2(1) DEFAULT 'Y',  -- 게시여부
  FRST_REGIST_PNTTM date,  -- 최초등록시각
  FRST_REGISTER_ID VARCHAR2(20),  -- 최초등록자ID
  LAST_UPDT_PNTTM date,  -- 최종수정시각
  LAST_UPDUSR_ID VARCHAR2(20),  -- 최종수정자ID
  PRIMARY KEY (POPUP_ID)
);
CREATE TABLE TB_WIKI_BKMK (
  WIKI_BKMK_ID VARCHAR2(20) NOT NULL,  -- 위키북마크ID
  USER_ID VARCHAR2(20),  -- 사용자아이디
  WIKI_BKMK_NM VARCHAR2(200),  -- 위키북마크명
  FRST_REGIST_PNTTM date,  -- 최초등록시각
  FRST_REGISTER_ID VARCHAR2(20),  -- 최초등록자ID
  LAST_UPDT_PNTTM date,  -- 최종수정시각
  LAST_UPDUSR_ID VARCHAR2(20),  -- 최종수정자ID
  PRIMARY KEY (WIKI_BKMK_ID)
);
CREATE TABLE TB_EVENT_MANAGE (
  EVENT_ID VARCHAR2(20) NOT NULL,  -- 행사ID
  EVENT_SE VARCHAR2(20),  -- 행사구분
  EVENT_NM VARCHAR2(200),  -- 행사명
  EVENT_PURPS clob,  -- 행사목적
  EVENT_BGNDE VARCHAR2(20),  -- 행사시작일자
  EVENT_ENDDE VARCHAR2(20),  -- 행사종료일자
  EVENT_AUSPC_INSTT_NM VARCHAR2(100),  -- 행사AUSPC기관명
  EVENT_MNGT_INSTT_NM VARCHAR2(100),  -- 행사관리기관명
  EVENT_PLACE VARCHAR2(200),  -- 행사장소
  EVENT_CN clob,  -- 행사내용
  CT_OCCRRNC_AT VARCHAR2(1) DEFAULT 'N',  -- 법원발생여부
  PARTCPT_CT VARCHAR2(100),  -- PARTCPT법원
  PSNCPA VARCHAR2(100),  -- PSNCPA
  REFRN_URL VARCHAR2(300),  -- REFRNURL
  RCEPT_BGNDE VARCHAR2(20),  -- RCEPT시작일자
  RCEPT_ENDDE VARCHAR2(20),  -- RCEPT종료일자
  FRST_REGISTER_ID VARCHAR2(20),  -- 최초등록자ID
  FRST_REGIST_PNTTM date,  -- 최초등록시각
  LAST_UPDUSR_ID VARCHAR2(20),  -- 최종수정자ID
  LAST_UPDT_PNTTM date,  -- 최종수정시각
  PRIMARY KEY (EVENT_ID)
);
CREATE TABLE TB_RWARD_MANAGE (
  RWARD_ID VARCHAR2(20) NOT NULL,  -- 포상ID
  RWARDWNR_ID VARCHAR2(20),  -- RWARDWNRID
  RWARD_CODE VARCHAR2(20),  -- 포상상세코드
  RWARD_DE VARCHAR2(20),  -- 포상일자
  RWARD_NM VARCHAR2(200),  -- 포상명
  PBLEN_CN clob,  -- PBLEN내용
  SANCTNER_ID VARCHAR2(20),  -- SANCTNERID
  CONFM_AT VARCHAR2(1) DEFAULT 'N',  -- 승인여부
  SANCTN_DT VARCHAR2(20),  -- 결재일시
  RETURN_RESN clob,  -- RETURN사유
  ATCH_FILE_ID VARCHAR2(20),  -- 첨부파일 묶음ID
  INFRML_SANCTN_ID VARCHAR2(20),  -- INFRML결재ID
  FRST_REGISTER_ID VARCHAR2(20),  -- 최초등록자ID
  FRST_REGIST_PNTTM date,  -- 최초등록시각
  LAST_UPDUSR_ID VARCHAR2(20),  -- 최종수정자ID
  LAST_UPDT_PNTTM date,  -- 최종수정시각
  PRIMARY KEY (RWARD_ID)
);
CREATE TABLE TB_NEWS_INFO (
  NEWS_ID VARCHAR2(20) NOT NULL,  -- 뉴스ID
  NEWS_SJ VARCHAR2(200),  -- 뉴스제목
  NEWS_CN clob,  -- 뉴스내용
  NEWS_ORIGIN VARCHAR2(200),  -- 뉴스ORIGIN
  NTCE_DE VARCHAR2(20),  -- 게시일자
  ATCH_FILE_ID VARCHAR2(20),  -- 첨부파일 묶음ID
  FRST_REGISTER_ID VARCHAR2(20),  -- 최초등록자ID
  FRST_REGIST_PNTTM date,  -- 최초등록시각
  LAST_UPDUSR_ID VARCHAR2(20),  -- 최종수정자ID
  LAST_UPDT_PNTTM date,  -- 최종수정시각
  PRIMARY KEY (NEWS_ID)
);
CREATE TABLE TB_MAIN_IMAGE (
  IMAGE_ID VARCHAR2(20) NOT NULL,  -- 이미지ID
  IMAGE_NM VARCHAR2(200),  -- 이미지명
  IMAGE VARCHAR2(300),  -- 이미지
  IMAGE_FILE VARCHAR2(300),  -- 이미지파일
  IMAGE_DC clob,  -- 이미지설명
  REFLCT_AT VARCHAR2(1) DEFAULT 'N',  -- REFLCT여부
  FRST_REGISTER_ID VARCHAR2(20),  -- 최초등록자ID
  FRST_REGIST_PNTTM date,  -- 최초등록시각
  LAST_UPDUSR_ID VARCHAR2(20),  -- 최종수정자ID
  LAST_UPDT_PNTTM date,  -- 최종수정시각
  PRIMARY KEY (IMAGE_ID)
);
CREATE TABLE TB_LOGIN_SCRIN_IMAGE (
  IMAGE_ID VARCHAR2(20) NOT NULL,  -- 이미지ID
  IMAGE_NM VARCHAR2(200),  -- 이미지명
  IMAGE VARCHAR2(300),  -- 이미지
  IMAGE_FILE VARCHAR2(300),  -- 이미지파일
  IMAGE_DC clob,  -- 이미지설명
  REFLCT_AT VARCHAR2(1) DEFAULT 'N',  -- REFLCT여부
  FRST_REGISTER_ID VARCHAR2(20),  -- 최초등록자ID
  FRST_REGIST_PNTTM date,  -- 최초등록시각
  LAST_UPDUSR_ID VARCHAR2(20),  -- 최종수정자ID
  LAST_UPDT_PNTTM date,  -- 최종수정시각
  PRIMARY KEY (IMAGE_ID)
);
CREATE TABLE TB_MTG_PLACE_MANAGE (
  MTGRUM_ID VARCHAR2(20) NOT NULL,  -- 회의실ID
  MTGRUM_NM VARCHAR2(200),  -- 회의실명
  OPN_BEGIN_TM VARCHAR2(10),  -- 개방시작시각
  OPN_END_TM VARCHAR2(10),  -- 개방종료시각
  ACEPTNC_POSBL_NMPR number(6),  -- 수용가능인원
  LC_SE VARCHAR2(20),  -- 위치구분
  LC_DETAIL VARCHAR2(300),  -- 위치DETAIL
  ATCH_FILE_ID VARCHAR2(20),  -- 첨부파일 묶음ID
  FRST_REGISTER_ID VARCHAR2(20),  -- 최초등록자ID
  FRST_REGIST_PNTTM date,  -- 최초등록시각
  LAST_UPDUSR_ID VARCHAR2(20),  -- 최종수정자ID
  LAST_UPDT_PNTTM date,  -- 최종수정시각
  PRIMARY KEY (MTGRUM_ID)
);
CREATE TABLE TB_WORD_DICARY_INFO (
  WORD_ID VARCHAR2(20) NOT NULL,  -- 단어ID
  WORD_NM VARCHAR2(200),  -- 단어명
  ENG_NM VARCHAR2(200),  -- 영문명
  WORD_DC clob,  -- 단어설명
  SYNONM VARCHAR2(300),  -- SYNONM
  FRST_REGISTER_ID VARCHAR2(20),  -- 최초등록자ID
  FRST_REGIST_PNTTM date,  -- 최초등록시각
  LAST_UPDUSR_ID VARCHAR2(20),  -- 최종수정자ID
  LAST_UPDT_PNTTM date,  -- 최종수정시각
  PRIMARY KEY (WORD_ID)
);
CREATE TABLE TB_INDVDL_PGE_CNTNTS (
  CNTNTS_ID VARCHAR2(20) NOT NULL,  -- 콘텐츠ID
  CNTNTS_NM VARCHAR2(200),  -- 콘텐츠명
  CNTC_URL VARCHAR2(300),  -- 접촉URL
  CNTNTS_USE_AT VARCHAR2(1) DEFAULT 'Y',  -- 콘텐츠사용여부
  CNTNTS_LINK_URL VARCHAR2(300),  -- 콘텐츠링크URL
  CNTNTS_DC clob,  -- 콘텐츠설명
  FRST_REGISTER_ID VARCHAR2(20),  -- 최초등록자ID
  FRST_REGIST_PNTTM date,  -- 최초등록시각
  LAST_UPDUSR_ID VARCHAR2(20),  -- 최종수정자ID
  LAST_UPDT_PNTTM date,  -- 최종수정시각
  PRIMARY KEY (CNTNTS_ID)
);
CREATE TABLE TB_HPCM_INFO (
  HPCM_ID VARCHAR2(20) NOT NULL,  -- 도움말ID
  HPCM_SE_CODE VARCHAR2(20),  -- 도움말구분상세코드
  HPCM_DFN VARCHAR2(300),  -- 도움말정의
  HPCM_DC clob,  -- 도움말설명
  FRST_REGISTER_ID VARCHAR2(20),  -- 최초등록자ID
  FRST_REGIST_PNTTM date,  -- 최초등록시각
  LAST_UPDUSR_ID VARCHAR2(20),  -- 최종수정자ID
  LAST_UPDT_PNTTM date,  -- 최종수정시각
  PRIMARY KEY (HPCM_ID)
);
CREATE TABLE TB_COMMUTE (
  WRKTM_ID VARCHAR2(20) NOT NULL,  -- WRKTMID
  EMPLYR_ID VARCHAR2(20),  -- 사용자ID
  ORGNZT_ID VARCHAR2(20),  -- 조직ID
  WRKT_DT VARCHAR2(20),  -- WRKT일시
  WRK_START_TIME VARCHAR2(10),  -- 작업START시간
  WRK_END_TIME VARCHAR2(10),  -- 작업종료시간
  WRK_HOURS VARCHAR2(10),  -- 작업시간
  OVTMWRK_HOURS VARCHAR2(10),  -- OVTMWRK시간
  WRK_START_STATUS VARCHAR2(1),  -- 작업STARTSTATUS
  WRK_END_STATUS VARCHAR2(1),  -- 작업종료STATUS
  FRST_REGISTER_ID VARCHAR2(20),  -- 최초등록자ID
  FRST_REGIST_PNTTM date,  -- 최초등록시각
  LAST_UPDUSR_ID VARCHAR2(20),  -- 최종수정자ID
  LAST_UPDT_PNTTM date,  -- 최종수정시각
  PRIMARY KEY (WRKTM_ID)
);
CREATE TABLE TB_ADMINISTRATION_WORD (
  ADMINIST_WORD_ID VARCHAR2(20) NOT NULL,  -- 행정단어ID
  ADMINIST_WORD_NM VARCHAR2(200),  -- 행정단어명
  ADMINIST_WORD_ENG_NM VARCHAR2(200),  -- 행정단어영문명
  ADMINIST_WORD_ABRV_NM VARCHAR2(100),  -- 행정단어약어명
  THEMA_RELM VARCHAR2(100),  -- THEMARELM
  WORD_SE VARCHAR2(20),  -- 단어구분
  RELATE_STD_WORD VARCHAR2(200),  -- 관련표준단어
  ADMINIST_WORD_DFN clob,  -- 행정단어정의
  ADMINIST_WORD_DC clob,  -- 행정단어설명
  FRST_REGISTER_ID VARCHAR2(20),  -- 최초등록자ID
  FRST_REGIST_PNTTM date,  -- 최초등록시각
  LAST_UPDUSR_ID VARCHAR2(20),  -- 최종수정자ID
  LAST_UPDT_PNTTM date,  -- 최종수정시각
  PRIMARY KEY (ADMINIST_WORD_ID)
);
CREATE TABLE TB_NOTE (
  NOTE_ID VARCHAR2(20) NOT NULL,  -- 쪽지ID
  NOTE_SJ VARCHAR2(200),  -- 쪽지제목
  NOTE_CN clob,  -- 쪽지내용
  ATCH_FILE_ID VARCHAR2(20),  -- 첨부파일 묶음ID
  FRST_REGISTER_ID VARCHAR2(20),  -- 최초등록자ID
  FRST_REGIST_PNTTM date,  -- 최초등록시각
  LAST_UPDUSR_ID VARCHAR2(20),  -- 최종수정자ID
  LAST_UPDT_PNTTM date,  -- 최종수정시각
  PRIMARY KEY (NOTE_ID)
);
CREATE TABLE TB_NOTE_TRNSMIT (
  NOTE_TRNSMIT_ID VARCHAR2(20) NOT NULL,  -- 쪽지송신ID
  NOTE_ID VARCHAR2(20),  -- 쪽지ID
  TRNSMITER_ID VARCHAR2(20),  -- TRNSMITERID
  DELETE_AT VARCHAR2(1) DEFAULT 'N',  -- 삭제여부
  FRST_REGISTER_ID VARCHAR2(20),  -- 최초등록자ID
  FRST_REGIST_PNTTM date,  -- 최초등록시각
  LAST_UPDUSR_ID VARCHAR2(20),  -- 최종수정자ID
  LAST_UPDT_PNTTM date,  -- 최종수정시각
  PRIMARY KEY (NOTE_TRNSMIT_ID)
);
CREATE TABLE TB_NOTE_RECPTN (
  NOTE_RECPTN_ID VARCHAR2(20) NOT NULL,  -- 쪽지수신ID
  NOTE_ID VARCHAR2(20),  -- 쪽지ID
  NOTE_TRNSMIT_ID VARCHAR2(20),  -- 쪽지송신ID
  RCVER_ID VARCHAR2(20),  -- 수화자ID
  READNG_AT VARCHAR2(1) DEFAULT 'N',  -- READNG여부
  OPEN_YN VARCHAR2(1) DEFAULT 'N',  -- 개봉여부
  RECPTN_SE VARCHAR2(20) DEFAULT '01',  -- 수신구분
  DELETE_AT VARCHAR2(1) DEFAULT 'N',  -- 삭제여부
  FRST_REGISTER_ID VARCHAR2(20),  -- 최초등록자ID
  FRST_REGIST_PNTTM date,  -- 최초등록시각
  LAST_UPDUSR_ID VARCHAR2(20),  -- 최종수정자ID
  LAST_UPDT_PNTTM date,  -- 최종수정시각
  PRIMARY KEY (NOTE_RECPTN_ID)
);
CREATE TABLE TB_INDVDL_YRYC_MANAGE (
  OCCRRNC_YEAR VARCHAR2(4) NOT NULL,  -- 발생연도
  USER_ID VARCHAR2(20) NOT NULL,  -- 사용자아이디
  YRYC_OCCRRNC_CO number(5,1),  -- 연차발생수
  USE_YRYC_CO number(5,1),  -- 사용연차수
  REMNDR_YRYC_CO number(5,1),  -- REMNDR연차수
  FRST_REGISTER_ID VARCHAR2(20),  -- 최초등록자ID
  FRST_REGIST_PNTTM date,  -- 최초등록시각
  LAST_UPDUSR_ID VARCHAR2(20),  -- 최종수정자ID
  LAST_UPDT_PNTTM date,  -- 최종수정시각
  PRIMARY KEY (OCCRRNC_YEAR, USER_ID)
);
CREATE TABLE TB_ANNVRSRY_MANAGE (
  ANNVRSRY_ID VARCHAR2(20) NOT NULL,  -- 기념일ID
  USER_ID VARCHAR2(20),  -- 사용자아이디
  ANNVRSRY_SE VARCHAR2(20),  -- 기념일구분
  ANNVRSRY_NM VARCHAR2(200),  -- 기념일명
  ANNVRSRY VARCHAR2(20),  -- 기념일
  CLDR_SE VARCHAR2(20),  -- 달력구분
  ANNVRSRY_NTCN_SETUP VARCHAR2(20),  -- 기념일알림설정
  ANNVRSRY_NTCN_BGNDE VARCHAR2(20),  -- 기념일알림시작일자
  MEMO clob,  -- 메모
  REPTIT_AT VARCHAR2(1) DEFAULT 'N',  -- REPTIT여부
  FRST_REGISTER_ID VARCHAR2(20),  -- 최초등록자ID
  FRST_REGIST_PNTTM date,  -- 최초등록시각
  LAST_UPDUSR_ID VARCHAR2(20),  -- 최종수정자ID
  LAST_UPDT_PNTTM date,  -- 최종수정시각
  PRIMARY KEY (ANNVRSRY_ID)
);
CREATE TABLE TB_MTG_INFO (
  MTG_ID VARCHAR2(20) NOT NULL,  -- 회의ID
  MTG_NM VARCHAR2(200),  -- 회의명
  MTG_MTR_CN clob,  -- 회의원동기내용
  MTG_SN VARCHAR2(20),  -- 회의일련번호
  MTG_CO VARCHAR2(20),  -- 회의수
  MTG_DE VARCHAR2(20),  -- 회의일자
  MTG_PLACE VARCHAR2(200),  -- 회의장소
  MTG_BEGIN_TM VARCHAR2(10),  -- 회의시작시각
  MTG_END_TM VARCHAR2(10),  -- 회의종료시각
  CLSDR_MTG_AT VARCHAR2(1) DEFAULT 'N',  -- CLSDR회의여부
  READNG_BGNDE VARCHAR2(20),  -- READNG시작일자
  READNG_AT VARCHAR2(1) DEFAULT 'N',  -- READNG여부
  MTG_RESULT_CN clob,  -- 회의결과내용
  MTG_RESULT_ENNC VARCHAR2(200),  -- 회의결과암호
  ETC_MATTER clob,  -- 기타MATTER
  MNGT_DEPT_ID VARCHAR2(20),  -- 관리부서ID
  MNAER_ID VARCHAR2(20),  -- 담당자ID
  MNAER_DEPT_ID VARCHAR2(20),  -- 담당자부서ID
  MTG_AT VARCHAR2(1) DEFAULT 'N',  -- 회의여부
  NONATDRN_CO number(6),  -- NONATDRN수
  ATDRN_CO number(6),  -- ATDRN수
  FRST_REGISTER_ID VARCHAR2(20),  -- 최초등록자ID
  FRST_REGIST_PNTTM date,  -- 최초등록시각
  LAST_UPDUSR_ID VARCHAR2(20),  -- 최종수정자ID
  LAST_UPDT_PNTTM date,  -- 최종수정시각
  PRIMARY KEY (MTG_ID)
);
CREATE TABLE TB_RECENT_SRCHWRD_MANAGE (
  SRCHWRD_MANAGE_ID VARCHAR2(20) NOT NULL,  -- 검색어MANAGEID
  SRCHWRD_MANAGE_NM VARCHAR2(200),  -- 검색어MANAGE명
  SRCHWRD_CONECT_URL VARCHAR2(300),  -- 검색어접속URL
  USER_SEARCH_AT VARCHAR2(1) DEFAULT 'Y',  -- 사용자SEARCH여부
  FRST_REGISTER_ID VARCHAR2(20),  -- 최초등록자ID
  FRST_REGIST_PNTTM date,  -- 최초등록시각
  LAST_UPDUSR_ID VARCHAR2(20),  -- 최종수정자ID
  LAST_UPDT_PNTTM date,  -- 최종수정시각
  PRIMARY KEY (SRCHWRD_MANAGE_ID)
);
CREATE TABLE TB_RECENT_SRCHWRD (
  SRCHWRD_ID VARCHAR2(20) NOT NULL,  -- 검색어ID
  SRCHWRD_MANAGE_ID VARCHAR2(20),  -- 검색어MANAGEID
  SRCHWRD_NM VARCHAR2(200),  -- 검색어명
  SRCHWRD_CO number(10) DEFAULT 0,  -- 검색어수
  FRST_REGISTER_ID VARCHAR2(20),  -- 최초등록자ID
  FRST_REGIST_PNTTM date,  -- 최초등록시각
  LAST_UPDUSR_ID VARCHAR2(20),  -- 최종수정자ID
  LAST_UPDT_PNTTM date,  -- 최종수정시각
  PRIMARY KEY (SRCHWRD_ID)
);
CREATE TABLE TB_EVENT_INFO (
  EVENT_ID VARCHAR2(20) NOT NULL,  -- 행사ID
  BSNS_YEAR VARCHAR2(4),  -- 용무연도
  BSNS_CODE VARCHAR2(20),  -- 용무코드
  EVENT_SVC_BGNDE VARCHAR2(20),  -- 행사서비스시작일자
  EVENT_SVC_ENDDE VARCHAR2(20),  -- 행사서비스종료일자
  SVC_USE_NMPR_CO number(8),  -- 봉사사용국가유공자수
  CHARGER_NM VARCHAR2(50),  -- 담당자명
  EVENT_CN clob,  -- 행사내용
  EVENT_TY_CODE VARCHAR2(20),  -- 행사유형상세코드
  PRPARETG_CN clob,  -- PRPARETG내용
  EVENT_CONFM_AT VARCHAR2(1) DEFAULT 'N',  -- 행사승인여부
  EVENT_CONFM_DE VARCHAR2(20),  -- 행사승인일자
  FRST_REGISTER_ID VARCHAR2(20),  -- 최초등록자ID
  FRST_REGIST_PNTTM date,  -- 최초등록시각
  LAST_UPDUSR_ID VARCHAR2(20),  -- 최종수정자ID
  LAST_UPDT_PNTTM date,  -- 최종수정시각
  PRIMARY KEY (EVENT_ID)
);
CREATE TABLE TB_VCATN_MANAGE (
  APPLCNT_ID VARCHAR2(20) NOT NULL,  -- APPLCNTID
  VCATN_SE VARCHAR2(20) NOT NULL,  -- VCATN구분
  OCCRRNC_YEAR VARCHAR2(4),  -- 발생연도
  BGNDE VARCHAR2(20) NOT NULL,  -- 시작일자
  ENDDE VARCHAR2(20) NOT NULL,  -- 종료일자
  REQST_DE VARCHAR2(20),  -- REQST일자
  VCATN_RESN VARCHAR2(500),  -- VCATN사유
  NOON_SE VARCHAR2(20),  -- NOON구분
  SANCTNER_ID VARCHAR2(20),  -- SANCTNERID
  CONFM_AT VARCHAR2(1) DEFAULT 'N',  -- 승인여부
  SANCTN_DT VARCHAR2(20),  -- 결재일시
  RETURN_RESN VARCHAR2(500),  -- RETURN사유
  INFRML_SANCTN_ID VARCHAR2(20),  -- INFRML결재ID
  FRST_REGISTER_ID VARCHAR2(20),  -- 최초등록자ID
  FRST_REGIST_PNTTM date,  -- 최초등록시각
  LAST_UPDUSR_ID VARCHAR2(20),  -- 최종수정자ID
  LAST_UPDT_PNTTM date,  -- 최종수정시각
  PRIMARY KEY (APPLCNT_ID, VCATN_SE, BGNDE, ENDDE)
);
CREATE TABLE TB_BNDT_MANAGE (
  BNDT_ID VARCHAR2(20) NOT NULL,  -- 당직ID
  BNDT_DE VARCHAR2(20) NOT NULL,  -- 당직일자
  RM VARCHAR2(2000),  -- RM
  FRST_REGISTER_ID VARCHAR2(20),  -- 최초등록자ID
  FRST_REGIST_PNTTM date,  -- 최초등록시각
  LAST_UPDUSR_ID VARCHAR2(20),  -- 최종수정자ID
  LAST_UPDT_PNTTM date,  -- 최종수정시각
  PRIMARY KEY (BNDT_ID, BNDT_DE)
);
CREATE TABLE TB_BNDT_DIARY (
  BNDT_ID VARCHAR2(20) NOT NULL,  -- 당직ID
  BNDT_DE VARCHAR2(20) NOT NULL,  -- 당직일자
  RM VARCHAR2(2000),  -- RM
  FRST_REGISTER_ID VARCHAR2(20),  -- 최초등록자ID
  FRST_REGIST_PNTTM date,  -- 최초등록시각
  LAST_UPDUSR_ID VARCHAR2(20),  -- 최종수정자ID
  LAST_UPDT_PNTTM date,  -- 최종수정시각
  PRIMARY KEY (BNDT_ID, BNDT_DE)
);
CREATE TABLE TB_BNDT_CECK_MANAGE (
  BNDT_ID VARCHAR2(20) NOT NULL,  -- 당직ID
  BNDT_DE VARCHAR2(20) NOT NULL,  -- 당직일자
  RM VARCHAR2(2000),  -- RM
  FRST_REGISTER_ID VARCHAR2(20),  -- 최초등록자ID
  FRST_REGIST_PNTTM date,  -- 최초등록시각
  LAST_UPDUSR_ID VARCHAR2(20),  -- 최종수정자ID
  LAST_UPDT_PNTTM date,  -- 최종수정시각
  PRIMARY KEY (BNDT_ID, BNDT_DE)
);
CREATE TABLE TB_ONLINE_POLL_MANAGE (
  POLL_ID VARCHAR2(20) NOT NULL,  -- 투표ID
  POLL_NM VARCHAR2(200),  -- 투표명
  POLL_BGNDE VARCHAR2(20),  -- 투표시작일자
  POLL_ENDDE VARCHAR2(20),  -- 투표종료일자
  POLL_KND VARCHAR2(20),  -- 투표종류
  POLL_DSUSE_ENNC VARCHAR2(1) DEFAULT 'N',  -- 투표폐기암호
  POLL_ATMC_DSUSE_ENNC VARCHAR2(1) DEFAULT 'N',  -- 투표ATMC폐기암호
  QESITM_CN clob,  -- QESITM내용
  FRST_REGISTER_ID VARCHAR2(20),  -- 최초등록자ID
  FRST_REGIST_PNTTM date,  -- 최초등록시각
  LAST_UPDUSR_ID VARCHAR2(20),  -- 최종수정자ID
  LAST_UPDT_PNTTM date,  -- 최종수정시각
  PRIMARY KEY (POLL_ID)
);
CREATE TABLE TB_ONLINE_POLL_IEM (
  POLL_ID VARCHAR2(20) NOT NULL,  -- 투표ID
  POLL_IEM_ID VARCHAR2(20) NOT NULL,  -- 투표항목ID
  POLL_IEM_NM VARCHAR2(200),  -- 투표항목명
  FRST_REGISTER_ID VARCHAR2(20),  -- 최초등록자ID
  FRST_REGIST_PNTTM date,  -- 최초등록시각
  LAST_UPDUSR_ID VARCHAR2(20),  -- 최종수정자ID
  LAST_UPDT_PNTTM date,  -- 최종수정시각
  PRIMARY KEY (POLL_ID, POLL_IEM_ID)
);
CREATE TABLE TB_ONLINE_MANUAL (
  ONLINE_MNL_ID VARCHAR2(20) NOT NULL,  -- 온라인매뉴얼ID
  ONLINE_MNL_NM VARCHAR2(200),  -- 온라인매뉴얼명
  ONLINE_MNL_SE_CODE VARCHAR2(20),  -- 온라인매뉴얼구분상세코드
  ONLINE_MNL_DFN VARCHAR2(500),  -- 온라인매뉴얼정의
  ONLINE_MNL_DC clob,  -- 온라인매뉴얼설명
  FRST_REGISTER_ID VARCHAR2(20),  -- 최초등록자ID
  FRST_REGIST_PNTTM date,  -- 최초등록시각
  LAST_UPDUSR_ID VARCHAR2(20),  -- 최종수정자ID
  LAST_UPDT_PNTTM date,  -- 최종수정시각
  PRIMARY KEY (ONLINE_MNL_ID)
);
CREATE TABLE TB_CPYRHT_INFO (
  CPYRHT_ID VARCHAR2(20) NOT NULL,  -- 저작권ID
  CPYRHT_PRTC_POLICY_CN clob,  -- 저작권보호정책내용
  FRST_REGISTER_ID VARCHAR2(20),  -- 최초등록자ID
  FRST_REGIST_PNTTM date,  -- 최초등록시각
  LAST_UPDUSR_ID VARCHAR2(20),  -- 최종수정자ID
  LAST_UPDT_PNTTM date,  -- 최종수정시각
  PRIMARY KEY (CPYRHT_ID)
);
CREATE TABLE TB_CNSLT_LIST (
  CNSLT_ID VARCHAR2(20) NOT NULL,  -- 컨설팅ID
  CNSLT_SJ VARCHAR2(200),  -- 컨설팅제목
  CNSLT_CN clob,  -- 컨설팅내용
  OTHBC_AT VARCHAR2(1) DEFAULT 'Y',  -- 외부공개여부
  EMAIL_ADRES VARCHAR2(100),  -- 이메일
  EMAIL_ANSWER_AT VARCHAR2(1) DEFAULT 'N',  -- 이메일답변여부
  AREA_NO VARCHAR2(10),  -- 지역번호
  FRST_REGISTER_ID VARCHAR2(20),  -- 최초등록자ID
  FRST_REGIST_PNTTM date,  -- 최초등록시각
  LAST_UPDUSR_ID VARCHAR2(20),  -- 최종수정자ID
  LAST_UPDT_PNTTM date,  -- 최종수정시각
  PRIMARY KEY (CNSLT_ID)
);
CREATE TABLE TB_BATCH_OPERT (
  BATCH_OPERT_ID VARCHAR2(20) NOT NULL,  -- 배치작업ID
  BATCH_OPERT_NM VARCHAR2(100),  -- 배치작업명
  BATCH_PROGRM VARCHAR2(500),  -- 배치프로그램
  PARAMTR VARCHAR2(500),  -- PARAMTR
  USE_AT VARCHAR2(1) DEFAULT 'Y',  -- 사용여부(Y/N)
  FRST_REGISTER_ID VARCHAR2(20),  -- 최초등록자ID
  FRST_REGIST_PNTTM date,  -- 최초등록시각
  LAST_UPDUSR_ID VARCHAR2(20),  -- 최종수정자ID
  LAST_UPDT_PNTTM date,  -- 최종수정시각
  PRIMARY KEY (BATCH_OPERT_ID)
);
CREATE TABLE TB_BATCH_SCHDUL (
  BATCH_SCHDUL_ID VARCHAR2(20) NOT NULL,  -- 배치일정ID
  BATCH_OPERT_ID VARCHAR2(20),  -- 배치작업ID
  EXECUT_CYCLE VARCHAR2(20),  -- 실행주기
  EXECUT_SCHDUL_DE VARCHAR2(20),  -- 실행일정일자
  EXECUT_SCHDUL_HOUR VARCHAR2(2),  -- 실행일정HOUR
  EXECUT_SCHDUL_MNT VARCHAR2(2),  -- 실행일정MNT
  EXECUT_SCHDUL_SECND VARCHAR2(2),  -- 실행일정SECND
  FRST_REGISTER_ID VARCHAR2(20),  -- 최초등록자ID
  FRST_REGIST_PNTTM date,  -- 최초등록시각
  LAST_UPDUSR_ID VARCHAR2(20),  -- 최종수정자ID
  LAST_UPDT_PNTTM date,  -- 최종수정시각
  PRIMARY KEY (BATCH_SCHDUL_ID)
);
CREATE TABLE TB_BATCH_RESULT (
  BATCH_RESULT_ID VARCHAR2(20) NOT NULL,  -- 배치결과ID
  BATCH_SCHDUL_ID VARCHAR2(20),  -- 배치일정ID
  BATCH_OPERT_ID VARCHAR2(20),  -- 배치작업ID
  PARAMTR VARCHAR2(500),  -- PARAMTR
  STTUS VARCHAR2(1),  -- 상태
  ERROR_INFO VARCHAR2(2000),  -- 오류정보
  EXECUT_BEGIN_TM VARCHAR2(14),  -- 실행시작시각
  EXECUT_END_TM VARCHAR2(14),  -- 실행종료시각
  FRST_REGISTER_ID VARCHAR2(20),  -- 최초등록자ID
  FRST_REGIST_PNTTM date,  -- 최초등록시각
  LAST_UPDUSR_ID VARCHAR2(20),  -- 최종수정자ID
  LAST_UPDT_PNTTM date,  -- 최종수정시각
  PRIMARY KEY (BATCH_RESULT_ID)
);
CREATE TABLE TB_NCRD (
  NCRD_ID VARCHAR2(20) NOT NULL,  -- 명함ID
  NM VARCHAR2(50),  -- 명
  NCRD_TRGTER_ID VARCHAR2(20),  -- 명함대상자ID
  OTHBC_AT VARCHAR2(1) DEFAULT 'Y',  -- 외부공개여부
  EXTRL_USER_AT VARCHAR2(1) DEFAULT 'N',  -- EXTRL사용자여부
  CMPNY_NM VARCHAR2(100),  -- 회사명
  DEPT_NM VARCHAR2(100),  -- 부서명
  OFCPS_NM VARCHAR2(60),  -- 직책명
  IDNTFC_NO VARCHAR2(50),  -- IDNTFC번호
  FRST_MBTLNUM VARCHAR2(4),  -- 최초휴대전화
  MIDDLE_MBTLNUM VARCHAR2(4),  -- MIDDLE휴대전화
  END_MBTLNUM VARCHAR2(4),  -- 종료휴대전화
  EMAIL_ADRES VARCHAR2(100),  -- 이메일
  ADRES VARCHAR2(300),  -- 주소
  ZIP_CODE VARCHAR2(6),  -- 우편번호코드
  REMARK VARCHAR2(2000),  -- REMARK
  FRST_REGISTER_ID VARCHAR2(20),  -- 최초등록자ID
  FRST_REGIST_PNTTM date,  -- 최초등록시각
  LAST_UPDUSR_ID VARCHAR2(20),  -- 최종수정자ID
  LAST_UPDT_PNTTM date,  -- 최종수정시각
  PRIMARY KEY (NCRD_ID)
);
CREATE TABLE TB_DAM_KNO_IFM (
  KNWLDG_ID VARCHAR2(20) NOT NULL,  -- 지식ID
  KNWLDG_NM VARCHAR2(200),  -- 지식명
  KNWLDG_CN clob,  -- 지식내용
  KNWLDG_TY_CODE VARCHAR2(20),  -- 지식유형상세코드
  KNWLDG_EVL VARCHAR2(1) DEFAULT '1',  -- 지식평가
  OTHBC_AT VARCHAR2(1) DEFAULT 'Y',  -- 외부공개여부
  EVL_DE VARCHAR2(20),  -- 평가일자
  ATCH_FILE_ID VARCHAR2(20),  -- 첨부파일 묶음ID
  FRST_REGISTER_ID VARCHAR2(20),  -- 최초등록자ID
  FRST_REGIST_PNTTM date,  -- 최초등록시각
  LAST_UPDUSR_ID VARCHAR2(20),  -- 최종수정자ID
  LAST_UPDT_PNTTM date,  -- 최종수정시각
  PRIMARY KEY (KNWLDG_ID)
);
CREATE TABLE TB_ADBK_MANAGE (
  ADBK_ID VARCHAR2(20) NOT NULL,  -- 주소록ID
  ADBK_NM VARCHAR2(100),  -- 주소록명
  OTHBC_SCOPE VARCHAR2(20) DEFAULT '회사',  -- 외부공개SCOPE
  USE_AT VARCHAR2(1) DEFAULT 'Y',  -- 사용여부(Y/N)
  WRTER_ID VARCHAR2(20),  -- WRTERID
  TRGET_ORGNZT_ID VARCHAR2(20),  -- 대상ORGNZTID
  FRST_REGISTER_ID VARCHAR2(20),  -- 최초등록자ID
  FRST_REGIST_PNTTM date,  -- 최초등록시각
  LAST_UPDUSR_ID VARCHAR2(20),  -- 최종수정자ID
  LAST_UPDT_PNTTM date,  -- 최종수정시각
  PRIMARY KEY (ADBK_ID)
);
CREATE TABLE TB_COMMENT (
  ANSWER_NO number(20) NOT NULL,  -- 답변번호
  NTT_ID number(20) NOT NULL,  -- 게시물ID
  BBS_ID VARCHAR2(20) NOT NULL,  -- 게시판ID
  WRTER_ID VARCHAR2(20),  -- WRTERID
  WRTER_NM VARCHAR2(50),  -- WRTER명
  ANSWER VARCHAR2(2000),  -- 답변
  PASSWORD VARCHAR2(200),  -- 비밀번호(해시)
  USE_AT VARCHAR2(1) DEFAULT 'Y',  -- 사용여부(Y/N)
  FRST_REGISTER_ID VARCHAR2(20),  -- 최초등록자ID
  FRST_REGIST_PNTTM date,  -- 최초등록시각
  LAST_UPDUSR_ID VARCHAR2(20),  -- 최종수정자ID
  LAST_UPDT_PNTTM date,  -- 최종수정시각
  PRIMARY KEY (ANSWER_NO, NTT_ID, BBS_ID)
);
CREATE TABLE TB_MEMO_TODO (
  TODO_ID VARCHAR2(20) NOT NULL,  -- 할일ID
  TODO_SJ VARCHAR2(200),  -- 할일제목
  TODO_CN clob,  -- 할일내용
  TODO_BEGIN_TIME VARCHAR2(20),  -- 할일시작시간
  TODO_END_TIME VARCHAR2(20),  -- 할일종료시간
  WRTER_ID VARCHAR2(20),  -- WRTERID
  FRST_REGISTER_ID VARCHAR2(20),  -- 최초등록자ID
  FRST_REGIST_PNTTM date,  -- 최초등록시각
  LAST_UPDUSR_ID VARCHAR2(20),  -- 최종수정자ID
  LAST_UPDT_PNTTM date,  -- 최종수정시각
  PRIMARY KEY (TODO_ID)
);

CREATE VIEW VW_USER_MASTER (ESNTL_ID, USER_ID, PASSWORD, USER_NM, USER_ZIP, USER_ADRES, USER_EMAIL, GROUP_ID, USER_SE, ORGNZT_ID) AS SELECT ESNTL_ID, MBER_ID, PASSWORD, MBER_NM, ZIP, ADRES, MBER_EMAIL_ADRES, ' ', 'GNR', ' ' FROM TB_GNRL_MBER UNION ALL SELECT ESNTL_ID, EMPLYR_ID, PASSWORD, USER_NM, ZIP, HOUSE_ADRES, EMAIL_ADRES, GROUP_ID, 'USR', ORGNZT_ID FROM TB_EMPLYR_INFO UNION ALL SELECT ESNTL_ID, ENTRPRS_MBER_ID, ENTRPRS_MBER_PASSWORD, CMPNY_NM, ZIP, ADRES, APPLCNT_EMAIL_ADRES, ' ', 'ENT', ' ' FROM TB_ENTRPRS_MBER;
