-- JSP 전체 스키마 이관(미이관분) — MySQL DDL -> HSQL 자동변환
-- 원본: _legacy_jsp_src/script/ddl/mysql/*.sql

CREATE TABLE COMTCADMINISTCODE (
  ADMINIST_ZONE_SE CHAR(1) NOT NULL,
  ADMINIST_ZONE_CODE VARCHAR(10) NOT NULL,
  USE_AT CHAR(1) NOT NULL,
  ADMINIST_ZONE_NM VARCHAR(60),
  UPPER_ADMINIST_ZONE_CODE VARCHAR(10),
  CREAT_DE CHAR(20),
  ABL_DE CHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  FRST_REGISTER_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  PRIMARY KEY (ADMINIST_ZONE_SE,ADMINIST_ZONE_CODE)
);

CREATE TABLE COMTCADMINISTCODERECPTNLOG (
  OCCRRNC_DE CHAR(20) NOT NULL,
  ADMINIST_ZONE_SE CHAR(1) NOT NULL,
  ADMINIST_ZONE_CODE VARCHAR(10) NOT NULL,
  OPERT_SN NUMERIC(10) NOT NULL,
  CHANGE_SE_CODE VARCHAR(2),
  PROCESS_SE VARCHAR(2),
  ADMINIST_ZONE_NM VARCHAR(60),
  LOWEST_ADMINIST_ZONE_NM VARCHAR(60),
  CTPRVN_CODE VARCHAR(2),
  SIGNGU_CODE VARCHAR(3),
  EMD_CODE VARCHAR(3),
  LI_CODE VARCHAR(2),
  CREAT_DE CHAR(20),
  ABL_DE CHAR(20),
  ABL_ENNC CHAR(1),
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  PRIMARY KEY (OCCRRNC_DE,ADMINIST_ZONE_SE,ADMINIST_ZONE_CODE,OPERT_SN)
);

CREATE TABLE COMTCCMMNCLCODE (
  CL_CODE CHAR(3) NOT NULL,
  CL_CODE_NM VARCHAR(60),
  CL_CODE_DC VARCHAR(200),
  USE_AT CHAR(1),
  FRST_REGIST_PNTTM TIMESTAMP,
  FRST_REGISTER_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  PRIMARY KEY (CL_CODE)
);

CREATE TABLE COMTCCMMNCODE (
  CODE_ID VARCHAR(6) NOT NULL,
  CODE_ID_NM VARCHAR(60),
  CODE_ID_DC VARCHAR(200),
  USE_AT CHAR(1),
  CL_CODE CHAR(3),
  FRST_REGIST_PNTTM TIMESTAMP,
  FRST_REGISTER_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  PRIMARY KEY (CODE_ID)
);

CREATE TABLE COMTCCMMNDETAILCODE (
  CODE_ID VARCHAR(6) NOT NULL,
  CODE VARCHAR(15) NOT NULL,
  CODE_NM VARCHAR(60),
  CODE_DC VARCHAR(200),
  USE_AT CHAR(1),
  FRST_REGIST_PNTTM TIMESTAMP,
  FRST_REGISTER_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  PRIMARY KEY (CODE_ID,CODE)
);

CREATE TABLE COMTCZIP (
  ZIP VARCHAR(6) NOT NULL,
  SN NUMERIC(10) NOT NULL,
  CTPRVN_NM VARCHAR(20),
  SIGNGU_NM VARCHAR(20),
  EMD_NM VARCHAR(60),
  LI_BULD_NM VARCHAR(60),
  LNBR_DONG_HO VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  FRST_REGISTER_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  PRIMARY KEY (ZIP,SN)
);

CREATE TABLE COMTHDBMNTRNGLOGINFO (
  DATA_SOURC_NM VARCHAR(60) NOT NULL,
  SERVER_NM VARCHAR(60),
  DBMS_KND VARCHAR(2),
  CECK_SQL VARCHAR(250),
  MNGR_NM VARCHAR(60),
  MNGR_EMAIL_ADRES VARCHAR(50),
  MNTRNG_STTUS CHAR(2),
  LOG_INFO VARCHAR(2000),
  CREAT_DT TIMESTAMP,
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP NOT NULL,
  LAST_UPDT_PNTTM TIMESTAMP NOT NULL,
  LAST_UPDUSR_ID VARCHAR(20),
  LOG_ID CHAR(20) NOT NULL,
  PRIMARY KEY (LOG_ID)
);

CREATE TABLE COMTHEMAILDSPTCHMANAGE (
  MSSAGE_ID VARCHAR(20) NOT NULL,
  EMAIL_CN MEDIUMTEXT,
  SNDR VARCHAR(50) NOT NULL,
  RCVER VARCHAR(50) NOT NULL,
  SJ VARCHAR(60) NOT NULL,
  SNDNG_RESULT_CODE CHAR(1),
  DSPTCH_DT CHAR(20) NOT NULL,
  ATCH_FILE_ID CHAR(20),
  PRIMARY KEY (MSSAGE_ID)
);

CREATE TABLE COMTHEMPLYRINFOCHANGEDTLS (
  EMPLYR_ID VARCHAR(20) NOT NULL,
  CHANGE_DE CHAR(20) NOT NULL,
  ORGNZT_ID CHAR(20),
  GROUP_ID CHAR(20),
  EMPL_NO VARCHAR(20),
  SEXDSTN_CODE CHAR(1),
  BRTHDY CHAR(20),
  FXNUM VARCHAR(20),
  HOUSE_ADRES VARCHAR(100),
  HOUSE_END_TELNO VARCHAR(4),
  AREA_NO VARCHAR(4),
  DETAIL_ADRES VARCHAR(100),
  ZIP VARCHAR(6),
  OFFM_TELNO VARCHAR(20),
  MBTLNUM VARCHAR(20),
  EMAIL_ADRES VARCHAR(50),
  HOUSE_MIDDLE_TELNO VARCHAR(4),
  PSTINST_CODE CHAR(8),
  EMPLYR_STTUS_CODE CHAR(1),
  ESNTL_ID CHAR(20),
  PRIMARY KEY (EMPLYR_ID,CHANGE_DE)
);

CREATE TABLE COMTHHTTPMONLOGINFO (
  SYS_ID VARCHAR(20) NOT NULL,
  SITE_URL VARCHAR(100),
  WEBSVC_KND VARCHAR(10),
  HTTP_STTUS_CODE VARCHAR(3),
  CREAT_DT TIMESTAMP,
  LOG_INFO VARCHAR(2000),
  MNGR_NM VARCHAR(60),
  MNGR_EMAIL_ADRES VARCHAR(50),
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  LOG_ID CHAR(20) NOT NULL,
  PRIMARY KEY (SYS_ID,LOG_ID)
);

CREATE TABLE COMTHPROGRMCHANGEDTLS (
  PROGRM_FILE_NM VARCHAR(60) NOT NULL,
  REQUST_NO NUMERIC(10) NOT NULL,
  RQESTER_ID VARCHAR(20) NOT NULL,
  CHANGE_REQUST_CN VARCHAR(1000),
  REQUST_PROCESS_CN MEDIUMTEXT,
  OPETR_ID VARCHAR(20),
  PROCESS_STTUS_CODE VARCHAR(15) NOT NULL,
  PROCESS_DE CHAR(20),
  RQESTDE CHAR(20),
  REQUST_SJ VARCHAR(60) NOT NULL,
  PRIMARY KEY (PROGRM_FILE_NM,REQUST_NO),
  ON DELETE CASCADE
);

CREATE TABLE COMTHSYSHIST (
  HIST_ID CHAR(20) NOT NULL,
  FRST_REGIST_PNTTM TIMESTAMP,
  FRST_REGISTER_ID VARCHAR(20) NOT NULL,
  LAST_UPDT_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  HIST_SE_CODE CHAR(6) NOT NULL,
  HIST_CN VARCHAR(2500) NOT NULL,
  SYS_NM VARCHAR(255) NOT NULL,
  ATCH_FILE_ID CHAR(20),
  PRIMARY KEY (HIST_ID)
);

CREATE TABLE COMTHTRSMRCVMNTRNGLOGINFO (
  LOG_ID CHAR(20) NOT NULL,
  CNTC_ID CHAR(8) NOT NULL,
  TEST_CLASS_NM VARCHAR(255),
  MNGR_NM VARCHAR(60),
  MNGR_EMAIL_ADRES VARCHAR(50),
  MNTRNG_STTUS CHAR(2),
  LOG_INFO VARCHAR(2000),
  CREAT_DT TIMESTAMP,
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP NOT NULL,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP NOT NULL,
  PRIMARY KEY (LOG_ID)
);

CREATE TABLE COMTNADBK (
  EMPLYR_ID VARCHAR(20),
  NCRD_ID CHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDT_PNTTM TIMESTAMP,
  FRST_REGISTER_ID VARCHAR(20),
  LAST_UPDUSR_ID VARCHAR(20),
  ADBK_CONSTNT_ID CHAR(20) NOT NULL,
  NM VARCHAR(50),
  EMAIL_ADRES VARCHAR(50),
  MBTLNUM VARCHAR(20),
  FXNUM VARCHAR(20),
  OFFM_TELNO VARCHAR(20),
  HOUSE_TELNO VARCHAR(20),
  ADBK_ID CHAR(20) NOT NULL,
  PRIMARY KEY (ADBK_CONSTNT_ID,ADBK_ID),
  ON DELETE CASCADE
);

CREATE TABLE COMTNADBKMANAGE (
  ADBK_ID CHAR(20) NOT NULL,
  ADBK_NM VARCHAR(50) NOT NULL,
  OTHBC_SCOPE VARCHAR(20) NOT NULL,
  USE_AT CHAR(1) NOT NULL,
  WRTER_ID VARCHAR(20),
  TRGET_ORGNZT_ID CHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP NOT NULL,
  LAST_UPDT_PNTTM TIMESTAMP,
  FRST_REGISTER_ID VARCHAR(20) NOT NULL,
  LAST_UPDUSR_ID VARCHAR(20),
  PRIMARY KEY (ADBK_ID)
);

CREATE TABLE COMTNADMINISTRATIONWORD (
  ADMINIST_WORD_ID CHAR(20) NOT NULL,
  ADMINIST_WORD_NM VARCHAR(255),
  ADMINIST_WORD_ENG_NM VARCHAR(255),
  ADMINIST_WORD_ABRV_NM VARCHAR(255),
  THEMA_RELM VARCHAR(255),
  WORD_SE VARCHAR(255),
  RELATE_STD_WORD VARCHAR(255),
  ADMINIST_WORD_DFN VARCHAR(2500),
  ADMINIST_WORD_DC VARCHAR(4000),
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  PRIMARY KEY (ADMINIST_WORD_ID)
);

CREATE TABLE COMTNANNVRSRYMANAGE (
  ANNVRSRY_ID VARCHAR(20) NOT NULL,
  USER_ID VARCHAR(20) NOT NULL,
  ANNVRSRY_SE VARCHAR(2) NOT NULL,
  ANNVRSRY_NM VARCHAR(255) NOT NULL,
  ANNVRSRY CHAR(20) NOT NULL,
  CLDR_SE CHAR(1) NOT NULL,
  ANNVRSRY_NTCN_SETUP CHAR(1),
  ANNVRSRY_NTCN_BGNDE CHAR(20),
  MEMO VARCHAR(1000),
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  REPTIT_AT CHAR(1),
  PRIMARY KEY (ANNVRSRY_ID)
);

CREATE TABLE COMTNAUTHORGROUPINFO (
  GROUP_ID CHAR(20) NOT NULL,
  GROUP_NM VARCHAR(60) NOT NULL,
  GROUP_CREAT_DE CHAR(20) NOT NULL,
  GROUP_DC VARCHAR(100),
  PRIMARY KEY (GROUP_ID)
);

CREATE TABLE COMTNAUTHORINFO (
  AUTHOR_CODE VARCHAR(30) NOT NULL,
  AUTHOR_NM VARCHAR(60) NOT NULL,
  AUTHOR_DC VARCHAR(200),
  AUTHOR_CREAT_DE CHAR(20) NOT NULL,
  PRIMARY KEY (AUTHOR_CODE)
);

CREATE TABLE COMTNAUTHORROLERELATE (
  AUTHOR_CODE VARCHAR(30) NOT NULL,
  ROLE_CODE VARCHAR(50) NOT NULL,
  CREAT_DT TIMESTAMP,
  PRIMARY KEY (AUTHOR_CODE,ROLE_CODE),
  ON DELETE CASCADE,
  ON DELETE CASCADE
);

CREATE TABLE COMTNBACKUPOPERT (
  BACKUP_OPERT_ID VARCHAR(20) NOT NULL,
  BACKUP_OPERT_NM VARCHAR(60),
  BACKUP_ORGINL_DRCTRY VARCHAR(255),
  BACKUP_STRE_DRCTRY VARCHAR(255),
  CMPRS_SE VARCHAR(2),
  EXECUT_CYCLE VARCHAR(2),
  EXECUT_SCHDUL_DE CHAR(20),
  EXECUT_SCHDUL_HOUR CHAR(2),
  EXECUT_SCHDUL_MNT CHAR(2),
  EXECUT_SCHDUL_SECND CHAR(2),
  USE_AT CHAR(1),
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP NOT NULL,
  PRIMARY KEY (BACKUP_OPERT_ID)
);

CREATE TABLE COMTNBACKUPRESULT (
  BACKUP_RESULT_ID VARCHAR(20) NOT NULL,
  BACKUP_OPERT_ID VARCHAR(20) NOT NULL,
  BACKUP_FILE VARCHAR(255),
  STTUS VARCHAR(2),
  ERROR_INFO VARCHAR(2000),
  EXECUT_BEGIN_TM VARCHAR(14),
  EXECUT_END_TM VARCHAR(14),
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP NOT NULL,
  PRIMARY KEY (BACKUP_RESULT_ID)
);

CREATE TABLE COMTNBACKUPSCHDULDFK (
  BACKUP_OPERT_ID VARCHAR(20) NOT NULL,
  EXECUT_SCHDUL_DFK_SE CHAR(1) NOT NULL,
  PRIMARY KEY (BACKUP_OPERT_ID,EXECUT_SCHDUL_DFK_SE)
);

CREATE TABLE COMTNBANNER (
  BANNER_ID CHAR(20) NOT NULL,
  BANNER_NM VARCHAR(60) NOT NULL,
  LINK_URL VARCHAR(255) NOT NULL,
  BANNER_IMAGE VARCHAR(60) NOT NULL,
  BANNER_DC VARCHAR(200),
  REFLCT_AT CHAR(1) NOT NULL,
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  BANNER_IMAGE_FILE VARCHAR(60),
  SORT_ORDR NUMERIC(8),
  PRIMARY KEY (BANNER_ID)
);

CREATE TABLE COMTNBATCHOPERT (
  BATCH_OPERT_ID VARCHAR(20) NOT NULL,
  BATCH_OPERT_NM VARCHAR(60),
  BATCH_PROGRM VARCHAR(255),
  PARAMTR VARCHAR(250),
  USE_AT CHAR(1),
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP NOT NULL,
  PRIMARY KEY (BATCH_OPERT_ID)
);

CREATE TABLE COMTNBATCHRESULT (
  BATCH_RESULT_ID VARCHAR(20) NOT NULL,
  BATCH_SCHDUL_ID VARCHAR(20) NOT NULL,
  BATCH_OPERT_ID VARCHAR(20) NOT NULL,
  PARAMTR VARCHAR(250),
  STTUS VARCHAR(2),
  ERROR_INFO VARCHAR(2000),
  EXECUT_BEGIN_TM VARCHAR(14),
  EXECUT_END_TM VARCHAR(14),
  LAST_UPDT_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP NOT NULL,
  FRST_REGISTER_ID VARCHAR(20),
  PRIMARY KEY (BATCH_RESULT_ID)
);

CREATE TABLE COMTNBATCHSCHDUL (
  BATCH_SCHDUL_ID VARCHAR(20) NOT NULL,
  BATCH_OPERT_ID VARCHAR(20) NOT NULL,
  EXECUT_CYCLE VARCHAR(2),
  EXECUT_SCHDUL_DE CHAR(20),
  EXECUT_SCHDUL_HOUR CHAR(2),
  EXECUT_SCHDUL_MNT CHAR(2),
  EXECUT_SCHDUL_SECND CHAR(2),
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP NOT NULL,
  PRIMARY KEY (BATCH_SCHDUL_ID)
);

CREATE TABLE COMTNBATCHSCHDULDFK (
  BATCH_SCHDUL_ID VARCHAR(20) NOT NULL,
  EXECUT_SCHDUL_DFK_SE CHAR(1) NOT NULL,
  PRIMARY KEY (BATCH_SCHDUL_ID,EXECUT_SCHDUL_DFK_SE)
);

CREATE TABLE COMTNBBS (
  NTT_ID NUMERIC(20) NOT NULL,
  BBS_ID CHAR(30) NOT NULL,
  NTT_NO NUMERIC(20),
  NTT_SJ VARCHAR(2000),
  NTT_CN MEDIUMTEXT,
  ANSWER_AT CHAR(1),
  PARNTSCTT_NO NUMERIC(10),
  ANSWER_LC NUMERIC(8),
  SORT_ORDR NUMERIC(8),
  RDCNT NUMERIC(10),
  USE_AT CHAR(1) NOT NULL,
  NTCE_BGNDE CHAR(20),
  NTCE_ENDDE CHAR(20),
  NTCR_ID VARCHAR(20),
  NTCR_NM VARCHAR(20),
  PASSWORD VARCHAR(200),
  ATCH_FILE_ID CHAR(20),
  NOTICE_AT CHAR(1),
  SJ_BOLD_AT CHAR(1),
  SECRET_AT CHAR(1),
  FRST_REGIST_PNTTM TIMESTAMP NOT NULL,
  FRST_REGISTER_ID VARCHAR(20) NOT NULL,
  LAST_UPDT_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  BLOG_ID CHAR(20),
  PRIMARY KEY (NTT_ID,BBS_ID)
);

CREATE TABLE COMTNBBSMASTER (
  BBS_ID CHAR(30) NOT NULL,
  BBS_NM VARCHAR(255) NOT NULL,
  BBS_INTRCN VARCHAR(2400),
  BBS_TY_CODE CHAR(6) NOT NULL,
  REPLY_POSBL_AT CHAR(1),
  FILE_ATCH_POSBL_AT CHAR(1) NOT NULL,
  ATCH_POSBL_FILE_NUMBER NUMERIC(2) NOT NULL,
  ATCH_POSBL_FILE_SIZE NUMERIC(8),
  USE_AT CHAR(1) NOT NULL,
  TMPLAT_ID CHAR(20),
  CMMNTY_ID CHAR(20),
  FRST_REGISTER_ID VARCHAR(20) NOT NULL,
  FRST_REGIST_PNTTM TIMESTAMP NOT NULL,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  BLOG_ID CHAR(20),
  BLOG_AT CHAR(2),
  PRIMARY KEY (BBS_ID)
);

CREATE TABLE COMTNBBSMASTEROPTN (
  BBS_ID CHAR(30) NOT NULL,
  ANSWER_AT CHAR(1) NOT NULL,
  STSFDG_AT CHAR(1) NOT NULL,
  FRST_REGIST_PNTTM TIMESTAMP NOT NULL,
  LAST_UPDT_PNTTM TIMESTAMP,
  FRST_REGISTER_ID VARCHAR(20) NOT NULL,
  LAST_UPDUSR_ID VARCHAR(20),
  PRIMARY KEY (BBS_ID)
);

CREATE TABLE COMTNBBSUSE (
  BBS_ID CHAR(30) NOT NULL,
  TRGET_ID CHAR(20) NOT NULL,
  USE_AT CHAR(1) NOT NULL,
  REGIST_SE_CODE CHAR(6),
  FRST_REGIST_PNTTM TIMESTAMP,
  FRST_REGISTER_ID VARCHAR(20) NOT NULL,
  LAST_UPDT_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  PRIMARY KEY (BBS_ID,TRGET_ID)
);

CREATE TABLE COMTNBKMKMENUMANAGERESULT (
  MENU_ID NUMERIC(20) NOT NULL,
  EMPLYR_ID VARCHAR(20) NOT NULL,
  MENU_NM VARCHAR(60) NOT NULL,
  PROGRM_STRE_PATH VARCHAR(100) NOT NULL,
  PRIMARY KEY (MENU_ID,EMPLYR_ID)
);

CREATE TABLE COMTNBLOG (
  BLOG_ID CHAR(20) NOT NULL,
  BLOG_NM VARCHAR(255) NOT NULL,
  BLOG_INTRCN VARCHAR(2400),
  USE_AT CHAR(1) NOT NULL,
  REGIST_SE_CODE CHAR(6),
  TMPLAT_ID CHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP NOT NULL,
  FRST_REGISTER_ID VARCHAR(20) NOT NULL,
  LAST_UPDT_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  BBS_ID CHAR(30) DEFAULT,
  BLOG_AT CHAR(2) DEFAULT,
  PRIMARY KEY (BLOG_ID)
);

CREATE TABLE COMTNBLOGUSER (
  BLOG_ID CHAR(20) NOT NULL,
  EMPLYR_ID VARCHAR(20) NOT NULL,
  MNGR_AT CHAR(1) NOT NULL,
  MBER_STTUS VARCHAR(15),
  SBSCRB_DE TIMESTAMP,
  SECSN_DE CHAR(20),
  USE_AT CHAR(1),
  FRST_REGIST_PNTTM TIMESTAMP NOT NULL,
  FRST_REGISTER_ID VARCHAR(20) NOT NULL,
  LAST_UPDT_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  PRIMARY KEY (BLOG_ID,EMPLYR_ID)
);

CREATE TABLE COMTNBNDTCECKMANAGE (
  BNDT_CECK_SE CHAR(2) NOT NULL,
  BNDT_CECK_CODE VARCHAR(10) NOT NULL,
  BNDT_CECK_CODE_NM VARCHAR(255) NOT NULL,
  USE_AT CHAR(1) NOT NULL,
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  PRIMARY KEY (BNDT_CECK_CODE,BNDT_CECK_SE)
);

CREATE TABLE COMTNBNDTDIARY (
  BNDT_ID VARCHAR(20) NOT NULL,
  BNDT_DE CHAR(8) NOT NULL,
  BNDT_CECK_SE CHAR(2) NOT NULL,
  BNDT_CECK_CODE VARCHAR(10) NOT NULL,
  CHCK_STTUS VARCHAR(1000),
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  PRIMARY KEY (BNDT_ID,BNDT_DE,BNDT_CECK_SE,BNDT_CECK_CODE)
);

CREATE TABLE COMTNBNDTMANAGE (
  BNDT_ID VARCHAR(20) NOT NULL,
  BNDT_DE CHAR(8) NOT NULL,
  RM VARCHAR(2500),
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  PRIMARY KEY (BNDT_ID,BNDT_DE)
);

CREATE TABLE COMTNCLUB (
  CLB_ID CHAR(20) NOT NULL,
  CMMNTY_ID CHAR(20) NOT NULL,
  CLB_NM VARCHAR(255) NOT NULL,
  CLB_INTRCN VARCHAR(2400),
  USE_AT CHAR(1) NOT NULL,
  REGIST_SE_CODE CHAR(6),
  TMPLAT_ID CHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP NOT NULL,
  FRST_REGISTER_ID VARCHAR(20) NOT NULL,
  LAST_UPDT_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  PRIMARY KEY (CLB_ID,CMMNTY_ID)
);

CREATE TABLE COMTNCMMNTY (
  CMMNTY_ID CHAR(20) NOT NULL,
  CMMNTY_NM VARCHAR(255) NOT NULL,
  CMMNTY_INTRCN VARCHAR(2400),
  USE_AT CHAR(1) NOT NULL,
  REGIST_SE_CODE CHAR(6),
  TMPLAT_ID CHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP NOT NULL,
  FRST_REGISTER_ID VARCHAR(20) NOT NULL,
  LAST_UPDT_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  PRIMARY KEY (CMMNTY_ID)
);

CREATE TABLE COMTNCMMNTYUSER (
  CMMNTY_ID CHAR(20) NOT NULL,
  EMPLYR_ID VARCHAR(20) NOT NULL,
  MNGR_AT CHAR(1) NOT NULL,
  MBER_STTUS VARCHAR(15),
  SBSCRB_DE TIMESTAMP,
  SECSN_DE CHAR(20),
  USE_AT CHAR(1),
  FRST_REGIST_PNTTM TIMESTAMP NOT NULL,
  FRST_REGISTER_ID VARCHAR(20) NOT NULL,
  LAST_UPDT_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  PRIMARY KEY (CMMNTY_ID,EMPLYR_ID)
);

CREATE TABLE COMTNCNSLTLIST (
  CNSLT_ID CHAR(20) NOT NULL,
  CNSLT_SJ VARCHAR(255),
  OTHBC_AT CHAR(1),
  EMAIL_ADRES VARCHAR(50),
  CNSLT_CN VARCHAR(2500),
  MANAGT_CN VARCHAR(2500),
  MANAGT_DE CHAR(20),
  RDCNT NUMERIC(10),
  ATCH_FILE_ID CHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  FRST_REGISTER_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  AREA_NO VARCHAR(4),
  MIDDLE_TELNO VARCHAR(4),
  END_TELNO VARCHAR(4),
  FRST_MBTLNUM VARCHAR(4),
  MIDDLE_MBTLNUM VARCHAR(4),
  END_MBTLNUM VARCHAR(4),
  WRITNG_DE CHAR(20),
  WRTER_NM VARCHAR(20),
  EMAIL_ANSWER_AT CHAR(1),
  QNA_PROCESS_STTUS_CODE CHAR(1),
  WRITNG_PASSWORD VARCHAR(20),
  PRIMARY KEY (CNSLT_ID)
);

CREATE TABLE COMTNCNTCINSTT (
  INSTT_ID VARCHAR(20) NOT NULL,
  INSTT_NM VARCHAR(100),
  FRST_REGISTER_ID VARCHAR(20),
  LAST_UPDUSR_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDT_PNTTM TIMESTAMP,
  USE_AT CHAR(1),
  PRIMARY KEY (INSTT_ID)
);

CREATE TABLE COMTNCNTCMESSAGE (
  CNTC_MSSAGE_ID VARCHAR(20) NOT NULL,
  CNTC_MSSAGE_NM VARCHAR(100),
  UPPER_CNTC_MSSAGE_ID VARCHAR(20),
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  USE_AT CHAR(1),
  PRIMARY KEY (CNTC_MSSAGE_ID)
);

CREATE TABLE COMTNCNTCMESSAGEITEM (
  CNTC_MSSAGE_ID VARCHAR(20) NOT NULL,
  IEM_ID VARCHAR(20) NOT NULL,
  IEM_NM VARCHAR(100),
  IEM_TY VARCHAR(50),
  IEM_LT NUMERIC(8),
  USE_AT CHAR(1),
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  PRIMARY KEY (CNTC_MSSAGE_ID,IEM_ID)
);

CREATE TABLE COMTNCNTCSERVICE (
  INSTT_ID VARCHAR(20) NOT NULL,
  SYS_ID VARCHAR(20) NOT NULL,
  SVC_ID VARCHAR(20) NOT NULL,
  SVC_NM VARCHAR(255),
  REQUST_MSSAGE_ID VARCHAR(20),
  RSPNS_MSSAGE_ID VARCHAR(20),
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  USE_AT CHAR(1),
  PRIMARY KEY (INSTT_ID,SYS_ID,SVC_ID)
);

CREATE TABLE COMTNCNTCSYSTEM (
  INSTT_ID VARCHAR(20) NOT NULL,
  SYS_ID VARCHAR(20) NOT NULL,
  SYS_NM VARCHAR(255),
  SYS_IP VARCHAR(23),
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  USE_AT CHAR(1),
  PRIMARY KEY (INSTT_ID,SYS_ID)
);

CREATE TABLE COMTNCOMMENT (
  NTT_ID NUMERIC(20) NOT NULL,
  BBS_ID CHAR(30) NOT NULL,
  ANSWER_NO NUMERIC(20) NOT NULL,
  WRTER_ID VARCHAR(20),
  WRTER_NM VARCHAR(20),
  ANSWER VARCHAR(200),
  USE_AT CHAR(1) NOT NULL,
  FRST_REGIST_PNTTM TIMESTAMP NOT NULL,
  FRST_REGISTER_ID VARCHAR(20) NOT NULL,
  LAST_UPDT_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  PASSWORD VARCHAR(200),
  PRIMARY KEY (NTT_ID,BBS_ID,ANSWER_NO)
);

CREATE TABLE COMTNCOMMUTE (
  WRKTM_ID CHAR(20) NOT NULL,
  EMPLYR_ID VARCHAR(20) NOT NULL,
  ORGNZT_ID VARCHAR(20),
  WRKT_DT VARCHAR(10) NOT NULL,
  WRK_START_TIME VARCHAR(14),
  WRK_END_TIME VARCHAR(14),
  WRK_HOURS CHAR(2),
  OVTMWRK_HOURS CHAR(2),
  WRK_START_STATUS VARCHAR(10),
  WRK_END_STATUS VARCHAR(10),
  RM VARCHAR(100),
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  PRIMARY KEY (EMPLYR_ID, WRKT_DT)
);

CREATE TABLE COMTNCPYRHTINFO (
  CPYRHT_ID CHAR(20) NOT NULL,
  CPYRHT_PRTC_POLICY_CN VARCHAR(2500),
  FRST_REGIST_PNTTM TIMESTAMP,
  FRST_REGISTER_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  PRIMARY KEY (CPYRHT_ID)
);

CREATE TABLE COMTNCTSNNMANAGE (
  CTSNN_ID VARCHAR(20) NOT NULL,
  USER_ID VARCHAR(20) NOT NULL,
  CTSNN_CODE CHAR(2) NOT NULL,
  REQST_DE CHAR(20) NOT NULL,
  CTSNN_NM VARCHAR(255) NOT NULL,
  TRGTER_NM VARCHAR(20) NOT NULL,
  BRTHDY CHAR(20) NOT NULL,
  OCCRRNC_DE CHAR(20) NOT NULL,
  RELATE CHAR(2) NOT NULL,
  RM VARCHAR(2500),
  SANCTNER_ID VARCHAR(20) NOT NULL,
  CONFM_AT CHAR(1),
  SANCTN_DT TIMESTAMP,
  RETURN_RESN VARCHAR(1000),
  INFRML_SANCTN_ID CHAR(20),
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  PRIMARY KEY (CTSNN_ID)
);

CREATE TABLE COMTNDAMCALRES (
  ORGNZT_ID VARCHAR(20),
  EXPERT_ID CHAR(20),
  KNWLDG_TY_CODE VARCHAR(3),
  EMPLYR_ID VARCHAR(20),
  KNWLDG_NM VARCHAR(60),
  KNWLDG_CN VARCHAR(2500),
  ATCH_FILE_ID CHAR(20),
  PARNTS_KNWLDG_ID CHAR(20),
  ANSWER_DP NUMERIC(20),
  ANSWER_ORDR NUMERIC(20),
  ANSWER_GROUP_NO NUMERIC(20),
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  KNWLDG_ID CHAR(20) NOT NULL,
  PRIMARY KEY (KNWLDG_ID)
);

CREATE TABLE COMTNDAMKNOIFM (
  KNWLDG_ID CHAR(20) NOT NULL,
  KNWLDG_TY_CODE VARCHAR(3),
  ORGNZT_ID VARCHAR(20),
  EXPERT_ID CHAR(20),
  EMPLYR_ID VARCHAR(20),
  KNWLDG_NM VARCHAR(60),
  KNWLDG_CN VARCHAR(2500),
  KWRD VARCHAR(100),
  OTHBC_AT CHAR(1),
  KNWLDG_EVL CHAR(1),
  COLCT_DE CHAR(20),
  EVL_DE CHAR(20),
  ATCH_FILE_ID CHAR(20),
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  DSUSE_DE CHAR(20),
  PRIMARY KEY (KNWLDG_ID)
);

CREATE TABLE COMTNDAMMAPKNO (
  KNWLDG_TY_CODE VARCHAR(3) NOT NULL,
  ORGNZT_ID VARCHAR(20),
  EXPERT_ID CHAR(20),
  KNWLDG_TY_NM VARCHAR(60),
  CL_DE CHAR(20),
  KNWLDG_URL VARCHAR(255),
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  PRIMARY KEY (KNWLDG_TY_CODE)
);

CREATE TABLE COMTNDAMMAPTEAM (
  ORGNZT_ID VARCHAR(20) NOT NULL,
  ORGNZT_NM VARCHAR(20),
  CL_DE CHAR(20),
  KNWLDG_URL VARCHAR(255),
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  PRIMARY KEY (ORGNZT_ID)
);

CREATE TABLE COMTNDAMPRO (
  EXPERT_ID CHAR(20) NOT NULL,
  KNWLDG_TY_CODE VARCHAR(3) NOT NULL,
  EXPERT_GRAD CHAR(1) NOT NULL,
  EXPERT_CONFM_DE CHAR(20),
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  EXPERT_DC VARCHAR(2000),
  PRIMARY KEY (EXPERT_ID,KNWLDG_TY_CODE,EXPERT_GRAD)
);

CREATE TABLE COMTNDBMNTRNG (
  DATA_SOURC_NM VARCHAR(60) NOT NULL,
  SERVER_NM VARCHAR(60),
  DBMS_KND VARCHAR(2),
  CECK_SQL VARCHAR(250),
  MNGR_NM VARCHAR(60),
  MNGR_EMAIL_ADRES VARCHAR(50),
  MNTRNG_STTUS CHAR(2),
  CREAT_DT TIMESTAMP,
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP NOT NULL,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP NOT NULL,
  PRIMARY KEY (DATA_SOURC_NM)
);

CREATE TABLE COMTNDEPTJOB (
  DEPT_JOB_ID CHAR(20) NOT NULL,
  DEPT_JOBBX_ID CHAR(6) NOT NULL,
  DEPT_JOB_NM VARCHAR(255) NOT NULL,
  DEPT_JOB_CN VARCHAR(2500) NOT NULL,
  ATCH_FILE_ID CHAR(20),
  CHARGER_ID VARCHAR(20) NOT NULL,
  PRIORT CHAR(1) NOT NULL,
  FRST_REGISTER_ID VARCHAR(20) NOT NULL,
  FRST_REGIST_PNTTM TIMESTAMP NOT NULL,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  PRIMARY KEY (DEPT_JOB_ID)
);

CREATE TABLE COMTNDEPTJOBBX (
  DEPT_JOBBX_ID CHAR(6) NOT NULL,
  DEPT_JOBBX_NM VARCHAR(255) NOT NULL,
  DEPT_ID VARCHAR(20) NOT NULL,
  INDICT_ORDR NUMERIC(6),
  FRST_REGISTER_ID VARCHAR(20) NOT NULL,
  FRST_REGIST_PNTTM TIMESTAMP NOT NULL,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  PRIMARY KEY (DEPT_JOBBX_ID)
);

CREATE TABLE COMTNDIARYINFO (
  SCHDUL_ID CHAR(20) NOT NULL,
  DIARY_ID CHAR(20) NOT NULL,
  DIARY_PROGRSRT NUMERIC(3),
  DIARY_NM VARCHAR(255),
  DRCT_MATTER VARCHAR(2500),
  PARTCLR_MATTER VARCHAR(2500),
  ATCH_FILE_ID CHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  FRST_REGISTER_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  PRIMARY KEY (SCHDUL_ID,DIARY_ID)
);

CREATE TABLE COMTNDTAUSESTATS (
  DTA_USE_STATS_ID CHAR(20) NOT NULL,
  BBS_ID CHAR(30) NOT NULL,
  NTT_ID NUMERIC(20) NOT NULL,
  ATCH_FILE_ID CHAR(20) NOT NULL,
  FILE_SN NUMERIC(10) NOT NULL,
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  PRIMARY KEY (DTA_USE_STATS_ID)
);

CREATE TABLE COMTNEMPLYRINFO (
  EMPLYR_ID VARCHAR(20) NOT NULL,
  ORGNZT_ID CHAR(20),
  USER_NM VARCHAR(60) NOT NULL,
  PASSWORD VARCHAR(200) NOT NULL,
  EMPL_NO VARCHAR(20),
  IHIDNUM VARCHAR(200),
  SEXDSTN_CODE CHAR(1),
  BRTHDY CHAR(20),
  FXNUM VARCHAR(20),
  HOUSE_ADRES VARCHAR(100) NOT NULL,
  PASSWORD_HINT VARCHAR(100) NOT NULL,
  PASSWORD_CNSR VARCHAR(100) NOT NULL,
  HOUSE_END_TELNO VARCHAR(4) NOT NULL,
  AREA_NO VARCHAR(4) NOT NULL,
  DETAIL_ADRES VARCHAR(100),
  ZIP VARCHAR(6) NOT NULL,
  OFFM_TELNO VARCHAR(20),
  MBTLNUM VARCHAR(20),
  EMAIL_ADRES VARCHAR(50),
  OFCPS_NM VARCHAR(60),
  HOUSE_MIDDLE_TELNO VARCHAR(4) NOT NULL,
  GROUP_ID CHAR(20),
  PSTINST_CODE CHAR(8),
  EMPLYR_STTUS_CODE CHAR(1) NOT NULL,
  ESNTL_ID CHAR(20) NOT NULL,
  CRTFC_DN_VALUE VARCHAR(100),
  SBSCRB_DE TIMESTAMP,
  LOCK_AT CHAR(1),
  LOCK_CNT NUMERIC(3),
  LOCK_LAST_PNTTM TIMESTAMP,
  CHG_PWD_LAST_PNTTM TIMESTAMP,
  PRIMARY KEY (EMPLYR_ID),
  ON DELETE SET,
  ON DELETE SET
);

CREATE TABLE COMTNEMPLYRSCRTYESTBS (
  SCRTY_DTRMN_TRGET_ID VARCHAR(20) NOT NULL,
  MBER_TY_CODE CHAR(5),
  AUTHOR_CODE VARCHAR(30) NOT NULL,
  PRIMARY KEY (SCRTY_DTRMN_TRGET_ID)
);

CREATE TABLE COMTNENTRPRSMBER (
  ENTRPRS_MBER_ID VARCHAR(20) NOT NULL,
  ENTRPRS_SE_CODE CHAR(8),
  BIZRNO VARCHAR(10),
  JURIRNO VARCHAR(13),
  CMPNY_NM VARCHAR(60) NOT NULL,
  CXFC VARCHAR(50),
  ZIP VARCHAR(6) NOT NULL,
  ADRES VARCHAR(100) NOT NULL,
  ENTRPRS_MIDDLE_TELNO VARCHAR(4) NOT NULL,
  FXNUM VARCHAR(20),
  INDUTY_CODE CHAR(1),
  APPLCNT_NM VARCHAR(50) NOT NULL,
  APPLCNT_IHIDNUM VARCHAR(200),
  SBSCRB_DE TIMESTAMP,
  ENTRPRS_MBER_STTUS VARCHAR(15),
  ENTRPRS_MBER_PASSWORD VARCHAR(200),
  ENTRPRS_MBER_PASSWORD_HINT VARCHAR(100) NOT NULL,
  ENTRPRS_MBER_PASSWORD_CNSR VARCHAR(100) NOT NULL,
  GROUP_ID CHAR(20),
  DETAIL_ADRES VARCHAR(100),
  ENTRPRS_END_TELNO VARCHAR(4) NOT NULL,
  AREA_NO VARCHAR(4) NOT NULL,
  APPLCNT_EMAIL_ADRES VARCHAR(50) NOT NULL,
  ESNTL_ID CHAR(20) NOT NULL,
  LOCK_AT CHAR(1),
  LOCK_CNT NUMERIC(3),
  LOCK_LAST_PNTTM TIMESTAMP,
  CHG_PWD_LAST_PNTTM TIMESTAMP,
  PRIMARY KEY (ENTRPRS_MBER_ID),
  ON DELETE SET
);

CREATE TABLE COMTNEVENTATDRN (
  APPLCNT_ID VARCHAR(20) NOT NULL,
  EVENT_ID CHAR(20) NOT NULL,
  REQST_DE CHAR(20) NOT NULL,
  SANCTNER_ID VARCHAR(20) NOT NULL,
  CONFM_AT CHAR(1),
  SANCTN_DT TIMESTAMP,
  RETURN_RESN VARCHAR(1000),
  INFRML_SANCTN_ID CHAR(20),
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  PRIMARY KEY (APPLCNT_ID,EVENT_ID)
);

CREATE TABLE COMTNEVENTINFO (
  EVENT_ID CHAR(20) NOT NULL,
  BSNS_YEAR CHAR(4),
  BSNS_CODE VARCHAR(2),
  EVENT_CN VARCHAR(1000),
  EVENT_SVC_BGNDE CHAR(20),
  SVC_USE_NMPR_CO NUMERIC(10),
  CHARGER_NM VARCHAR(50),
  PRPARETG_CN VARCHAR(2500),
  FRST_REGIST_PNTTM TIMESTAMP,
  FRST_REGISTER_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  EVENT_SVC_ENDDE CHAR(20),
  EVENT_TY_CODE CHAR(1),
  EVENT_CONFM_AT CHAR(1),
  EVENT_CONFM_DE CHAR(20),
  PRIMARY KEY (EVENT_ID)
);

CREATE TABLE COMTNEVENTMANAGE (
  EVENT_ID CHAR(20) NOT NULL,
  EVENT_SE VARCHAR(2) NOT NULL,
  EVENT_NM VARCHAR(60) NOT NULL,
  EVENT_PURPS VARCHAR(200) NOT NULL,
  EVENT_BGNDE CHAR(20) NOT NULL,
  EVENT_ENDDE CHAR(20) NOT NULL,
  EVENT_AUSPC_INSTT_NM VARCHAR(60),
  EVENT_MNGT_INSTT_NM VARCHAR(60),
  EVENT_PLACE VARCHAR(200) NOT NULL,
  EVENT_CN VARCHAR(1000),
  CT_OCCRRNC_AT CHAR(1),
  PARTCPT_CT NUMERIC(16),
  PSNCPA NUMERIC(10) NOT NULL,
  REFRN_URL VARCHAR(1024),
  RCEPT_BGNDE CHAR(20) NOT NULL,
  RCEPT_ENDDE CHAR(20) NOT NULL,
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  PRIMARY KEY (EVENT_ID)
);

CREATE TABLE COMTNEXTRLHRINFO (
  EVENT_ID CHAR(20) NOT NULL,
  EXTRL_HR_ID CHAR(20) NOT NULL,
  SEXDSTN_CODE CHAR(1),
  EXTRL_HR_NM VARCHAR(60),
  OCCP_TY_CODE CHAR(1),
  PSITN_INSTT_NM VARCHAR(100),
  BRTHDY CHAR(20),
  AREA_NO VARCHAR(4),
  MIDDLE_TELNO VARCHAR(4),
  END_TELNO VARCHAR(4),
  EMAIL_ADRES VARCHAR(50),
  FRST_REGIST_PNTTM TIMESTAMP,
  FRST_REGISTER_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  PRIMARY KEY (EVENT_ID,EXTRL_HR_ID)
);

CREATE TABLE COMTNFAQINFO (
  FAQ_ID CHAR(20) NOT NULL,
  QESTN_SJ VARCHAR(255),
  QESTN_CN VARCHAR(2500),
  ANSWER_CN VARCHAR(2500),
  RDCNT NUMERIC(10),
  FRST_REGIST_PNTTM TIMESTAMP NOT NULL,
  FRST_REGISTER_ID VARCHAR(20) NOT NULL,
  LAST_UPDT_PNTTM TIMESTAMP NOT NULL,
  LAST_UPDUSR_ID VARCHAR(20) NOT NULL,
  ATCH_FILE_ID CHAR(20),
  QNA_PROCESS_STTUS_CODE CHAR(1),
  PRIMARY KEY (FAQ_ID)
);

CREATE TABLE COMTNFILE (
  ATCH_FILE_ID CHAR(20) NOT NULL,
  CREAT_DT TIMESTAMP NOT NULL,
  USE_AT CHAR(1),
  PRIMARY KEY (ATCH_FILE_ID)
);

CREATE TABLE COMTNFILEDETAIL (
  ATCH_FILE_ID CHAR(20) NOT NULL,
  FILE_SN NUMERIC(10) NOT NULL,
  FILE_STRE_COURS VARCHAR(2000) NOT NULL,
  STRE_FILE_NM VARCHAR(255) NOT NULL,
  ORIGNL_FILE_NM VARCHAR(255),
  FILE_EXTSN VARCHAR(20) NOT NULL,
  FILE_CN MEDIUMTEXT,
  FILE_SIZE NUMERIC(8),
  PRIMARY KEY (ATCH_FILE_ID,FILE_SN)
);

CREATE TABLE COMTNFILESYSMNTRNG (
  FILE_SYS_ID CHAR(20) NOT NULL,
  FILE_SYS_NM VARCHAR(60) NOT NULL,
  FILE_SYS_MANAGE_NM VARCHAR(255) NOT NULL,
  FILE_SYS_SIZE NUMERIC(8) NOT NULL,
  FILE_SYS_THRHLD NUMERIC(8) NOT NULL,
  FILE_SYS_USGQTY NUMERIC(8),
  MNGR_NM VARCHAR(60),
  MNGR_EMAIL_ADRES VARCHAR(50),
  MNTRNG_STTUS CHAR(2),
  CREAT_DT TIMESTAMP,
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  PRIMARY KEY (FILE_SYS_ID)
);

CREATE TABLE COMTNFILESYSMNTRNGLOGINFO (
  FILE_SYS_ID CHAR(20) NOT NULL,
  FILE_SYS_NM VARCHAR(60) NOT NULL,
  FILE_SYS_MANAGE_NM VARCHAR(255) NOT NULL,
  FILE_SYS_SIZE NUMERIC(8) NOT NULL,
  FILE_SYS_THRHLD NUMERIC(8) NOT NULL,
  FILE_SYS_USGQTY NUMERIC(8),
  MNTRNG_STTUS CHAR(2),
  LOG_INFO VARCHAR(2000),
  CREAT_DT TIMESTAMP,
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  LOG_ID CHAR(20) NOT NULL,
  PRIMARY KEY (FILE_SYS_ID,LOG_ID)
);

CREATE TABLE COMTNFXTRSMANAGE (
  FXTRS_CODE CHAR(14) NOT NULL,
  FXTRS_NM VARCHAR(100) NOT NULL,
  MAKR_NM VARCHAR(100),
  PRICE NUMERIC(16),
  PRIMARY KEY (FXTRS_CODE)
);

CREATE TABLE COMTNGNRLMBER (
  MBER_ID VARCHAR(20) NOT NULL,
  PASSWORD VARCHAR(200) NOT NULL,
  PASSWORD_HINT VARCHAR(100),
  PASSWORD_CNSR VARCHAR(100),
  IHIDNUM VARCHAR(200),
  MBER_NM VARCHAR(50) NOT NULL,
  ZIP VARCHAR(6) NOT NULL,
  ADRES VARCHAR(100) NOT NULL,
  AREA_NO VARCHAR(4) NOT NULL,
  MBER_STTUS VARCHAR(15),
  DETAIL_ADRES VARCHAR(100),
  END_TELNO VARCHAR(4) NOT NULL,
  MBTLNUM VARCHAR(20) NOT NULL,
  GROUP_ID CHAR(20),
  MBER_FXNUM VARCHAR(20),
  MBER_EMAIL_ADRES VARCHAR(50),
  MIDDLE_TELNO VARCHAR(4) NOT NULL,
  SBSCRB_DE TIMESTAMP,
  SEXDSTN_CODE CHAR(1),
  ESNTL_ID CHAR(20) NOT NULL,
  LOCK_AT CHAR(1),
  LOCK_CNT NUMERIC(3),
  LOCK_LAST_PNTTM TIMESTAMP,
  CHG_PWD_LAST_PNTTM TIMESTAMP,
  PRIMARY KEY (MBER_ID),
  ON DELETE SET
);

CREATE TABLE COMTNHPCMINFO (
  HPCM_ID CHAR(20) NOT NULL,
  HPCM_SE_CODE CHAR(1),
  HPCM_DFN VARCHAR(1000),
  HPCM_DC VARCHAR(2500),
  FRST_REGIST_PNTTM TIMESTAMP,
  FRST_REGISTER_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  PRIMARY KEY (HPCM_ID)
);

CREATE TABLE COMTNHTTPMON (
  SYS_ID VARCHAR(20) NOT NULL,
  SITE_URL VARCHAR(100),
  WEBSVC_KND VARCHAR(10),
  HTTP_STTUS_CODE VARCHAR(3),
  CREAT_DT TIMESTAMP,
  MNGR_NM VARCHAR(60),
  MNGR_EMAIL_ADRES VARCHAR(50),
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  DELETE_AT CHAR(1),
  PRIMARY KEY (SYS_ID)
);

CREATE TABLE COMTNINDVDLINFOPOLICY (
  INDVDL_INFO_POLICY_ID CHAR(20) NOT NULL,
  INDVDL_INFO_POLICY_CN VARCHAR(2500),
  INDVDL_INFO_POLICY_AGRE_AT CHAR(1),
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  INDVDL_INFO_POLICY_NM VARCHAR(255),
  PRIMARY KEY (INDVDL_INFO_POLICY_ID)
);

CREATE TABLE COMTNINDVDLPGECNTNTS (
  CNTNTS_ID VARCHAR(20) NOT NULL,
  CNTNTS_NM VARCHAR(100) NOT NULL,
  CNTC_URL VARCHAR(255) NOT NULL,
  CNTNTS_USE_AT CHAR(1) NOT NULL,
  CNTNTS_LINK_URL VARCHAR(1000),
  CNTNTS_DC VARCHAR(250),
  PRIMARY KEY (CNTNTS_ID)
);

CREATE TABLE COMTNINDVDLPGEESTBS (
  EMPLYR_ID VARCHAR(20) NOT NULL,
  UPEND_IMAGE VARCHAR(1024),
  TITLEBAR_COLOR CHAR(7),
  ALGN_MTHD CHAR(1),
  ALGN_CO NUMERIC(10),
  PRIMARY KEY (EMPLYR_ID)
);

CREATE TABLE COMTNINDVDLYRYCMANAGE (
  OCCRRNC_YEAR CHAR(4) NOT NULL,
  YRYC_OCCRRNC_CO NUMERIC(5,1),
  USE_YRYC_CO NUMERIC(5,1),
  REMNDR_YRYC_CO NUMERIC(5,1),
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  USER_ID VARCHAR(20) NOT NULL,
  PRIMARY KEY (OCCRRNC_YEAR,USER_ID)
);

CREATE TABLE COMTNINFRMLSANCTN (
  INFRML_SANCTN_ID CHAR(20) NOT NULL,
  JOB_SE_CODE CHAR(3) NOT NULL,
  APPLCNT_ID VARCHAR(20) NOT NULL,
  REQST_DE CHAR(20) NOT NULL,
  SANCTNER_ID VARCHAR(20) NOT NULL,
  CONFM_AT CHAR(1) NOT NULL,
  SANCTN_DT TIMESTAMP,
  RETURN_RESN VARCHAR(1000),
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  PRIMARY KEY (INFRML_SANCTN_ID)
);

CREATE TABLE COMTNINSTTCODE (
  INSTT_CODE CHAR(7) NOT NULL,
  ALL_INSTT_NM VARCHAR(255),
  LOWEST_INSTT_NM VARCHAR(100),
  INSTT_ABRV_NM VARCHAR(50),
  ODR CHAR(1),
  ORD CHAR(3),
  INSTT_ODR CHAR(2),
  UPPER_INSTT_CODE CHAR(7),
  BEST_INSTT_CODE CHAR(7),
  REPRSNT_INSTT_CODE CHAR(7),
  INSTT_TY_LCLAS VARCHAR(100),
  INSTT_TY_MLSFC VARCHAR(100),
  INSTT_TY_SCLAS VARCHAR(100),
  TELNO VARCHAR(20),
  FXNUM VARCHAR(20),
  CREAT_DE CHAR(20),
  ABL_DE CHAR(20),
  ABL_ENNC CHAR(1),
  CHANGE_DE CHAR(20),
  CHANGE_TIME VARCHAR(6),
  BSIS_DE CHAR(20),
  SORT_ORDR NUMERIC(8),
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  PRIMARY KEY (INSTT_CODE)
);

CREATE TABLE COMTNINSTTCODERECPTNLOG (
  OCCRRNC_DE CHAR(20) NOT NULL,
  INSTT_CODE CHAR(7) NOT NULL,
  OPERT_SN NUMERIC(10) NOT NULL,
  CHANGE_SE_CODE VARCHAR(2),
  PROCESS_SE VARCHAR(2),
  ETC_CODE CHAR(2),
  ALL_INSTT_NM VARCHAR(255),
  LOWEST_INSTT_NM VARCHAR(100),
  INSTT_ABRV_NM VARCHAR(50),
  ODR CHAR(1),
  ORD CHAR(3),
  INSTT_ODR CHAR(2),
  UPPER_INSTT_CODE CHAR(7),
  BEST_INSTT_CODE CHAR(7),
  REPRSNT_INSTT_CODE CHAR(7),
  INSTT_TY_LCLAS VARCHAR(100),
  INSTT_TY_MLSFC VARCHAR(100),
  INSTT_TY_SCLAS VARCHAR(100),
  TELNO VARCHAR(20),
  FXNUM VARCHAR(20),
  CREAT_DE CHAR(20),
  ABL_DE CHAR(20),
  ABL_ENNC CHAR(1),
  CHANGE_DE CHAR(20),
  CHANGE_TIME VARCHAR(6),
  BSIS_DE CHAR(20),
  SORT_ORDR NUMERIC(8),
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  PRIMARY KEY (OCCRRNC_DE,INSTT_CODE,OPERT_SN)
);

CREATE TABLE COMTNINTNETSVC (
  INTNET_SVC_ID CHAR(20) NOT NULL,
  INTNET_SVC_NM VARCHAR(20) NOT NULL,
  INTNET_SVC_DC VARCHAR(200),
  REFLCT_AT CHAR(1) NOT NULL,
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  PRIMARY KEY (INTNET_SVC_ID)
);

CREATE TABLE COMTNLEADERSCHDUL (
  SCHDUL_ID CHAR(20) NOT NULL,
  SCHDUL_SE CHAR(1),
  SCHDUL_NM VARCHAR(255) NOT NULL,
  SCHDUL_CN VARCHAR(2500) NOT NULL,
  SCHDUL_PLACE VARCHAR(255),
  LEADER_ID VARCHAR(20) NOT NULL,
  REPTIT_SE_CODE CHAR(1),
  SCHDUL_BGNDE CHAR(20),
  SCHDUL_ENDDE CHAR(20),
  SCHDUL_CHARGER_ID VARCHAR(20) NOT NULL,
  FRST_REGISTER_ID VARCHAR(20) NOT NULL,
  FRST_REGIST_PNTTM TIMESTAMP NOT NULL,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  PRIMARY KEY (SCHDUL_ID)
);

CREATE TABLE COMTNLEADERSCHDULDE (
  SCHDUL_ID CHAR(20) NOT NULL,
  SCHDUL_DE CHAR(8) NOT NULL,
  PRIMARY KEY (SCHDUL_ID,SCHDUL_DE)
);

CREATE TABLE COMTNLEADERSTTUS (
  LEADER_ID VARCHAR(20) NOT NULL,
  LEADER_STTUS CHAR(1) NOT NULL,
  FRST_REGIST_PNTTM TIMESTAMP,
  FRST_REGISTER_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  PRIMARY KEY (LEADER_ID)
);

CREATE TABLE COMTNLOGINLOG (
  LOG_ID CHAR(20) NOT NULL,
  CONECT_ID VARCHAR(20),
  CONECT_IP VARCHAR(23),
  CONECT_MTHD CHAR(4),
  ERROR_OCCRRNC_AT CHAR(1),
  ERROR_CODE CHAR(3),
  CREAT_DT TIMESTAMP,
  PRIMARY KEY (LOG_ID)
);

CREATE TABLE COMTNLOGINPOLICY (
  EMPLYR_ID VARCHAR(20) NOT NULL,
  IP_INFO VARCHAR(23) NOT NULL,
  DPLCT_PERM_AT CHAR(1) NOT NULL,
  LMTT_AT CHAR(1) NOT NULL,
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  PRIMARY KEY (EMPLYR_ID)
);

CREATE TABLE COMTNLOGINSCRINIMAGE (
  IMAGE_ID CHAR(20) NOT NULL,
  IMAGE_NM VARCHAR(20) NOT NULL,
  REFLCT_AT CHAR(1) NOT NULL,
  IMAGE VARCHAR(60) NOT NULL,
  IMAGE_DC VARCHAR(200),
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  IMAGE_FILE VARCHAR(60),
  PRIMARY KEY (IMAGE_ID)
);

CREATE TABLE COMTNMAINIMAGE (
  IMAGE_ID CHAR(20) NOT NULL,
  IMAGE_NM VARCHAR(20) NOT NULL,
  IMAGE VARCHAR(60) NOT NULL,
  IMAGE_DC VARCHAR(200),
  REFLCT_AT CHAR(1) NOT NULL,
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  IMAGE_FILE VARCHAR(60),
  PRIMARY KEY (IMAGE_ID)
);

CREATE TABLE COMTNMEMOREPRT (
  REPRT_SJ VARCHAR(255) NOT NULL,
  REPORT_DE CHAR(20) NOT NULL,
  WRTER_ID VARCHAR(20) NOT NULL,
  REPORTR_ID VARCHAR(20) NOT NULL,
  REPORT_CN VARCHAR(2500) NOT NULL,
  ATCH_FILE_ID CHAR(20),
  DRCT_MATTER VARCHAR(2500),
  DRCT_MATTER_REGIST_DT VARCHAR(14),
  REPORTR_INQIRE_DT VARCHAR(14),
  FRST_REGISTER_ID VARCHAR(20) NOT NULL,
  FRST_REGIST_PNTTM TIMESTAMP NOT NULL,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  REPRT_ID CHAR(6) NOT NULL,
  PRIMARY KEY (REPRT_ID)
);

CREATE TABLE COMTNMEMOTODO (
  TODO_ID CHAR(20) NOT NULL,
  TODO_SJ VARCHAR(255) NOT NULL,
  TODO_BEGIN_TIME VARCHAR(14) NOT NULL,
  TODO_END_TIME VARCHAR(14) NOT NULL,
  WRTER_ID VARCHAR(20) NOT NULL,
  TODO_CN VARCHAR(2500) NOT NULL,
  FRST_REGISTER_ID VARCHAR(20) NOT NULL,
  FRST_REGIST_PNTTM TIMESTAMP NOT NULL,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  PRIMARY KEY (TODO_ID)
);

CREATE TABLE COMTNMENUCREATDTLS (
  MENU_NO NUMERIC(20) NOT NULL,
  AUTHOR_CODE VARCHAR(30) NOT NULL,
  MAPNG_CREAT_ID VARCHAR(30),
  PRIMARY KEY (MENU_NO,AUTHOR_CODE),
  ON DELETE CASCADE,
  ON DELETE CASCADE
);

CREATE TABLE COMTNMENUINFO (
  MENU_NM VARCHAR(60) NOT NULL,
  PROGRM_FILE_NM VARCHAR(60) NOT NULL,
  MENU_NO NUMERIC(20) NOT NULL,
  UPPER_MENU_NO NUMERIC(20),
  MENU_ORDR NUMERIC(5) NOT NULL,
  MENU_DC VARCHAR(250),
  RELATE_IMAGE_PATH VARCHAR(100),
  RELATE_IMAGE_NM VARCHAR(60),
  PRIMARY KEY (MENU_NO),
  ON DELETE CASCADE,
  ON DELETE CASCADE
);

CREATE TABLE COMTNMTGINFO (
  MTG_ID CHAR(20) NOT NULL,
  MTG_NM VARCHAR(255),
  MTG_MTR_CN VARCHAR(1000),
  MTG_SN NUMERIC(10),
  MTG_CO NUMERIC(5),
  MTG_DE CHAR(20),
  MTG_PLACE VARCHAR(255),
  MTG_BEGIN_TM VARCHAR(14),
  MTG_END_TM VARCHAR(14),
  CLSDR_MTG_AT CHAR(1),
  READNG_BGNDE CHAR(20),
  READNG_AT CHAR(1),
  MTG_RESULT_CN VARCHAR(1000),
  MTG_RESULT_ENNC CHAR(1),
  ETC_MATTER VARCHAR(1000),
  MNGT_DEPT_ID VARCHAR(20),
  MNAER_ID VARCHAR(20),
  MNAER_DEPT_ID VARCHAR(20),
  MTG_AT CHAR(1),
  NONATDRN_CO NUMERIC(10),
  ATDRN_CO NUMERIC(10),
  FRST_REGIST_PNTTM TIMESTAMP,
  FRST_REGISTER_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  PRIMARY KEY (MTG_ID)
);

CREATE TABLE COMTNMTGPLACEFXTRS (
  MTGRUM_ID CHAR(20) NOT NULL,
  FXTRS_CODE CHAR(14) NOT NULL,
  QY NUMERIC(20) NOT NULL,
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  PRIMARY KEY (MTGRUM_ID,FXTRS_CODE)
);

CREATE TABLE COMTNMTGPLACEMANAGE (
  MTGRUM_ID CHAR(20) NOT NULL,
  MTGRUM_NM VARCHAR(255) NOT NULL,
  OPN_BEGIN_TM VARCHAR(6) NOT NULL,
  OPN_END_TM VARCHAR(6) NOT NULL,
  ACEPTNC_POSBL_NMPR NUMERIC(10) NOT NULL,
  LC_SE CHAR(5),
  LC_DETAIL VARCHAR(200),
  ATCH_FILE_ID CHAR(20),
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  PRIMARY KEY (MTGRUM_ID)
);

CREATE TABLE COMTNMTGPLACERESVE (
  RESVE_ID CHAR(20) NOT NULL,
  MTGRUM_ID CHAR(20) NOT NULL,
  MTG_SJ VARCHAR(100) NOT NULL,
  RSVCTM_ID VARCHAR(20) NOT NULL,
  RESVE_DE CHAR(8) NOT NULL,
  RESVE_BEGIN_TM VARCHAR(14) NOT NULL,
  RESVE_END_TM VARCHAR(14) NOT NULL,
  ATNDNC_NMPR NUMERIC(10),
  MTG_CN VARCHAR(2500),
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  PRIMARY KEY (RESVE_ID)
);

CREATE TABLE COMTNNCRD (
  NCRD_ID CHAR(20) NOT NULL,
  NCRD_TRGTER_ID VARCHAR(20),
  NM VARCHAR(50) NOT NULL,
  TELNO VARCHAR(20),
  NATION_NO VARCHAR(10),
  AREA_NO VARCHAR(4),
  MIDDLE_TELNO VARCHAR(4),
  END_TELNO VARCHAR(4),
  MBTLNUM VARCHAR(20),
  IDNTFC_NO VARCHAR(10),
  MIDDLE_MBTLNUM VARCHAR(4),
  END_MBTLNUM VARCHAR(4),
  EMAIL_ADRES VARCHAR(50),
  CMPNY_NM VARCHAR(60),
  DEPT_NM VARCHAR(60),
  ADRES VARCHAR(100),
  DETAIL_ADRES VARCHAR(100),
  OFCPS_NM VARCHAR(60),
  CLSF_NM VARCHAR(60),
  EXTRL_USER_AT CHAR(1),
  OTHBC_AT CHAR(1) NOT NULL,
  RM VARCHAR(2500),
  FRST_REGIST_PNTTM TIMESTAMP NOT NULL,
  FRST_REGISTER_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  PRIMARY KEY (NCRD_ID)
);

CREATE TABLE COMTNNCRDUSER (
  NCRD_ID CHAR(20) NOT NULL,
  REGIST_SE_CODE CHAR(6) NOT NULL,
  USE_AT CHAR(1) NOT NULL,
  CREAT_DT TIMESTAMP NOT NULL,
  EMPLYR_ID VARCHAR(20) NOT NULL,
  PRIMARY KEY (NCRD_ID,EMPLYR_ID)
);

CREATE TABLE COMTNNEWSINFO (
  NEWS_ID CHAR(20) NOT NULL,
  NEWS_SJ VARCHAR(100),
  NEWS_CN VARCHAR(2500),
  NEWS_ORIGIN VARCHAR(250),
  NTCE_AT CHAR(1),
  FRST_REGIST_PNTTM TIMESTAMP NOT NULL,
  FRST_REGISTER_ID VARCHAR(20) NOT NULL,
  LAST_UPDT_PNTTM TIMESTAMP NOT NULL,
  LAST_UPDUSR_ID VARCHAR(20) NOT NULL,
  NTCE_DE CHAR(20),
  ATCH_FILE_ID CHAR(20),
  PRIMARY KEY (NEWS_ID),
  ON DELETE SET
);

CREATE TABLE COMTNNOTE (
  NOTE_ID CHAR(20) NOT NULL,
  NOTE_SJ VARCHAR(255),
  NOTE_CN VARCHAR(4000),
  ATCH_FILE_ID CHAR(20),
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  PRIMARY KEY (NOTE_ID)
);

CREATE TABLE COMTNNOTERECPTN (
  NOTE_ID CHAR(20) NOT NULL,
  NOTE_TRNSMIT_ID CHAR(20) NOT NULL,
  NOTE_RECPTN_ID CHAR(20) NOT NULL,
  RCVER_ID CHAR(20),
  OPEN_YN CHAR(1),
  RECPTN_SE CHAR(1),
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  PRIMARY KEY (NOTE_ID,NOTE_TRNSMIT_ID,NOTE_RECPTN_ID)
);

CREATE TABLE COMTNNOTETRNSMIT (
  NOTE_ID CHAR(20) NOT NULL,
  NOTE_TRNSMIT_ID CHAR(20) NOT NULL,
  TRNSMITER_ID CHAR(20),
  DELETE_AT CHAR(8),
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  PRIMARY KEY (NOTE_ID,NOTE_TRNSMIT_ID)
);

CREATE TABLE COMTNNTFCINFO (
  NTCN_NO NUMERIC(20) NOT NULL,
  NTCN_SJ VARCHAR(60) NOT NULL,
  NTCN_CN VARCHAR(100) NOT NULL,
  NTCN_TM VARCHAR(14) NOT NULL,
  BH_NTCN_INTRVL VARCHAR(20) NOT NULL,
  FRST_REGIST_PNTTM TIMESTAMP NOT NULL,
  LAST_UPDT_PNTTM TIMESTAMP,
  FRST_REGISTER_ID VARCHAR(20) NOT NULL,
  LAST_UPDUSR_ID VARCHAR(20),
  PRIMARY KEY (NTCN_NO)
);

CREATE TABLE COMTNNTTSTATS (
  STATS_ID CHAR(18) NOT NULL,
  NTCE_CO NUMERIC(10),
  AVRG_RDCNT NUMERIC(10),
  TOP_RDCNT NUMERIC(10),
  MUMM_RDCNT NUMERIC(10),
  TOP_NTCR_ID VARCHAR(20),
  PRIMARY KEY (STATS_ID)
);

CREATE TABLE COMTNNTWRKINFO (
  NTWRK_ID CHAR(20) NOT NULL,
  NTWRK_IP VARCHAR(23),
  GTWY VARCHAR(23),
  SUBNET VARCHAR(23),
  DOMN_NM_SERVER VARCHAR(23),
  MANAGE_IEM CHAR(2),
  USER_NM VARCHAR(60),
  USE_AT CHAR(1),
  RGSDE TIMESTAMP,
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  PRIMARY KEY (NTWRK_ID)
);

CREATE TABLE COMTNNTWRKSVCMNTRNG (
  SYS_IP VARCHAR(23) NOT NULL,
  SYS_PORT NUMERIC(5) NOT NULL,
  SYS_NM VARCHAR(255) NOT NULL,
  MNGR_NM VARCHAR(60),
  MNGR_EMAIL_ADRES VARCHAR(50),
  MNTRNG_STTUS CHAR(2),
  CREAT_DT TIMESTAMP,
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20) NOT NULL,
  LAST_UPDT_PNTTM TIMESTAMP NOT NULL,
  PRIMARY KEY (SYS_IP,SYS_PORT)
);

CREATE TABLE COMTNNTWRKSVCMNTRNGLOGINFO (
  SYS_IP VARCHAR(23) NOT NULL,
  SYS_PORT NUMERIC(5) NOT NULL,
  SYS_NM VARCHAR(255) NOT NULL,
  MNTRNG_STTUS CHAR(2),
  LOG_INFO VARCHAR(2000),
  CREAT_DT TIMESTAMP,
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20) NOT NULL,
  LAST_UPDT_PNTTM TIMESTAMP NOT NULL,
  LOG_ID CHAR(20) NOT NULL,
  PRIMARY KEY (SYS_IP,SYS_PORT,LOG_ID)
);

CREATE TABLE COMTNONLINEMANUAL (
  ONLINE_MNL_ID CHAR(20) NOT NULL,
  ONLINE_MNL_SE_CODE CHAR(3),
  ONLINE_MNL_DFN MEDIUMTEXT,
  ONLINE_MNL_DC MEDIUMTEXT,
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  ONLINE_MNL_NM VARCHAR(255),
  PRIMARY KEY (ONLINE_MNL_ID)
);

CREATE TABLE COMTNONLINEPOLLIEM (
  POLL_IEM_NM VARCHAR(255),
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  POLL_IEM_ID CHAR(20) NOT NULL,
  POLL_ID CHAR(20) NOT NULL,
  PRIMARY KEY (POLL_ID,POLL_IEM_ID)
);

CREATE TABLE COMTNONLINEPOLLMANAGE (
  POLL_ID CHAR(20) NOT NULL,
  POLL_NM VARCHAR(255),
  POLL_BGNDE CHAR(10),
  POLL_ENDDE CHAR(10),
  POLL_KND CHAR(3),
  POLL_DSUSE_ENNC CHAR(1),
  POLL_ATMC_DSUSE_ENNC CHAR(1),
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  PRIMARY KEY (POLL_ID)
);

CREATE TABLE COMTNONLINEPOLLRESULT (
  POLL_RESULT_ID CHAR(20) NOT NULL,
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  POLL_IEM_ID CHAR(20) NOT NULL,
  POLL_ID CHAR(20) NOT NULL,
  PRIMARY KEY (POLL_RESULT_ID,POLL_IEM_ID,POLL_ID)
);

CREATE TABLE COMTNORGNZTINFO (
  ORGNZT_ID CHAR(20) NOT NULL,
  ORGNZT_NM VARCHAR(20) NOT NULL,
  ORGNZT_DC VARCHAR(100),
  PRIMARY KEY (ORGNZT_ID)
);

CREATE TABLE COMTNPOPUPMANAGE (
  POPUP_ID VARCHAR(20) NOT NULL,
  POPUP_SJ_NM VARCHAR(1024),
  FILE_URL VARCHAR(1024),
  POPUP_WIDTH_LC VARCHAR(20),
  POPUP_WIDTH_SIZE NUMERIC,
  NTCE_BGNDE CHAR(20),
  NTCE_ENDDE CHAR(20),
  STOPVEW_SETUP_AT CHAR(1),
  NTCE_AT CHAR(1),
  POPUP_VRTICL_LC VARCHAR(20),
  POPUP_VRTICL_SIZE NUMERIC,
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  PRIMARY KEY (POPUP_ID)
);

CREATE TABLE COMTNPRIVACYLOG (
  REQUST_ID VARCHAR(20) NOT NULL,
  INQIRE_DT TIMESTAMP NOT NULL,
  SRVC_NM VARCHAR(500),
  INQIRE_INFO VARCHAR(100),
  RQESTER_ID VARCHAR(20),
  RQESTER_IP VARCHAR(23),
  PRIMARY KEY (REQUST_ID)
);

CREATE TABLE COMTNPROCESSMON (
  PROCS_ID CHAR(20) NOT NULL,
  PROCS_NM VARCHAR(60),
  PROCS_STTUS VARCHAR(3),
  CREAT_DT TIMESTAMP,
  MNGR_NM VARCHAR(60),
  MNGR_EMAIL_ADRES VARCHAR(50),
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  PRIMARY KEY (PROCS_ID)
);

CREATE TABLE COMTNPROCESSMONLOGINFO (
  PROCS_ID CHAR(20) NOT NULL,
  PROCS_NM VARCHAR(60),
  PROCS_STTUS VARCHAR(3),
  CREAT_DT TIMESTAMP,
  LOG_INFO VARCHAR(2000),
  MNGR_NM VARCHAR(60),
  MNGR_EMAIL_ADRES VARCHAR(50),
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  LOG_ID CHAR(20) NOT NULL,
  PRIMARY KEY (PROCS_ID,LOG_ID)
);

CREATE TABLE COMTNPROGRMLIST (
  PROGRM_FILE_NM VARCHAR(60) NOT NULL,
  PROGRM_STRE_PATH VARCHAR(100) NOT NULL,
  PROGRM_KOREAN_NM VARCHAR(60),
  PROGRM_DC VARCHAR(200),
  URL VARCHAR(100) NOT NULL,
  PRIMARY KEY (PROGRM_FILE_NM)
);

CREATE TABLE COMTNPROXYINFO (
  PROXY_ID CHAR(20) NOT NULL,
  PROXY_NM VARCHAR(60),
  PROXY_IP VARCHAR(23),
  PROXY_PORT VARCHAR(10),
  TRGET_SVC_NM VARCHAR(255),
  SVC_DC VARCHAR(2000),
  SVC_IP VARCHAR(23),
  SVC_PORT VARCHAR(10),
  SVC_STTUS CHAR(2),
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  PRIMARY KEY (PROXY_ID)
);

CREATE TABLE COMTNPROXYLOGINFO (
  PROXY_ID CHAR(20) NOT NULL,
  CLNT_IP VARCHAR(23),
  CLNT_PORT VARCHAR(10),
  CONECT_TIME TIMESTAMP,
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  LOG_ID CHAR(20) NOT NULL,
  PRIMARY KEY (PROXY_ID,LOG_ID)
);

CREATE TABLE COMTNQAINFO (
  QA_ID CHAR(20) NOT NULL,
  QESTN_SJ VARCHAR(255),
  QESTN_CN VARCHAR(2500),
  WRITNG_DE CHAR(20),
  RDCNT NUMERIC(10),
  EMAIL_ADRES VARCHAR(50),
  FRST_REGIST_PNTTM TIMESTAMP,
  FRST_REGISTER_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  QNA_PROCESS_STTUS_CODE CHAR(1),
  WRTER_NM VARCHAR(20),
  ANSWER_CN VARCHAR(2500),
  WRITNG_PASSWORD VARCHAR(20),
  ANSWER_DE CHAR(20),
  EMAIL_ANSWER_AT CHAR(1),
  AREA_NO VARCHAR(4),
  MIDDLE_TELNO VARCHAR(4),
  END_TELNO VARCHAR(4),
  PRIMARY KEY (QA_ID)
);

CREATE TABLE COMTNQESTNRINFO (
  QUSTNR_TMPLAT_ID CHAR(20) NOT NULL,
  QESTNR_ID CHAR(20) NOT NULL,
  QUSTNR_SJ VARCHAR(255),
  QUSTNR_PURPS VARCHAR(1000),
  QUSTNR_WRITNG_GUIDANCE_CN VARCHAR(2000),
  QUSTNR_TRGET VARCHAR(1000),
  QUSTNR_BGNDE CHAR(20),
  QUSTNR_ENDDE CHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  FRST_REGISTER_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  PRIMARY KEY (QUSTNR_TMPLAT_ID,QESTNR_ID)
);

CREATE TABLE COMTNQUSTNRIEM (
  QUSTNR_TMPLAT_ID CHAR(20) NOT NULL,
  QESTNR_ID CHAR(20) NOT NULL,
  QUSTNR_QESITM_ID CHAR(20) NOT NULL,
  QUSTNR_IEM_ID VARCHAR(20) NOT NULL,
  IEM_SN NUMERIC(5),
  IEM_CN VARCHAR(1000),
  ETC_ANSWER_AT CHAR(1),
  FRST_REGIST_PNTTM TIMESTAMP,
  FRST_REGISTER_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  PRIMARY KEY (QUSTNR_TMPLAT_ID,QESTNR_ID,QUSTNR_QESITM_ID,QUSTNR_IEM_ID)
);

CREATE TABLE COMTNQUSTNRQESITM (
  QESTNR_ID CHAR(20) NOT NULL,
  QUSTNR_QESITM_ID CHAR(20) NOT NULL,
  QUSTNR_TMPLAT_ID CHAR(20) NOT NULL,
  QESTN_SN NUMERIC(10),
  QESTN_TY_CODE CHAR(1),
  QESTN_CN VARCHAR(2500),
  MXMM_CHOISE_CO NUMERIC(5),
  FRST_REGIST_PNTTM TIMESTAMP NOT NULL,
  FRST_REGISTER_ID VARCHAR(20) NOT NULL,
  LAST_UPDT_PNTTM TIMESTAMP NOT NULL,
  LAST_UPDUSR_ID VARCHAR(20) NOT NULL,
  PRIMARY KEY (QESTNR_ID,QUSTNR_QESITM_ID,QUSTNR_TMPLAT_ID)
);

CREATE TABLE COMTNQUSTNRRESPONDINFO (
  QUSTNR_TMPLAT_ID CHAR(20) NOT NULL,
  QESTNR_ID CHAR(20) NOT NULL,
  QUSTNR_RESPOND_ID CHAR(20) NOT NULL,
  SEXDSTN_CODE CHAR(1),
  OCCP_TY_CODE CHAR(1),
  RESPOND_NM VARCHAR(50),
  BRTHDY CHAR(20),
  AREA_NO VARCHAR(4),
  MIDDLE_TELNO VARCHAR(4),
  END_TELNO VARCHAR(4),
  FRST_REGIST_PNTTM TIMESTAMP,
  FRST_REGISTER_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  PRIMARY KEY (QUSTNR_TMPLAT_ID,QESTNR_ID,QUSTNR_RESPOND_ID)
);

CREATE TABLE COMTNQUSTNRRSPNSRESULT (
  QUSTNR_RSPNS_RESULT_ID CHAR(20) NOT NULL,
  QESTNR_ID CHAR(20) NOT NULL,
  QUSTNR_QESITM_ID CHAR(20) NOT NULL,
  QUSTNR_TMPLAT_ID CHAR(20) NOT NULL,
  RESPOND_ANSWER_CN VARCHAR(1000),
  ETC_ANSWER_CN VARCHAR(1000),
  RESPOND_NM VARCHAR(50),
  FRST_REGIST_PNTTM TIMESTAMP,
  FRST_REGISTER_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  QUSTNR_IEM_ID VARCHAR(20),
  PRIMARY KEY (QUSTNR_RSPNS_RESULT_ID,QESTNR_ID,QUSTNR_QESITM_ID,QUSTNR_TMPLAT_ID)
);

CREATE TABLE COMTNQUSTNRTMPLAT (
  QUSTNR_TMPLAT_ID CHAR(20) NOT NULL,
  QUSTNR_TMPLAT_TY VARCHAR(100),
  QUSTNR_TMPLAT_DC VARCHAR(2000),
  QUSTNR_TMPLAT_PATH_NM VARCHAR(100),
  FRST_REGIST_PNTTM TIMESTAMP,
  FRST_REGISTER_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  QUSTNR_TMPLAT_IMAGE_INFO LONGVARBINARY,
  PRIMARY KEY (QUSTNR_TMPLAT_ID)
);

CREATE TABLE COMTNRECENTSRCHWRD (
  SRCHWRD_MANAGE_ID CHAR(20) NOT NULL,
  RECENT_SRCHWRD_ID CHAR(20) NOT NULL,
  RECENT_SRCHWRD_NM VARCHAR(255),
  RECENT_SRCHWRD_CO NUMERIC(20),
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  PRIMARY KEY (RECENT_SRCHWRD_ID)
);

CREATE TABLE COMTNRECENTSRCHWRDMANAGE (
  SRCHWRD_MANAGE_ID CHAR(20) NOT NULL,
  SRCHWRD_MANAGE_NM VARCHAR(255),
  SRCHWRD_CONECT_URL VARCHAR(255),
  USER_SEARCH_AT CHAR(1),
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  PRIMARY KEY (SRCHWRD_MANAGE_ID)
);

CREATE TABLE COMTNRECOMENDSITEINFO (
  RECOMEND_SITE_ID CHAR(20) NOT NULL,
  RECOMEND_SITE_NM VARCHAR(100),
  RECOMEND_SITE_URL VARCHAR(255),
  RECOMEND_SITE_DC VARCHAR(1000),
  RECOMEND_RESN_CN VARCHAR(1000),
  RECOMEND_CONFM_AT CHAR(1),
  CONFM_DE CHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  FRST_REGISTER_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  PRIMARY KEY (RECOMEND_SITE_ID)
);

CREATE TABLE COMTNREPRTSTATS (
  REPRT_ID CHAR(6) NOT NULL,
  REPRT_NM VARCHAR(20) NOT NULL,
  REPRT_STTUS CHAR(2) NOT NULL,
  FRST_REGISTER_ID VARCHAR(20) NOT NULL,
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  REPRT_TY CHAR(2),
  PRIMARY KEY (REPRT_ID)
);

CREATE TABLE COMTNRESTDE (
  RESTDE_NO NUMERIC(6) NOT NULL,
  RESTDE CHAR(8),
  RESTDE_NM VARCHAR(60),
  RESTDE_DC VARCHAR(200),
  RESTDE_SE_CODE VARCHAR(2),
  FRST_REGIST_PNTTM TIMESTAMP,
  FRST_REGISTER_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  PRIMARY KEY (RESTDE_NO)
);

CREATE TABLE COMTNROLEINFO (
  ROLE_CODE VARCHAR(50) NOT NULL,
  ROLE_NM VARCHAR(60) NOT NULL,
  ROLE_PTTRN VARCHAR(300),
  ROLE_DC VARCHAR(200),
  ROLE_TY VARCHAR(80),
  ROLE_SORT VARCHAR(10),
  ROLE_CREAT_DE CHAR(20) NOT NULL,
  PRIMARY KEY (ROLE_CODE)
);

CREATE TABLE COMTNROLES_HIERARCHY (
  PARNTS_ROLE VARCHAR(30) NOT NULL,
  CHLDRN_ROLE VARCHAR(30) NOT NULL,
  PRIMARY KEY (PARNTS_ROLE,CHLDRN_ROLE),
  ON DELETE CASCADE,
  ON DELETE CASCADE
);

CREATE TABLE COMTNROUGHMAP (
  ROUGHMAP_ID VARCHAR(75) NOT NULL,
  ROUGHMAPSJ VARCHAR(75) NOT NULL,
  ROUGHMAPADDRESS VARCHAR(200),
  LA VARCHAR(48),
  LO VARCHAR(48),
  MARKERLA VARCHAR(48),
  MARKERLO VARCHAR(48),
  INFOWINDOW VARCHAR(20),
  ZOOMLEVEL VARCHAR(10),
  FRST_REGIST_PNTTM TIMESTAMP,
  FRST_REGISTER_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20)
);

CREATE TABLE COMTNRSS (
  RSS_ID CHAR(20) NOT NULL,
  TRGET_SVC_NM VARCHAR(255) NOT NULL,
  TRGET_SVC_TABLE VARCHAR(255) NOT NULL,
  TRGET_SVC_LIST_CO NUMERIC(5) NOT NULL,
  HDER_TITLE VARCHAR(255) NOT NULL,
  HDER_LINK VARCHAR(255) NOT NULL,
  HDER_DC VARCHAR(4000) NOT NULL,
  HDER_TAG VARCHAR(255),
  HDER_ETC VARCHAR(250),
  BDT_TITLE VARCHAR(255),
  BDT_LINK VARCHAR(255),
  BDT_DC VARCHAR(4000),
  BDT_TAG VARCHAR(255),
  BDT_ETC_TAG VARCHAR(255),
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  PRIMARY KEY (RSS_ID)
);

CREATE TABLE COMTNRWARDMANAGE (
  RWARD_ID CHAR(20) NOT NULL,
  RWARDWNR_ID VARCHAR(20) NOT NULL,
  RWARD_CODE CHAR(2) NOT NULL,
  RWARD_DE CHAR(20) NOT NULL,
  RWARD_NM VARCHAR(255) NOT NULL,
  PBLEN_CN VARCHAR(1000),
  SANCTNER_ID VARCHAR(20) NOT NULL,
  CONFM_AT CHAR(1),
  SANCTN_DT TIMESTAMP,
  RETURN_RESN VARCHAR(1000),
  ATCH_FILE_ID CHAR(20),
  INFRML_SANCTN_ID CHAR(20),
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  PRIMARY KEY (RWARD_ID)
);

CREATE TABLE COMTNSCHDULINFO (
  SCHDUL_ID CHAR(20) NOT NULL,
  SCHDUL_SE CHAR(1),
  SCHDUL_DEPT_ID VARCHAR(20),
  SCHDUL_KND_CODE CHAR(1),
  SCHDUL_BGNDE CHAR(20),
  SCHDUL_ENDDE CHAR(20),
  SCHDUL_NM VARCHAR(255),
  SCHDUL_CN VARCHAR(2500),
  SCHDUL_PLACE VARCHAR(255),
  SCHDUL_IPCR_CODE CHAR(1),
  SCHDUL_CHARGER_ID VARCHAR(20),
  ATCH_FILE_ID CHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  FRST_REGISTER_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  REPTIT_SE_CODE CHAR(1),
  PRIMARY KEY (SCHDUL_ID)
);

CREATE TABLE COMTNSCRAP (
  SCRAP_ID CHAR(20) NOT NULL,
  NTT_ID NUMERIC(20) NOT NULL,
  BBS_ID CHAR(30) NOT NULL,
  SCRAP_NM VARCHAR(100) NOT NULL,
  USE_AT CHAR(1) NOT NULL,
  FRST_REGIST_PNTTM TIMESTAMP NOT NULL,
  LAST_UPDT_PNTTM TIMESTAMP,
  FRST_REGISTER_ID VARCHAR(20) NOT NULL,
  LAST_UPDUSR_ID VARCHAR(20),
  PRIMARY KEY (SCRAP_ID)
);

CREATE TABLE COMTNSERVEREQPMNINFO (
  SERVER_EQPMN_ID VARCHAR(20) NOT NULL,
  SERVER_EQPMN_NM VARCHAR(60),
  SERVER_EQPMN_IP VARCHAR(23),
  SERVER_EQPMN_MNGR VARCHAR(60),
  MNGR_EMAIL_ADRES VARCHAR(50),
  OPERSYSM_INFO VARCHAR(2000),
  CPU_INFO VARCHAR(2000),
  MORY_INFO VARCHAR(2000),
  HDDISK CHAR(18),
  ETC_INFO VARCHAR(250),
  RGSDE TIMESTAMP,
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  PRIMARY KEY (SERVER_EQPMN_ID)
);

CREATE TABLE COMTNSERVEREQPMNRELATE (
  SERVER_EQPMN_ID VARCHAR(20) NOT NULL,
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  SERVER_ID CHAR(20) NOT NULL,
  PRIMARY KEY (SERVER_EQPMN_ID,SERVER_ID)
);

CREATE TABLE COMTNSERVERINFO (
  SERVER_ID CHAR(20) NOT NULL,
  SERVER_NM VARCHAR(60),
  SERVER_KND CHAR(2),
  RGSDE TIMESTAMP,
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  PRIMARY KEY (SERVER_ID)
);

CREATE TABLE COMTNSERVERRESRCELOGINFO (
  SERVER_EQPMN_ID VARCHAR(20) NOT NULL,
  CPU_USE_RT NUMERIC(3),
  MORY_USE_RT NUMERIC(3),
  SVC_STTUS CHAR(2),
  LOG_INFO VARCHAR(2000),
  CREAT_DT TIMESTAMP,
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  SERVER_ID CHAR(20) NOT NULL,
  LAST_UPDT_PNTTM TIMESTAMP,
  LOG_ID CHAR(20) NOT NULL,
  PRIMARY KEY (SERVER_EQPMN_ID,SERVER_ID,LOG_ID)
);

CREATE TABLE COMTNSITELIST (
  SITE_ID CHAR(20) NOT NULL,
  SITE_NM VARCHAR(100),
  SITE_URL VARCHAR(100),
  SITE_DC VARCHAR(1000),
  SITE_THEMA_CL_CODE VARCHAR(2),
  ACTVTY_AT CHAR(1),
  USE_AT CHAR(1),
  FRST_REGIST_PNTTM TIMESTAMP,
  FRST_REGISTER_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  PRIMARY KEY (SITE_ID)
);

CREATE TABLE COMTNSITEMAP (
  MAPNG_CREAT_ID VARCHAR(30) NOT NULL,
  CREATR_ID VARCHAR(20) NOT NULL,
  MAPNG_FILE_NM VARCHAR(60) NOT NULL,
  MAPNG_FILE_PATH VARCHAR(100) NOT NULL,
  PRIMARY KEY (MAPNG_CREAT_ID)
);

CREATE TABLE COMTNSMS (
  SMS_ID CHAR(20) NOT NULL,
  TRNSMIS_TELNO VARCHAR(12) NOT NULL,
  TRNSMIS_CN VARCHAR(80) NOT NULL,
  FRST_REGIST_PNTTM TIMESTAMP NOT NULL,
  FRST_REGISTER_ID VARCHAR(20) NOT NULL,
  PRIMARY KEY (SMS_ID)
);

CREATE TABLE COMTNSMSRECPTN (
  SMS_ID CHAR(20) NOT NULL,
  RECPTN_TELNO VARCHAR(12) NOT NULL,
  RESULT_CODE VARCHAR(4),
  RESULT_MSSAGE VARCHAR(4000),
  PRIMARY KEY (SMS_ID,RECPTN_TELNO)
);

CREATE TABLE COMTNSTPLATINFO (
  USE_STPLAT_ID CHAR(20) NOT NULL,
  USE_STPLAT_NM VARCHAR(100),
  USE_STPLAT_CN MEDIUMTEXT,
  INFO_PROVD_AGRE_CN MEDIUMTEXT,
  FRST_REGIST_PNTTM TIMESTAMP,
  FRST_REGISTER_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  PRIMARY KEY (USE_STPLAT_ID)
);

CREATE TABLE COMTNSYNCHRNSERVERINFO (
  SERVER_ID CHAR(20) NOT NULL,
  SERVER_NM VARCHAR(60),
  SERVER_IP VARCHAR(23),
  SERVER_PORT VARCHAR(10),
  FTP_ID VARCHAR(20),
  FTP_PASSWORD VARCHAR(20),
  SYNCHRN_LC VARCHAR(255),
  REFLCT_AT CHAR(1),
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  PRIMARY KEY (SERVER_ID)
);

CREATE TABLE COMTNSYSLOG (
  REQUST_ID VARCHAR(20) NOT NULL,
  JOB_SE_CODE CHAR(3),
  INSTT_CODE CHAR(7),
  OCCRRNC_DE TIMESTAMP,
  RQESTER_IP VARCHAR(23),
  RQESTER_ID VARCHAR(20),
  TRGET_MENU_NM VARCHAR(255),
  SVC_NM VARCHAR(255),
  METHOD_NM VARCHAR(60),
  PROCESS_SE_CODE CHAR(3),
  PROCESS_CO NUMERIC(10),
  PROCESS_TIME VARCHAR(14),
  RSPNS_CODE CHAR(3),
  ERROR_SE CHAR(1),
  ERROR_CO NUMERIC(10),
  ERROR_CODE CHAR(3),
  PRIMARY KEY (REQUST_ID)
);

CREATE TABLE COMTNSYSTEMCNTC (
  CNTC_ID CHAR(8) NOT NULL,
  CNTC_NM VARCHAR(100),
  PROVD_INSTT_ID CHAR(8),
  PROVD_SYS_ID CHAR(8),
  PROVD_SVC_ID CHAR(8),
  REQUST_INSTT_ID CHAR(8),
  REQUST_SYS_ID CHAR(8),
  CONFM_AT CHAR(1),
  USE_AT CHAR(1),
  VALID_BGNDE CHAR(20),
  VALID_ENDDE CHAR(20),
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  CNTC_TY VARCHAR(60),
  PRIMARY KEY (CNTC_ID)
);

CREATE TABLE COMTNTMPLATINFO (
  TMPLAT_ID CHAR(20) NOT NULL,
  TMPLAT_NM VARCHAR(255),
  TMPLAT_COURS VARCHAR(2000),
  USE_AT CHAR(1),
  TMPLAT_SE_CODE CHAR(6),
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  PRIMARY KEY (TMPLAT_ID)
);

CREATE TABLE COMTNTROBLINFO (
  TROBL_ID CHAR(20) NOT NULL,
  TROBL_NM VARCHAR(60),
  TROBL_KND CHAR(2),
  TROBL_DC VARCHAR(2000),
  TROBL_OCCRRNC_TIME VARCHAR(14),
  TROBL_RQESTER_NM VARCHAR(60),
  TROBL_REQUST_TIME VARCHAR(14),
  TROBL_PROCESS_RESULT VARCHAR(2000),
  TROBL_OPETR_NM VARCHAR(60),
  TROBL_PROCESS_TIME VARCHAR(14),
  PROCESS_STTUS CHAR(1),
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  PRIMARY KEY (TROBL_ID)
);

CREATE TABLE COMTNTRSMRCVLOG (
  REQUST_ID VARCHAR(20) NOT NULL,
  OCCRRNC_DE CHAR(20),
  TRSMRCV_SE_CODE CHAR(3),
  CNTC_ID CHAR(8),
  PROVD_INSTT_ID CHAR(8),
  PROVD_SYS_ID CHAR(8),
  PROVD_SVC_ID CHAR(8),
  REQUST_INSTT_ID CHAR(8),
  REQUST_SYS_ID CHAR(8),
  REQUST_TRNSMIT_TM VARCHAR(14),
  REQUST_RECPTN_TM VARCHAR(14),
  RSPNS_TRNSMIT_TM VARCHAR(14),
  RSPNS_RECPTN_TM VARCHAR(14),
  RESULT_CODE VARCHAR(4),
  RESULT_MSSAGE VARCHAR(4000),
  FRST_REGIST_PNTTM TIMESTAMP,
  RQESTER_ID VARCHAR(20),
  PRIMARY KEY (REQUST_ID)
);

CREATE TABLE COMTNTRSMRCVMNTRNG (
  CNTC_ID CHAR(8) NOT NULL,
  TEST_CLASS_NM VARCHAR(255),
  MNGR_NM VARCHAR(60),
  MNGR_EMAIL_ADRES VARCHAR(50),
  MNTRNG_STTUS CHAR(2),
  CREAT_DT TIMESTAMP,
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP NOT NULL,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP NOT NULL,
  PRIMARY KEY (CNTC_ID)
);

CREATE TABLE COMTNTWITTER (
  USER_ID VARCHAR(20) NOT NULL,
  CNSMR_KEY VARCHAR(50) NOT NULL,
  CNSMR_SECRET VARCHAR(50) NOT NULL,
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  PRIMARY KEY (USER_ID)
);

CREATE TABLE COMTNUNITYLINK (
  UNITY_LINK_ID CHAR(20) NOT NULL,
  UNITY_LINK_GROUP VARCHAR(255),
  UNITY_LINK_NM VARCHAR(255),
  UNITY_LINK_URL VARCHAR(255),
  UNITY_LINK_DC VARCHAR(2500),
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  UNITY_LINK_SE_CODE CHAR(3),
  PRIMARY KEY (UNITY_LINK_ID)
);

CREATE TABLE COMTNUSERABSNCE (
  EMPLYR_ID VARCHAR(20) NOT NULL,
  USER_ABSNCE_AT CHAR(1) NOT NULL,
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  PRIMARY KEY (EMPLYR_ID)
);

CREATE TABLE COMTNUSERLOG (
  OCCRRNC_DE CHAR(8) NOT NULL,
  RQESTER_ID VARCHAR(20) NOT NULL,
  SVC_NM VARCHAR(255) NOT NULL,
  METHOD_NM VARCHAR(60) NOT NULL,
  CREAT_CO NUMERIC(10),
  UPDT_CO NUMERIC(10),
  RDCNT NUMERIC(10),
  DELETE_CO NUMERIC(10),
  OUTPT_CO NUMERIC(10),
  ERROR_CO NUMERIC(10),
  PRIMARY KEY (OCCRRNC_DE,RQESTER_ID,SVC_NM,METHOD_NM)
);

CREATE TABLE COMTNVCATNMANAGE (
  APPLCNT_ID VARCHAR(20) NOT NULL,
  VCATN_SE CHAR(2) NOT NULL,
  BGNDE CHAR(8) NOT NULL,
  ENDDE CHAR(8) NOT NULL,
  VCATN_RESN VARCHAR(200) NOT NULL,
  REQST_DE CHAR(20) NOT NULL,
  OCCRRNC_YEAR CHAR(4),
  SANCTNER_ID VARCHAR(20),
  CONFM_AT CHAR(1),
  SANCTN_DT TIMESTAMP,
  RETURN_RESN VARCHAR(1000),
  INFRML_SANCTN_ID CHAR(20),
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  NOON_SE CHAR(1),
  PRIMARY KEY (APPLCNT_ID,VCATN_SE,BGNDE,ENDDE)
);

CREATE TABLE COMTNWEBLOG (
  REQUST_ID VARCHAR(20) NOT NULL,
  OCCRRNC_DE TIMESTAMP,
  URL VARCHAR(200),
  RQESTER_ID VARCHAR(20),
  RQESTER_IP VARCHAR(23),
  PRIMARY KEY (REQUST_ID)
);

CREATE TABLE COMTNWIKIBKMK (
  WIKI_BKMK_ID CHAR(20) NOT NULL,
  USER_ID VARCHAR(20) NOT NULL,
  WIKI_BKMK_NM VARCHAR(1000) NOT NULL,
  FRST_REGISTER_ID VARCHAR(20),
  FRST_REGIST_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  PRIMARY KEY (WIKI_BKMK_ID,USER_ID)
);

CREATE TABLE COMTNWIKMNTHNGREPRT (
  REPRT_ID CHAR(6) NOT NULL,
  REPRT_SE CHAR(1) NOT NULL,
  REPRT_SJ VARCHAR(255) NOT NULL,
  REPORT_DE CHAR(20) NOT NULL,
  WRTER_ID VARCHAR(20) NOT NULL,
  REPORTR_ID VARCHAR(20) NOT NULL,
  REPORT_BGNDE CHAR(20) NOT NULL,
  REPORT_ENDDE CHAR(20) NOT NULL,
  THSWIK_REPORT_CN MEDIUMTEXT NOT NULL,
  NEXTWIK_REPORT_CN MEDIUMTEXT NOT NULL,
  PARTCLR_MATTER VARCHAR(2500),
  ATCH_FILE_ID CHAR(20),
  CONFM_DT VARCHAR(14),
  FRST_REGISTER_ID VARCHAR(20) NOT NULL,
  FRST_REGIST_PNTTM TIMESTAMP NOT NULL,
  LAST_UPDUSR_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  PRIMARY KEY (REPRT_ID)
);

CREATE TABLE COMTNWORDDICARYINFO (
  WORD_ID CHAR(20) NOT NULL,
  WORD_NM VARCHAR(255),
  ENG_NM VARCHAR(60),
  WORD_DC VARCHAR(4000),
  SYNONM VARCHAR(100),
  FRST_REGIST_PNTTM TIMESTAMP,
  FRST_REGISTER_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  PRIMARY KEY (WORD_ID)
);

CREATE TABLE COMTRDNMADRZIP (
  RDMN_CODE VARCHAR(12) NOT NULL,
  SN NUMERIC(10) NOT NULL,
  CTPRVN_NM VARCHAR(20),
  SIGNGU_NM VARCHAR(20),
  RDMN VARCHAR(60),
  BDNBR_MNNM VARCHAR(5),
  BDNBR_SLNO VARCHAR(5),
  BULD_NM VARCHAR(60),
  DETAIL_BULD_NM VARCHAR(60),
  ZIP VARCHAR(6) NOT NULL,
  FRST_REGIST_PNTTM TIMESTAMP,
  FRST_REGISTER_ID VARCHAR(20),
  LAST_UPDT_PNTTM TIMESTAMP,
  LAST_UPDUSR_ID VARCHAR(20),
  PRIMARY KEY (SN)
);

CREATE TABLE COMTSBBSSUMMARY (
  OCCRRNC_DE CHAR(20) NOT NULL,
  STATS_SE VARCHAR(10) NOT NULL,
  DETAIL_STATS_SE VARCHAR(10) NOT NULL,
  CREAT_CO NUMERIC(10),
  TOT_RDCNT NUMERIC(10),
  AVRG_RDCNT NUMERIC(10),
  TOP_INQIRE_BBSCTT_ID VARCHAR(20),
  MUMM_INQIRE_BBSCTT_ID VARCHAR(20),
  TOP_NTCR_ID VARCHAR(20),
  PRIMARY KEY (OCCRRNC_DE,STATS_SE,DETAIL_STATS_SE)
);

CREATE TABLE COMTSSYSLOGSUMMARY (
  OCCRRNC_DE CHAR(8) NOT NULL,
  SVC_NM VARCHAR(255) NOT NULL,
  METHOD_NM VARCHAR(60) NOT NULL,
  CREAT_CO NUMERIC(10),
  UPDT_CO NUMERIC(10),
  RDCNT NUMERIC(10),
  DELETE_CO NUMERIC(10),
  OUTPT_CO NUMERIC(10),
  ERROR_CO NUMERIC(10),
  PRIMARY KEY (OCCRRNC_DE,SVC_NM,METHOD_NM)
);

CREATE TABLE COMTSTRSMRCVLOGSUMMARY (
  OCCRRNC_DE CHAR(20) NOT NULL,
  TRSMRCV_SE_CODE CHAR(3) NOT NULL,
  PROVD_INSTT_ID CHAR(8) NOT NULL,
  PROVD_SYS_ID CHAR(8) NOT NULL,
  PROVD_SVC_ID CHAR(8) NOT NULL,
  REQUST_INSTT_ID CHAR(8) NOT NULL,
  REQUST_SYS_ID CHAR(8) NOT NULL,
  RDCNT NUMERIC(10),
  ERROR_CO NUMERIC(10),
  PRIMARY KEY (OCCRRNC_DE,TRSMRCV_SE_CODE,PROVD_INSTT_ID,PROVD_SYS_ID,PROVD_SVC_ID,REQUST_INSTT_ID,REQUST_SYS_ID)
);

CREATE TABLE COMTSUSERSUMMARY (
  OCCRRNC_DE CHAR(20) NOT NULL,
  STATS_SE VARCHAR(10) NOT NULL,
  DETAIL_STATS_SE VARCHAR(10) NOT NULL,
  USER_CO NUMERIC(10),
  PRIMARY KEY (OCCRRNC_DE,STATS_SE,DETAIL_STATS_SE)
);

CREATE TABLE COMTSWEBLOGSUMMARY (
  OCCRRNC_DE CHAR(8) NOT NULL,
  URL VARCHAR(200) NOT NULL,
  RDCNT NUMERIC(10),
  PRIMARY KEY (OCCRRNC_DE,URL)
);

CREATE TABLE IMGTEMP (
  ORGNZT_CODE VARCHAR(10) NOT NULL,
  ERNCSL_SE VARCHAR(2) NOT NULL,
  IMAGE_INFO LONGVARBINARY NOT NULL,
  IMAGE_TY VARCHAR(20),
  PRIMARY KEY (ORGNZT_CODE,ERNCSL_SE)
);


-- ============================================================
-- 더미데이터(DEMO) — 외부연동/배치가 필요한 컴포넌트의 1사이클 시연용 샘플
-- 실제 운영에서는 SMTP/SMS게이트웨이/통계배치 연동으로 채워집니다.
-- ============================================================
INSERT INTO COMTHEMAILDSPTCHMANAGE(MSSAGE_ID,EMAIL_CN,SNDR,RCVER,SJ,SNDNG_RESULT_CODE,DSPTCH_DT) VALUES ('MAIL_DEMO_001','[더미] 공통컴포넌트 안내 메일입니다.','admin@example.go.kr','user1@example.go.kr','[더미] 시스템 점검 안내','S','2026-06-30 10:00:00');
INSERT INTO COMTHEMAILDSPTCHMANAGE(MSSAGE_ID,EMAIL_CN,SNDR,RCVER,SJ,SNDNG_RESULT_CODE,DSPTCH_DT) VALUES ('MAIL_DEMO_002','[더미] 뉴스레터 발송 예시','admin@example.go.kr','user2@example.go.kr','[더미] 7월 뉴스레터','F','2026-06-30 11:00:00');
INSERT INTO COMTNSMS(SMS_ID,TRNSMIS_TELNO,RECPTN_TELNO,TRNSMIS_CN,FRST_REGISTER_ID,FRST_REGIST_PNTTM) VALUES ('SMS_DEMO_001','021234567','01011112222','[더미] 인증번호는 123456 입니다.','admin','2026-06-30 09:30:00');
INSERT INTO COMTNSMS(SMS_ID,TRNSMIS_TELNO,RECPTN_TELNO,TRNSMIS_CN,FRST_REGISTER_ID,FRST_REGIST_PNTTM) VALUES ('SMS_DEMO_002','021234567','01033334444','[더미] 민원이 접수되었습니다.','admin','2026-06-30 09:45:00');
INSERT INTO COMTNSCRAP(SCRAP_ID,NTT_ID,BBS_ID,SCRAP_NM,USE_AT,FRST_REGISTER_ID,FRST_REGIST_PNTTM) VALUES ('SCRAP_DEMO_01',1,'BBSMSTR_AAAAAAAAAAAA','[더미] 공지사항 스크랩','Y','USRCNFRM_00000000000','2026-06-28 14:00:00');
INSERT INTO COMTNSCRAP(SCRAP_ID,NTT_ID,BBS_ID,SCRAP_NM,USE_AT,FRST_REGISTER_ID,FRST_REGIST_PNTTM) VALUES ('SCRAP_DEMO_02',2,'BBSMSTR_AAAAAAAAAAAA','[더미] 갤러리 스크랩','Y','USRCNFRM_00000000000','2026-06-29 15:00:00');
INSERT INTO COMTSBBSSUMMARY(OCCRRNC_DE,STATS_SE,DETAIL_STATS_SE,CREAT_CO,TOT_RDCNT,AVRG_RDCNT) VALUES ('20260630','D','BBS',12,340,28);
INSERT INTO COMTSBBSSUMMARY(OCCRRNC_DE,STATS_SE,DETAIL_STATS_SE,CREAT_CO,TOT_RDCNT,AVRG_RDCNT) VALUES ('20260629','D','BBS',9,270,30);

-- 더미(DEMO) 추가분: 블로그 / 데이터활용통계 / 웹로그통계
INSERT INTO COMTNBLOG(BLOG_ID,BLOG_NM,BLOG_INTRCN,USE_AT,FRST_REGISTER_ID,FRST_REGIST_PNTTM) VALUES ('BLOG_DEMO_001','[더미] 정보화 소식 블로그','정보화 사업 소식을 전하는 블로그입니다.','Y','USRCNFRM_00000000000','2026-05-10 09:00:00');
INSERT INTO COMTNBLOG(BLOG_ID,BLOG_NM,BLOG_INTRCN,USE_AT,FRST_REGISTER_ID,FRST_REGIST_PNTTM) VALUES ('BLOG_DEMO_002','[더미] 개발팀 기술 블로그','공통컴포넌트 개발 노하우 공유','Y','USRCNFRM_00000000000','2026-05-12 10:00:00');
INSERT INTO COMTNDTAUSESTATS(DTA_USE_STATS_ID,BBS_ID,NTT_ID,ATCH_FILE_ID,FILE_SN,FRST_REGISTER_ID,FRST_REGIST_PNTTM) VALUES ('DUS_DEMO_001','BBSMSTR_AAAAAAAAAAAA',1,'FILE_000001',1,'USRCNFRM_00000000000','2026-06-28 11:00:00');
INSERT INTO COMTNDTAUSESTATS(DTA_USE_STATS_ID,BBS_ID,NTT_ID,ATCH_FILE_ID,FILE_SN,FRST_REGISTER_ID,FRST_REGIST_PNTTM) VALUES ('DUS_DEMO_002','BBSMSTR_AAAAAAAAAAAA',2,'FILE_000002',1,'USRCNFRM_00000000000','2026-06-29 13:00:00');
INSERT INTO COMTSWEBLOGSUMMARY(OCCRRNC_DE,URL,RDCNT) VALUES ('20260630','/cop/bbs/selectBoardList.do',1240);
INSERT INTO COMTSWEBLOGSUMMARY(OCCRRNC_DE,URL,RDCNT) VALUES ('20260630','/examples',860);

-- 갭 보완 시드(일기/서버장비/연계시스템/게시글통계)
INSERT INTO COMTNDIARYINFO(SCHDUL_ID,DIARY_ID,DIARY_PROGRSRT,DIARY_NM,DRCT_MATTER,PARTCLR_MATTER,FRST_REGISTER_ID,FRST_REGIST_PNTTM) VALUES ('SCHDUL_0000000001','DIARY_DEMO_01',80,'[더미] 6/30 업무일지','정보화 전략 검토 지시','특이사항 없음','USRCNFRM_00000000000','2026-06-30 18:00:00');
INSERT INTO COMTNDIARYINFO(SCHDUL_ID,DIARY_ID,DIARY_PROGRSRT,DIARY_NM,DRCT_MATTER,PARTCLR_MATTER,FRST_REGISTER_ID,FRST_REGIST_PNTTM) VALUES ('SCHDUL_0000000002','DIARY_DEMO_02',50,'[더미] 7/1 업무일지','교육자료 준비','일부 지연','USRCNFRM_00000000000','2026-07-01 18:00:00');
INSERT INTO COMTNSERVEREQPMNINFO(SERVER_EQPMN_ID,SERVER_EQPMN_NM,SERVER_EQPMN_IP,SERVER_EQPMN_MNGR,OPERSYSM_INFO,CPU_INFO,MORY_INFO) VALUES ('SVR_DEMO_001','[더미] 웹서버 WEB-01','10.10.10.11','홍길동','Linux Ubuntu 22.04','8 vCPU','16GB');
INSERT INTO COMTNSERVEREQPMNINFO(SERVER_EQPMN_ID,SERVER_EQPMN_NM,SERVER_EQPMN_IP,SERVER_EQPMN_MNGR,OPERSYSM_INFO,CPU_INFO,MORY_INFO) VALUES ('SVR_DEMO_002','[더미] DB서버 DB-01','10.10.10.21','김담당','Linux RHEL 9','16 vCPU','64GB');
INSERT INTO COMTNCNTCSYSTEM(INSTT_ID,SYS_ID,SYS_NM,SYS_IP,FRST_REGISTER_ID,FRST_REGIST_PNTTM) VALUES ('INSTT_001','SYS_DEMO_01','[더미] 행정정보공동이용','10.20.30.40','admin','2026-05-01 09:00:00');
INSERT INTO COMTNCNTCSYSTEM(INSTT_ID,SYS_ID,SYS_NM,SYS_IP,FRST_REGISTER_ID,FRST_REGIST_PNTTM) VALUES ('INSTT_001','SYS_DEMO_02','[더미] 전자문서유통','10.20.30.41','admin','2026-05-02 10:00:00');
INSERT INTO COMTNNTTSTATS(STATS_ID,NTCE_CO,AVRG_RDCNT,TOP_RDCNT,MUMM_RDCNT,TOP_NTCR_ID) VALUES ('NTTSTAT_DEMO_001',45,120,890,5,'USRCNFRM_00000000000');
INSERT INTO COMTNNTTSTATS(STATS_ID,NTCE_CO,AVRG_RDCNT,TOP_RDCNT,MUMM_RDCNT,TOP_NTCR_ID) VALUES ('NTTSTAT_DEMO_002',38,95,640,3,'USRCNFRM_00000000000');
