-- 개정이력: 2026.06.30  구재호  전 DBMS TB_ 표준 명명 현행화(공통컴포넌트)
-- ============================================================
-- common-components-boot Altibase DDL (shtdb.sql HSQL 정본에서 생성)
-- 명명규칙: TB_ + snake_case / 감사컬럼 4종(FRST_REGIST_PNTTM, FRST_REGISTER_ID, LAST_UPDT_PNTTM, LAST_UPDUSR_ID)
-- 사용: altibase 에 적재 (DB명 예: ccm)
-- ============================================================

DROP VIEW VW_USER_MASTER;
DROP TABLE TB_MEMO_TODO;
DROP TABLE TB_COMMENT;
DROP TABLE TB_ADBK_MANAGE;
DROP TABLE TB_DAM_KNO_IFM;
DROP TABLE TB_NCRD;
DROP TABLE TB_BATCH_RESULT;
DROP TABLE TB_BATCH_SCHDUL;
DROP TABLE TB_BATCH_OPERT;
DROP TABLE TB_CNSLT_LIST;
DROP TABLE TB_CPYRHT_INFO;
DROP TABLE TB_ONLINE_MANUAL;
DROP TABLE TB_ONLINE_POLL_IEM;
DROP TABLE TB_ONLINE_POLL_MANAGE;
DROP TABLE TB_BNDT_CECK_MANAGE;
DROP TABLE TB_BNDT_DIARY;
DROP TABLE TB_BNDT_MANAGE;
DROP TABLE TB_VCATN_MANAGE;
DROP TABLE TB_EVENT_INFO;
DROP TABLE TB_RECENT_SRCHWRD;
DROP TABLE TB_RECENT_SRCHWRD_MANAGE;
DROP TABLE TB_MTG_INFO;
DROP TABLE TB_ANNVRSRY_MANAGE;
DROP TABLE TB_INDVDL_YRYC_MANAGE;
DROP TABLE TB_NOTE_RECPTN;
DROP TABLE TB_NOTE_TRNSMIT;
DROP TABLE TB_NOTE;
DROP TABLE TB_ADMINISTRATION_WORD;
DROP TABLE TB_COMMUTE;
DROP TABLE TB_HPCM_INFO;
DROP TABLE TB_INDVDL_PGE_CNTNTS;
DROP TABLE TB_WORD_DICARY_INFO;
DROP TABLE TB_MTG_PLACE_MANAGE;
DROP TABLE TB_LOGIN_SCRIN_IMAGE;
DROP TABLE TB_MAIN_IMAGE;
DROP TABLE TB_NEWS_INFO;
DROP TABLE TB_RWARD_MANAGE;
DROP TABLE TB_EVENT_MANAGE;
DROP TABLE TB_WIKI_BKMK;
DROP TABLE TB_POPUP_MANAGE;
DROP TABLE TB_SITE_LIST;
DROP TABLE TB_UNITY_LINK;
DROP TABLE TB_ROUGHMAP;
DROP TABLE TB_RECOMEND_SITE_INFO;
DROP TABLE TB_INTNET_SVC;
DROP TABLE TB_NTFC_INFO;
DROP TABLE TB_RSS;
DROP TABLE TB_CTSNN_MANAGE;
DROP TABLE TB_STPLAT_INFO;
DROP TABLE TB_QUSTNR_RSPNS_RESULT;
DROP TABLE TB_QUSTNR_RESPOND_INFO;
DROP TABLE TB_QUSTNR_IEM;
DROP TABLE TB_QUSTNR_QESITM;
DROP TABLE TB_QESTNR_INFO;
DROP TABLE TB_QUSTNR_TMPLAT;
DROP TABLE TB_MENU_CREAT_DTLS;
DROP TABLE TB_MENU_INFO;
DROP TABLE TB_PROGRM_LIST;
DROP TABLE TB_INDVDL_INFO_POLICY;
DROP TABLE TB_BANNER;
DROP TABLE TB_ZIP;
DROP TABLE TB_AUTHOR_ROLE_RELATE;
DROP TABLE TB_ROLE_INFO;
DROP TABLE TB_ROLES_HIERARCHY;

CREATE TABLE TB_ROLES_HIERARCHY (
PARNTS_ROLE varchar(30) NOT NULL,
  CHLDRN_ROLE varchar(30) NOT NULL,
  PRIMARY KEY (PARNTS_ROLE,CHLDRN_ROLE)
);
CREATE TABLE TB_ROLE_INFO (
ROLE_CODE varchar(50) DEFAULT '' NOT NULL,
  ROLE_NM varchar(60) NOT NULL,
  ROLE_PTTRN varchar(300) DEFAULT NULL,
  ROLE_DC varchar(200) DEFAULT NULL,
  ROLE_TY varchar(80) DEFAULT NULL,
  ROLE_SORT varchar(10) DEFAULT NULL,
  ROLE_CREAT_DE char(20) NOT NULL,
  PRIMARY KEY (ROLE_CODE)
);
CREATE TABLE TB_AUTHOR_ROLE_RELATE (
AUTHOR_CODE varchar(30) NOT NULL,
  ROLE_CODE varchar(50) NOT NULL,
  CREAT_DT date DEFAULT NULL,
  PRIMARY KEY (AUTHOR_CODE,ROLE_CODE)
);
CREATE TABLE TB_ZIP (
ZIP varchar(6) NOT NULL,
  SN number(10,0) DEFAULT '0' NOT NULL,
  CTPRVN_NM varchar(20) DEFAULT NULL,
  SIGNGU_NM varchar(20) DEFAULT NULL,
  EMD_NM varchar(60) DEFAULT NULL,
  LI_BULD_NM varchar(60) DEFAULT NULL,
  LNBR_DONG_HO varchar(20) DEFAULT NULL,
  FRST_REGIST_PNTTM date DEFAULT NULL,
  FRST_REGISTER_ID varchar(20) DEFAULT NULL,
  LAST_UPDT_PNTTM date DEFAULT NULL,
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  PRIMARY KEY (ZIP,SN)
);
CREATE TABLE TB_BANNER (
BANNER_ID char(20) DEFAULT '' NOT NULL,
  BANNER_NM varchar(60) NOT NULL,
  LINK_URL varchar(255) DEFAULT NULL,
  BANNER_IMAGE varchar(60) DEFAULT NULL,
  BANNER_DC varchar(200) DEFAULT NULL,
  REFLCT_AT char(1) NOT NULL,
  FRST_REGISTER_ID varchar(20) DEFAULT NULL,
  FRST_REGIST_PNTTM date DEFAULT NULL,
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  LAST_UPDT_PNTTM date DEFAULT NULL,
  BANNER_IMAGE_FILE varchar(60) DEFAULT NULL,
  SORT_ORDR number(8,0) DEFAULT NULL,
  BANNER_TY varchar(10) DEFAULT 'MAIN',
  POPUP_LEFT INT DEFAULT NULL,
  POPUP_TOP INT DEFAULT NULL,
  POPUP_WIDTH INT DEFAULT NULL,
  POPUP_HEIGHT INT DEFAULT NULL,
  POPUP_GROUP_AT char(1) DEFAULT 'N',
  EXPSR_BGNDE DATE DEFAULT NULL,
  EXPSR_ENDDE DATE DEFAULT NULL,
  PRIMARY KEY (BANNER_ID)
);
CREATE TABLE TB_INDVDL_INFO_POLICY (
INDVDL_INFO_POLICY_ID char(20) DEFAULT '' NOT NULL,
  INDVDL_INFO_POLICY_CN varchar(2500) DEFAULT NULL,
  INDVDL_INFO_POLICY_AGRE_AT char(1) DEFAULT NULL,
  VER varchar(20) DEFAULT NULL,
  APLC_DE varchar(8) DEFAULT NULL,
  REPRSNT_AT char(1) DEFAULT 'N',
  USE_AT char(1) DEFAULT 'Y',
  FRST_REGISTER_ID varchar(20) DEFAULT NULL,
  FRST_REGIST_PNTTM date DEFAULT NULL,
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  LAST_UPDT_PNTTM date DEFAULT NULL,
  INDVDL_INFO_POLICY_NM varchar(255) DEFAULT NULL,
  PRIMARY KEY (INDVDL_INFO_POLICY_ID)
);
CREATE TABLE TB_PROGRM_LIST (
PROGRM_FILE_NM varchar(60) DEFAULT '' NOT NULL,
  PROGRM_STRE_PATH varchar(100) NOT NULL,
  PROGRM_KOREAN_NM varchar(60) DEFAULT NULL,
  PROGRM_DC varchar(200) DEFAULT NULL,
  URL varchar(100) NOT NULL,
  PRIMARY KEY (PROGRM_FILE_NM)
);
CREATE TABLE TB_MENU_INFO (
MENU_NM varchar(60) NOT NULL,
  PROGRM_FILE_NM varchar(60) NOT NULL,
  MENU_NO number(20,0) NOT NULL,
  UPPER_MENU_NO number(20,0) DEFAULT NULL,
  MENU_ORDR number(5,0) NOT NULL,
  MENU_DC varchar(250) DEFAULT NULL,
  RELATE_IMAGE_PATH varchar(100) DEFAULT NULL,
  RELATE_IMAGE_NM varchar(60) DEFAULT NULL,
  PRIMARY KEY (MENU_NO)
);
CREATE TABLE TB_MENU_CREAT_DTLS (
MENU_NO number(20,0) NOT NULL,
  AUTHOR_CODE varchar(30) NOT NULL,
  MAPNG_CREAT_ID varchar(30) DEFAULT NULL,
  PRIMARY KEY (MENU_NO,AUTHOR_CODE)
);
CREATE TABLE TB_QUSTNR_TMPLAT (
QUSTNR_TMPLAT_ID char(20) NOT NULL,
  QUSTNR_TMPLAT_TY varchar(100) DEFAULT NULL,
  QUSTNR_TMPLAT_DC varchar(2000) DEFAULT NULL,
  QUSTNR_TMPLAT_PATH_NM varchar(100) DEFAULT NULL,
  FRST_REGIST_PNTTM date DEFAULT NULL,
  FRST_REGISTER_ID varchar(20) DEFAULT NULL,
  LAST_UPDT_PNTTM date DEFAULT NULL,
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  QUSTNR_TMPLAT_IMAGE_INFO blob,
  PRIMARY KEY (QUSTNR_TMPLAT_ID)
);
CREATE TABLE TB_QESTNR_INFO (
QUSTNR_TMPLAT_ID char(20) NOT NULL,
  QESTNR_ID char(20) NOT NULL,
  QUSTNR_SJ varchar(255) DEFAULT NULL,
  QUSTNR_PURPS varchar(1000) DEFAULT NULL,
  QUSTNR_WRITNG_GUIDANCE_CN varchar(2000) DEFAULT NULL,
  QUSTNR_TRGET varchar(1000) DEFAULT NULL,
  QUSTNR_BGNDE char(20)  DEFAULT NULL,
  QUSTNR_ENDDE char(20) DEFAULT NULL,
  FRST_REGIST_PNTTM date DEFAULT NULL,
  FRST_REGISTER_ID varchar(20) DEFAULT NULL,
  LAST_UPDT_PNTTM date DEFAULT NULL,
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  PRIMARY KEY (QUSTNR_TMPLAT_ID,QESTNR_ID)
);
CREATE TABLE TB_QUSTNR_QESITM (
QESTNR_ID char(20) NOT NULL,
  QUSTNR_QESITM_ID char(20) NOT NULL,
  QUSTNR_TMPLAT_ID char(20) NOT NULL,
  QESTN_SN number(10,0) DEFAULT NULL,
  QESTN_TY_CODE char(1) DEFAULT NULL,
  QESTN_CN varchar(2500) DEFAULT NULL,
  MXMM_CHOISE_CO number(5,0) DEFAULT NULL,
  FRST_REGIST_PNTTM date NOT NULL,
  FRST_REGISTER_ID varchar(20) NOT NULL,
  LAST_UPDT_PNTTM date NOT NULL,
  LAST_UPDUSR_ID varchar(20) NOT NULL,
  PRIMARY KEY (QESTNR_ID,QUSTNR_QESITM_ID,QUSTNR_TMPLAT_ID)
);
CREATE TABLE TB_QUSTNR_IEM (
QUSTNR_TMPLAT_ID char(20) NOT NULL,
  QESTNR_ID char(20) NOT NULL,
  QUSTNR_QESITM_ID char(20) NOT NULL,
  QUSTNR_IEM_ID varchar(20) NOT NULL,
  IEM_SN number(5,0) DEFAULT NULL,
  IEM_CN varchar(1000) DEFAULT NULL,
  ETC_ANSWER_AT char(1) DEFAULT NULL,
  FRST_REGIST_PNTTM date DEFAULT NULL,
  FRST_REGISTER_ID varchar(20) DEFAULT NULL,
  LAST_UPDT_PNTTM date DEFAULT NULL,
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  PRIMARY KEY (QUSTNR_TMPLAT_ID,QESTNR_ID,QUSTNR_QESITM_ID,QUSTNR_IEM_ID)
);
CREATE TABLE TB_QUSTNR_RESPOND_INFO (
QUSTNR_TMPLAT_ID char(20) NOT NULL,
  QESTNR_ID char(20) NOT NULL,
  QUSTNR_RESPOND_ID char(20) NOT NULL,
  SEXDSTN_CODE char(1) DEFAULT NULL,
  OCCP_TY_CODE varchar(10) DEFAULT NULL,
  RESPOND_NM varchar(50) DEFAULT NULL,
  BRTHDY char(20) DEFAULT NULL,
  AREA_NO varchar(4) DEFAULT NULL,
  MIDDLE_TELNO varchar(4) DEFAULT NULL,
  END_TELNO varchar(4) DEFAULT NULL,
  FRST_REGIST_PNTTM date DEFAULT NULL,
  FRST_REGISTER_ID varchar(20) DEFAULT NULL,
  LAST_UPDT_PNTTM date DEFAULT NULL,
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  PRIMARY KEY (QUSTNR_TMPLAT_ID,QESTNR_ID,QUSTNR_RESPOND_ID)
);
CREATE TABLE TB_QUSTNR_RSPNS_RESULT (
QUSTNR_RSPNS_RESULT_ID char(20) NOT NULL,
  QESTNR_ID char(20) NOT NULL,
  QUSTNR_QESITM_ID char(20) NOT NULL,
  QUSTNR_TMPLAT_ID char(20) NOT NULL,
  RESPOND_ANSWER_CN varchar(1000) DEFAULT NULL,
  ETC_ANSWER_CN varchar(1000) DEFAULT NULL,
  RESPOND_NM varchar(50) DEFAULT NULL,
  FRST_REGIST_PNTTM date DEFAULT NULL,
  FRST_REGISTER_ID varchar(20) DEFAULT NULL,
  LAST_UPDT_PNTTM date DEFAULT NULL,
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  QUSTNR_IEM_ID varchar(20) DEFAULT NULL,
  PRIMARY KEY (QUSTNR_RSPNS_RESULT_ID,QESTNR_ID,QUSTNR_QESITM_ID,QUSTNR_TMPLAT_ID)
);
CREATE TABLE TB_STPLAT_INFO (
USE_STPLAT_ID char(20) NOT NULL,
  USE_STPLAT_NM varchar(100) DEFAULT NULL,
  USE_STPLAT_CN varchar(4000),
  INFO_PROVD_AGRE_CN varchar(4000),
  VER varchar(20) DEFAULT NULL,
  APLC_DE varchar(8) DEFAULT NULL,
  REPRSNT_AT char(1) DEFAULT 'N',
  USE_AT char(1) DEFAULT 'Y',
  FRST_REGIST_PNTTM date DEFAULT NULL,
  FRST_REGISTER_ID varchar(20) DEFAULT NULL,
  LAST_UPDT_PNTTM date DEFAULT NULL,
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  PRIMARY KEY (USE_STPLAT_ID)
);
CREATE TABLE TB_CTSNN_MANAGE (
CTSNN_ID char(20) NOT NULL,
  USER_ID varchar(20) DEFAULT NULL,
  CTSNN_CODE varchar(6) DEFAULT NULL,
  REQST_DE varchar(20) DEFAULT NULL,
  CTSNN_NM varchar(100) DEFAULT NULL,
  TRGTER_NM varchar(50) DEFAULT NULL,
  BRTHDY varchar(20) DEFAULT NULL,
  OCCRRNC_DE varchar(20) DEFAULT NULL,
  RELATE varchar(6) DEFAULT NULL,
  RM varchar(4000),
  SANCTNER_ID varchar(20) DEFAULT NULL,
  CONFM_AT char(1) DEFAULT 'N',
  SANCTN_DT varchar(20) DEFAULT NULL,
  RETURN_RESN varchar(2000) DEFAULT NULL,
  INFRML_SANCTN_ID varchar(20) DEFAULT NULL,
  FRST_REGISTER_ID varchar(20) DEFAULT NULL,
  FRST_REGIST_PNTTM date DEFAULT NULL,
  LAST_UPDUSR_ID varchar(20) DEFAULT NULL,
  LAST_UPDT_PNTTM date DEFAULT NULL,
  PRIMARY KEY (CTSNN_ID)
);
CREATE TABLE TB_RSS (
RSS_ID varchar(20) NOT NULL, TRGET_SVC_NM varchar(100), TRGET_SVC_TABLE varchar(100),
  TRGET_SVC_LIST_CO number(6), HDER_TITLE varchar(200), HDER_LINK varchar(200), HDER_DC varchar(500),
  HDER_TAG varchar(200), HDER_ETC varchar(200), BDT_TITLE varchar(200), BDT_LINK varchar(200),
  BDT_DC varchar(500), BDT_TAG varchar(200), BDT_ETC_TAG varchar(200),
  FRST_REGIST_PNTTM date, FRST_REGISTER_ID varchar(20), LAST_UPDT_PNTTM date, LAST_UPDUSR_ID varchar(20),
  PRIMARY KEY (RSS_ID)
);
CREATE TABLE TB_NTFC_INFO (
NTCN_NO number(10) NOT NULL, NTCN_SJ varchar(200), NTCN_CN varchar(4000), NTCN_TM varchar(20),
  BH_NTCN_INTRVL varchar(100), FRST_REGISTER_ID varchar(20), FRST_REGIST_PNTTM date,
  LAST_UPDUSR_ID varchar(20), LAST_UPDT_PNTTM date, PRIMARY KEY (NTCN_NO)
);
CREATE TABLE TB_INTNET_SVC (
INTNET_SVC_ID varchar(20) NOT NULL, INTNET_SVC_NM varchar(200), INTNET_SVC_DC varchar(4000),
  REFLCT_AT varchar(1) DEFAULT 'N', FRST_REGISTER_ID varchar(20), FRST_REGIST_PNTTM date,
  LAST_UPDUSR_ID varchar(20), LAST_UPDT_PNTTM date, PRIMARY KEY (INTNET_SVC_ID)
);
CREATE TABLE TB_RECOMEND_SITE_INFO (
RECOMEND_SITE_ID varchar(20) NOT NULL, RECOMEND_SITE_URL varchar(300), RECOMEND_SITE_NM varchar(200),
  RECOMEND_SITE_DC varchar(4000), RECOMEND_RESN_CN varchar(4000), RECOMEND_CONFM_AT varchar(1) DEFAULT 'N',
  CONFM_DE varchar(20), FRST_REGIST_PNTTM date, FRST_REGISTER_ID varchar(20),
  LAST_UPDT_PNTTM date, LAST_UPDUSR_ID varchar(20), PRIMARY KEY (RECOMEND_SITE_ID)
);
CREATE TABLE TB_ROUGHMAP (
ROUGHMAP_ID varchar(20) NOT NULL, ROUGHMAPSJ varchar(200), ROUGHMAPADDRESS varchar(300),
  LA varchar(30), LO varchar(30), MARKERLA varchar(30), MARKERLO varchar(30), INFOWINDOW varchar(4000), ZOOMLEVEL varchar(5),
  FRST_REGISTER_ID varchar(20), FRST_REGIST_PNTTM date, LAST_UPDUSR_ID varchar(20), LAST_UPDT_PNTTM date,
  PRIMARY KEY (ROUGHMAP_ID)
);
CREATE TABLE TB_UNITY_LINK (
UNITY_LINK_ID varchar(20) NOT NULL, UNITY_LINK_SE_CODE varchar(20), UNITY_LINK_NM varchar(200),
  UNITY_LINK_URL varchar(300), UNITY_LINK_DC varchar(4000),
  FRST_REGIST_PNTTM date, FRST_REGISTER_ID varchar(20), LAST_UPDT_PNTTM date, LAST_UPDUSR_ID varchar(20),
  PRIMARY KEY (UNITY_LINK_ID)
);
CREATE TABLE TB_SITE_LIST (
SITE_ID varchar(20) NOT NULL, SITE_URL varchar(300), SITE_NM varchar(200), SITE_DC varchar(4000),
  SITE_THEMA_CL_CODE varchar(20), ACTVTY_AT varchar(1) DEFAULT 'Y', USE_AT varchar(1) DEFAULT 'Y',
  FRST_REGIST_PNTTM date, FRST_REGISTER_ID varchar(20), LAST_UPDT_PNTTM date, LAST_UPDUSR_ID varchar(20),
  PRIMARY KEY (SITE_ID)
);
CREATE TABLE TB_POPUP_MANAGE (
POPUP_ID varchar(20) NOT NULL, POPUP_SJ_NM varchar(200), FILE_URL varchar(300),
  POPUP_VRTICL_LC varchar(10), POPUP_WIDTH_LC varchar(10), POPUP_VRTICL_SIZE varchar(10), POPUP_WIDTH_SIZE varchar(10),
  NTCE_BGNDE varchar(20), NTCE_ENDDE varchar(20), STOPVEW_SETUP_AT varchar(1) DEFAULT 'N', NTCE_AT varchar(1) DEFAULT 'Y',
  FRST_REGIST_PNTTM date, FRST_REGISTER_ID varchar(20), LAST_UPDT_PNTTM date, LAST_UPDUSR_ID varchar(20),
  PRIMARY KEY (POPUP_ID)
);
CREATE TABLE TB_WIKI_BKMK (
WIKI_BKMK_ID varchar(20) NOT NULL, USER_ID varchar(20), WIKI_BKMK_NM varchar(200),
  FRST_REGIST_PNTTM date, FRST_REGISTER_ID varchar(20), LAST_UPDT_PNTTM date, LAST_UPDUSR_ID varchar(20),
  PRIMARY KEY (WIKI_BKMK_ID)
);
CREATE TABLE TB_EVENT_MANAGE (
EVENT_ID varchar(20) NOT NULL, EVENT_SE varchar(20), EVENT_NM varchar(200), EVENT_PURPS varchar(4000),
  EVENT_BGNDE varchar(20), EVENT_ENDDE varchar(20), EVENT_AUSPC_INSTT_NM varchar(100), EVENT_MNGT_INSTT_NM varchar(100),
  EVENT_PLACE varchar(200), EVENT_CN varchar(4000), CT_OCCRRNC_AT varchar(1) DEFAULT 'N', PARTCPT_CT varchar(100),
  PSNCPA varchar(100), REFRN_URL varchar(300), RCEPT_BGNDE varchar(20), RCEPT_ENDDE varchar(20),
  FRST_REGISTER_ID varchar(20), FRST_REGIST_PNTTM date, LAST_UPDUSR_ID varchar(20), LAST_UPDT_PNTTM date,
  PRIMARY KEY (EVENT_ID)
);
CREATE TABLE TB_RWARD_MANAGE (
RWARD_ID varchar(20) NOT NULL, RWARDWNR_ID varchar(20), RWARD_CODE varchar(20), RWARD_DE varchar(20), RWARD_NM varchar(200),
  PBLEN_CN varchar(4000), SANCTNER_ID varchar(20), CONFM_AT varchar(1) DEFAULT 'N', SANCTN_DT varchar(20), RETURN_RESN varchar(4000),
  ATCH_FILE_ID varchar(20), INFRML_SANCTN_ID varchar(20),
  FRST_REGISTER_ID varchar(20), FRST_REGIST_PNTTM date, LAST_UPDUSR_ID varchar(20), LAST_UPDT_PNTTM date,
  PRIMARY KEY (RWARD_ID)
);
CREATE TABLE TB_NEWS_INFO (
NEWS_ID varchar(20) NOT NULL, NEWS_SJ varchar(200), NEWS_CN varchar(4000), NEWS_ORIGIN varchar(200),
  NTCE_DE varchar(20), ATCH_FILE_ID varchar(20),
  FRST_REGISTER_ID varchar(20), FRST_REGIST_PNTTM date, LAST_UPDUSR_ID varchar(20), LAST_UPDT_PNTTM date,
  PRIMARY KEY (NEWS_ID)
);
CREATE TABLE TB_MAIN_IMAGE (
IMAGE_ID varchar(20) NOT NULL, IMAGE_NM varchar(200), IMAGE varchar(300), IMAGE_FILE varchar(300),
  IMAGE_DC varchar(4000), REFLCT_AT varchar(1) DEFAULT 'N',
  FRST_REGISTER_ID varchar(20), FRST_REGIST_PNTTM date, LAST_UPDUSR_ID varchar(20), LAST_UPDT_PNTTM date,
  PRIMARY KEY (IMAGE_ID)
);
CREATE TABLE TB_LOGIN_SCRIN_IMAGE (
IMAGE_ID varchar(20) NOT NULL, IMAGE_NM varchar(200), IMAGE varchar(300), IMAGE_FILE varchar(300),
  IMAGE_DC varchar(4000), REFLCT_AT varchar(1) DEFAULT 'N',
  FRST_REGISTER_ID varchar(20), FRST_REGIST_PNTTM date, LAST_UPDUSR_ID varchar(20), LAST_UPDT_PNTTM date,
  PRIMARY KEY (IMAGE_ID)
);
CREATE TABLE TB_MTG_PLACE_MANAGE (
MTGRUM_ID varchar(20) NOT NULL, MTGRUM_NM varchar(200), OPN_BEGIN_TM varchar(10), OPN_END_TM varchar(10),
  ACEPTNC_POSBL_NMPR number(6), LC_SE varchar(20), LC_DETAIL varchar(300), ATCH_FILE_ID varchar(20),
  FRST_REGISTER_ID varchar(20), FRST_REGIST_PNTTM date, LAST_UPDUSR_ID varchar(20), LAST_UPDT_PNTTM date,
  PRIMARY KEY (MTGRUM_ID)
);
CREATE TABLE TB_WORD_DICARY_INFO (
WORD_ID varchar(20) NOT NULL, WORD_NM varchar(200), ENG_NM varchar(200), WORD_DC varchar(4000), SYNONM varchar(300),
  FRST_REGISTER_ID varchar(20), FRST_REGIST_PNTTM date, LAST_UPDUSR_ID varchar(20), LAST_UPDT_PNTTM date,
  PRIMARY KEY (WORD_ID)
);
CREATE TABLE TB_INDVDL_PGE_CNTNTS (
CNTNTS_ID varchar(20) NOT NULL, CNTNTS_NM varchar(200), CNTC_URL varchar(300), CNTNTS_USE_AT varchar(1) DEFAULT 'Y',
  CNTNTS_LINK_URL varchar(300), CNTNTS_DC varchar(4000),
  FRST_REGISTER_ID varchar(20), FRST_REGIST_PNTTM date, LAST_UPDUSR_ID varchar(20), LAST_UPDT_PNTTM date,
  PRIMARY KEY (CNTNTS_ID)
);
CREATE TABLE TB_HPCM_INFO (
HPCM_ID varchar(20) NOT NULL, HPCM_SE_CODE varchar(20), HPCM_DFN varchar(300), HPCM_DC varchar(4000),
  FRST_REGISTER_ID varchar(20), FRST_REGIST_PNTTM date, LAST_UPDUSR_ID varchar(20), LAST_UPDT_PNTTM date,
  PRIMARY KEY (HPCM_ID)
);
CREATE TABLE TB_COMMUTE (
WRKTM_ID varchar(20) NOT NULL, EMPLYR_ID varchar(20), ORGNZT_ID varchar(20), WRKT_DT varchar(20),
  WRK_START_TIME varchar(10), WRK_END_TIME varchar(10), WRK_HOURS varchar(10), OVTMWRK_HOURS varchar(10),
  WRK_START_STATUS varchar(1), WRK_END_STATUS varchar(1),
  FRST_REGISTER_ID varchar(20), FRST_REGIST_PNTTM date, LAST_UPDUSR_ID varchar(20), LAST_UPDT_PNTTM date,
  PRIMARY KEY (WRKTM_ID)
);
CREATE TABLE TB_ADMINISTRATION_WORD (
ADMINIST_WORD_ID varchar(20) NOT NULL, ADMINIST_WORD_NM varchar(200), ADMINIST_WORD_ENG_NM varchar(200),
  ADMINIST_WORD_ABRV_NM varchar(100), THEMA_RELM varchar(100), WORD_SE varchar(20), RELATE_STD_WORD varchar(200),
  ADMINIST_WORD_DFN varchar(4000), ADMINIST_WORD_DC varchar(4000),
  FRST_REGISTER_ID varchar(20), FRST_REGIST_PNTTM date, LAST_UPDUSR_ID varchar(20), LAST_UPDT_PNTTM date,
  PRIMARY KEY (ADMINIST_WORD_ID)
);
CREATE TABLE TB_NOTE (
NOTE_ID varchar(20) NOT NULL, NOTE_SJ varchar(200), NOTE_CN varchar(4000), ATCH_FILE_ID varchar(20),
  FRST_REGISTER_ID varchar(20), FRST_REGIST_PNTTM date, LAST_UPDUSR_ID varchar(20), LAST_UPDT_PNTTM date,
  PRIMARY KEY (NOTE_ID)
);
CREATE TABLE TB_NOTE_TRNSMIT (
NOTE_TRNSMIT_ID varchar(20) NOT NULL, NOTE_ID varchar(20), TRNSMITER_ID varchar(20), DELETE_AT varchar(1) DEFAULT 'N',
  FRST_REGISTER_ID varchar(20), FRST_REGIST_PNTTM date, LAST_UPDUSR_ID varchar(20), LAST_UPDT_PNTTM date,
  PRIMARY KEY (NOTE_TRNSMIT_ID)
);
CREATE TABLE TB_NOTE_RECPTN (
NOTE_RECPTN_ID varchar(20) NOT NULL, NOTE_ID varchar(20), NOTE_TRNSMIT_ID varchar(20), RCVER_ID varchar(20),
  READNG_AT varchar(1) DEFAULT 'N', OPEN_YN varchar(1) DEFAULT 'N', RECPTN_SE varchar(20) DEFAULT '01', DELETE_AT varchar(1) DEFAULT 'N',
  FRST_REGISTER_ID varchar(20), FRST_REGIST_PNTTM date, LAST_UPDUSR_ID varchar(20), LAST_UPDT_PNTTM date,
  PRIMARY KEY (NOTE_RECPTN_ID)
);
CREATE TABLE TB_INDVDL_YRYC_MANAGE (
OCCRRNC_YEAR varchar(4) NOT NULL, USER_ID varchar(20) NOT NULL,
  YRYC_OCCRRNC_CO number(5,1), USE_YRYC_CO number(5,1), REMNDR_YRYC_CO number(5,1),
  FRST_REGISTER_ID varchar(20), FRST_REGIST_PNTTM date, LAST_UPDUSR_ID varchar(20), LAST_UPDT_PNTTM date,
  PRIMARY KEY (OCCRRNC_YEAR, USER_ID)
);
CREATE TABLE TB_ANNVRSRY_MANAGE (
ANNVRSRY_ID varchar(20) NOT NULL, USER_ID varchar(20), ANNVRSRY_SE varchar(20), ANNVRSRY_NM varchar(200),
  ANNVRSRY varchar(20), CLDR_SE varchar(20), ANNVRSRY_NTCN_SETUP varchar(20), ANNVRSRY_NTCN_BGNDE varchar(20),
  MEMO varchar(4000), REPTIT_AT varchar(1) DEFAULT 'N',
  FRST_REGISTER_ID varchar(20), FRST_REGIST_PNTTM date, LAST_UPDUSR_ID varchar(20), LAST_UPDT_PNTTM date,
  PRIMARY KEY (ANNVRSRY_ID)
);
CREATE TABLE TB_MTG_INFO (
MTG_ID varchar(20) NOT NULL, MTG_NM varchar(200), MTG_MTR_CN varchar(4000), MTG_SN varchar(20), MTG_CO varchar(20),
  MTG_DE varchar(20), MTG_PLACE varchar(200), MTG_BEGIN_TM varchar(10), MTG_END_TM varchar(10),
  CLSDR_MTG_AT varchar(1) DEFAULT 'N', READNG_BGNDE varchar(20), READNG_AT varchar(1) DEFAULT 'N',
  MTG_RESULT_CN varchar(4000), MTG_RESULT_ENNC varchar(200), ETC_MATTER varchar(4000),
  MNGT_DEPT_ID varchar(20), MNAER_ID varchar(20), MNAER_DEPT_ID varchar(20), MTG_AT varchar(1) DEFAULT 'N',
  NONATDRN_CO number(6), ATDRN_CO number(6),
  FRST_REGISTER_ID varchar(20), FRST_REGIST_PNTTM date, LAST_UPDUSR_ID varchar(20), LAST_UPDT_PNTTM date,
  PRIMARY KEY (MTG_ID)
);
CREATE TABLE TB_RECENT_SRCHWRD_MANAGE (
SRCHWRD_MANAGE_ID varchar(20) NOT NULL, SRCHWRD_MANAGE_NM varchar(200), SRCHWRD_CONECT_URL varchar(300),
  USER_SEARCH_AT varchar(1) DEFAULT 'Y',
  FRST_REGISTER_ID varchar(20), FRST_REGIST_PNTTM date, LAST_UPDUSR_ID varchar(20), LAST_UPDT_PNTTM date,
  PRIMARY KEY (SRCHWRD_MANAGE_ID)
);
CREATE TABLE TB_RECENT_SRCHWRD (
SRCHWRD_ID varchar(20) NOT NULL, SRCHWRD_MANAGE_ID varchar(20), SRCHWRD_NM varchar(200), SRCHWRD_CO number(10) DEFAULT 0,
  FRST_REGISTER_ID varchar(20), FRST_REGIST_PNTTM date, LAST_UPDUSR_ID varchar(20), LAST_UPDT_PNTTM date,
  PRIMARY KEY (SRCHWRD_ID)
);
CREATE TABLE TB_EVENT_INFO (
EVENT_ID varchar(20) NOT NULL, BSNS_YEAR varchar(4), BSNS_CODE varchar(20),
  EVENT_SVC_BGNDE varchar(20), EVENT_SVC_ENDDE varchar(20), SVC_USE_NMPR_CO number(8), CHARGER_NM varchar(50),
  EVENT_CN varchar(4000), EVENT_TY_CODE varchar(20), PRPARETG_CN varchar(4000), EVENT_CONFM_AT varchar(1) DEFAULT 'N', EVENT_CONFM_DE varchar(20),
  FRST_REGISTER_ID varchar(20), FRST_REGIST_PNTTM date, LAST_UPDUSR_ID varchar(20), LAST_UPDT_PNTTM date,
  PRIMARY KEY (EVENT_ID)
);
CREATE TABLE TB_VCATN_MANAGE (
APPLCNT_ID varchar(20) NOT NULL, VCATN_SE varchar(20) NOT NULL, OCCRRNC_YEAR varchar(4),
  BGNDE varchar(20) NOT NULL, ENDDE varchar(20) NOT NULL, REQST_DE varchar(20), VCATN_RESN varchar(500),
  NOON_SE varchar(20), SANCTNER_ID varchar(20), CONFM_AT varchar(1) DEFAULT 'N', SANCTN_DT varchar(20),
  RETURN_RESN varchar(500), INFRML_SANCTN_ID varchar(20),
  FRST_REGISTER_ID varchar(20), FRST_REGIST_PNTTM date, LAST_UPDUSR_ID varchar(20), LAST_UPDT_PNTTM date,
  PRIMARY KEY (APPLCNT_ID, VCATN_SE, BGNDE, ENDDE)
);
CREATE TABLE TB_BNDT_MANAGE (
BNDT_ID varchar(20) NOT NULL, BNDT_DE varchar(20) NOT NULL, RM varchar(2000),
  FRST_REGISTER_ID varchar(20), FRST_REGIST_PNTTM date, LAST_UPDUSR_ID varchar(20), LAST_UPDT_PNTTM date,
  PRIMARY KEY (BNDT_ID, BNDT_DE)
);
CREATE TABLE TB_BNDT_DIARY (
BNDT_ID varchar(20) NOT NULL, BNDT_DE varchar(20) NOT NULL, RM varchar(2000),
  FRST_REGISTER_ID varchar(20), FRST_REGIST_PNTTM date, LAST_UPDUSR_ID varchar(20), LAST_UPDT_PNTTM date,
  PRIMARY KEY (BNDT_ID, BNDT_DE)
);
CREATE TABLE TB_BNDT_CECK_MANAGE (
BNDT_ID varchar(20) NOT NULL, BNDT_DE varchar(20) NOT NULL, RM varchar(2000),
  FRST_REGISTER_ID varchar(20), FRST_REGIST_PNTTM date, LAST_UPDUSR_ID varchar(20), LAST_UPDT_PNTTM date,
  PRIMARY KEY (BNDT_ID, BNDT_DE)
);
CREATE TABLE TB_ONLINE_POLL_MANAGE (
POLL_ID varchar(20) NOT NULL, POLL_NM varchar(200), POLL_BGNDE varchar(20), POLL_ENDDE varchar(20),
  POLL_KND varchar(20), POLL_DSUSE_ENNC varchar(1) DEFAULT 'N', POLL_ATMC_DSUSE_ENNC varchar(1) DEFAULT 'N', QESITM_CN varchar(4000),
  FRST_REGISTER_ID varchar(20), FRST_REGIST_PNTTM date, LAST_UPDUSR_ID varchar(20), LAST_UPDT_PNTTM date,
  PRIMARY KEY (POLL_ID)
);
CREATE TABLE TB_ONLINE_POLL_IEM (
POLL_ID varchar(20) NOT NULL, POLL_IEM_ID varchar(20) NOT NULL, POLL_IEM_NM varchar(200),
  FRST_REGISTER_ID varchar(20), FRST_REGIST_PNTTM date, LAST_UPDUSR_ID varchar(20), LAST_UPDT_PNTTM date,
  PRIMARY KEY (POLL_ID, POLL_IEM_ID)
);
CREATE TABLE TB_ONLINE_MANUAL (
ONLINE_MNL_ID varchar(20) NOT NULL, ONLINE_MNL_NM varchar(200), ONLINE_MNL_SE_CODE varchar(20),
  ONLINE_MNL_DFN varchar(500), ONLINE_MNL_DC varchar(4000),
  FRST_REGISTER_ID varchar(20), FRST_REGIST_PNTTM date, LAST_UPDUSR_ID varchar(20), LAST_UPDT_PNTTM date,
  PRIMARY KEY (ONLINE_MNL_ID)
);
CREATE TABLE TB_CPYRHT_INFO (
CPYRHT_ID varchar(20) NOT NULL, CPYRHT_PRTC_POLICY_CN varchar(4000),
  FRST_REGISTER_ID varchar(20), FRST_REGIST_PNTTM date, LAST_UPDUSR_ID varchar(20), LAST_UPDT_PNTTM date,
  PRIMARY KEY (CPYRHT_ID)
);
CREATE TABLE TB_CNSLT_LIST (
CNSLT_ID varchar(20) NOT NULL, CNSLT_SJ varchar(200), CNSLT_CN varchar(4000), OTHBC_AT varchar(1) DEFAULT 'Y',
  EMAIL_ADRES varchar(100), EMAIL_ANSWER_AT varchar(1) DEFAULT 'N', AREA_NO varchar(10),
  FRST_REGISTER_ID varchar(20), FRST_REGIST_PNTTM date, LAST_UPDUSR_ID varchar(20), LAST_UPDT_PNTTM date,
  PRIMARY KEY (CNSLT_ID)
);
CREATE TABLE TB_BATCH_OPERT (
BATCH_OPERT_ID varchar(20) NOT NULL, BATCH_OPERT_NM varchar(100), BATCH_PROGRM varchar(500), PARAMTR varchar(500), USE_AT varchar(1) DEFAULT 'Y',
  FRST_REGISTER_ID varchar(20), FRST_REGIST_PNTTM date, LAST_UPDUSR_ID varchar(20), LAST_UPDT_PNTTM date,
  PRIMARY KEY (BATCH_OPERT_ID)
);
CREATE TABLE TB_BATCH_SCHDUL (
BATCH_SCHDUL_ID varchar(20) NOT NULL, BATCH_OPERT_ID varchar(20), EXECUT_CYCLE varchar(20),
  EXECUT_SCHDUL_DE varchar(20), EXECUT_SCHDUL_HOUR varchar(2), EXECUT_SCHDUL_MNT varchar(2), EXECUT_SCHDUL_SECND varchar(2),
  FRST_REGISTER_ID varchar(20), FRST_REGIST_PNTTM date, LAST_UPDUSR_ID varchar(20), LAST_UPDT_PNTTM date,
  PRIMARY KEY (BATCH_SCHDUL_ID)
);
CREATE TABLE TB_BATCH_RESULT (
BATCH_RESULT_ID varchar(20) NOT NULL, BATCH_SCHDUL_ID varchar(20), BATCH_OPERT_ID varchar(20), PARAMTR varchar(500),
  STTUS varchar(1), ERROR_INFO varchar(2000), EXECUT_BEGIN_TM varchar(14), EXECUT_END_TM varchar(14),
  FRST_REGISTER_ID varchar(20), FRST_REGIST_PNTTM date, LAST_UPDUSR_ID varchar(20), LAST_UPDT_PNTTM date,
  PRIMARY KEY (BATCH_RESULT_ID)
);
CREATE TABLE TB_NCRD (
NCRD_ID varchar(20) NOT NULL, NM varchar(50), NCRD_TRGTER_ID varchar(20), OTHBC_AT varchar(1) DEFAULT 'Y', EXTRL_USER_AT varchar(1) DEFAULT 'N',
  CMPNY_NM varchar(100), DEPT_NM varchar(100), OFCPS_NM varchar(60), IDNTFC_NO varchar(50),
  FRST_MBTLNUM varchar(4), MIDDLE_MBTLNUM varchar(4), END_MBTLNUM varchar(4), EMAIL_ADRES varchar(100),
  ADRES varchar(300), ZIP_CODE varchar(6), REMARK varchar(2000),
  FRST_REGISTER_ID varchar(20), FRST_REGIST_PNTTM date, LAST_UPDUSR_ID varchar(20), LAST_UPDT_PNTTM date,
  PRIMARY KEY (NCRD_ID)
);
CREATE TABLE TB_DAM_KNO_IFM (
KNWLDG_ID varchar(20) NOT NULL, KNWLDG_NM varchar(200), KNWLDG_CN varchar(4000), KNWLDG_TY_CODE varchar(20),
  KNWLDG_EVL varchar(1) DEFAULT '1', OTHBC_AT varchar(1) DEFAULT 'Y', EVL_DE varchar(20), ATCH_FILE_ID varchar(20),
  FRST_REGISTER_ID varchar(20), FRST_REGIST_PNTTM date, LAST_UPDUSR_ID varchar(20), LAST_UPDT_PNTTM date,
  PRIMARY KEY (KNWLDG_ID)
);
CREATE TABLE TB_ADBK_MANAGE (
ADBK_ID varchar(20) NOT NULL, ADBK_NM varchar(100), OTHBC_SCOPE varchar(20) DEFAULT '회사', USE_AT varchar(1) DEFAULT 'Y',
  WRTER_ID varchar(20), TRGET_ORGNZT_ID varchar(20),
  FRST_REGISTER_ID varchar(20), FRST_REGIST_PNTTM date, LAST_UPDUSR_ID varchar(20), LAST_UPDT_PNTTM date,
  PRIMARY KEY (ADBK_ID)
);
CREATE TABLE TB_COMMENT (
ANSWER_NO number(20) NOT NULL, NTT_ID number(20) NOT NULL, BBS_ID varchar(20) NOT NULL,
  WRTER_ID varchar(20), WRTER_NM varchar(50), ANSWER varchar(2000), PASSWORD varchar(200), USE_AT varchar(1) DEFAULT 'Y',
  FRST_REGISTER_ID varchar(20), FRST_REGIST_PNTTM date, LAST_UPDUSR_ID varchar(20), LAST_UPDT_PNTTM date,
  PRIMARY KEY (ANSWER_NO, NTT_ID, BBS_ID)
);
CREATE TABLE TB_MEMO_TODO (
TODO_ID varchar(20) NOT NULL, TODO_SJ varchar(200), TODO_CN varchar(4000), TODO_BEGIN_TIME varchar(20), TODO_END_TIME varchar(20), WRTER_ID varchar(20),
  FRST_REGISTER_ID varchar(20), FRST_REGIST_PNTTM date, LAST_UPDUSR_ID varchar(20), LAST_UPDT_PNTTM date,
  PRIMARY KEY (TODO_ID)
);

CREATE VIEW VW_USER_MASTER (ESNTL_ID, USER_ID, PASSWORD, USER_NM, USER_ZIP, USER_ADRES, USER_EMAIL, GROUP_ID, USER_SE, ORGNZT_ID) AS SELECT ESNTL_ID, MBER_ID, PASSWORD, MBER_NM, ZIP, ADRES, MBER_EMAIL_ADRES, ' ', 'GNR', ' ' FROM TB_GNRL_MBER UNION ALL SELECT ESNTL_ID, EMPLYR_ID, PASSWORD, USER_NM, ZIP, HOUSE_ADRES, EMAIL_ADRES, GROUP_ID, 'USR', ORGNZT_ID FROM TB_EMPLYR_INFO UNION ALL SELECT ESNTL_ID, ENTRPRS_MBER_ID, ENTRPRS_MBER_PASSWORD, CMPNY_NM, ZIP, ADRES, APPLCNT_EMAIL_ADRES, ' ', 'ENT', ' ' FROM TB_ENTRPRS_MBER;
